/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountRatedTvEpisodes200ResponseResultsInner
 */
export interface AccountRatedTvEpisodes200ResponseResultsInner {
    /**
     * 
     * @type {string}
     * @memberof AccountRatedTvEpisodes200ResponseResultsInner
     */
    airDate?: string;
    /**
     * 
     * @type {number}
     * @memberof AccountRatedTvEpisodes200ResponseResultsInner
     */
    episodeNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof AccountRatedTvEpisodes200ResponseResultsInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof AccountRatedTvEpisodes200ResponseResultsInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountRatedTvEpisodes200ResponseResultsInner
     */
    overview?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountRatedTvEpisodes200ResponseResultsInner
     */
    productionCode?: string;
    /**
     * 
     * @type {number}
     * @memberof AccountRatedTvEpisodes200ResponseResultsInner
     */
    runtime?: number;
    /**
     * 
     * @type {number}
     * @memberof AccountRatedTvEpisodes200ResponseResultsInner
     */
    seasonNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof AccountRatedTvEpisodes200ResponseResultsInner
     */
    showId?: number;
    /**
     * 
     * @type {string}
     * @memberof AccountRatedTvEpisodes200ResponseResultsInner
     */
    stillPath?: string;
    /**
     * 
     * @type {number}
     * @memberof AccountRatedTvEpisodes200ResponseResultsInner
     */
    voteAverage?: number;
    /**
     * 
     * @type {number}
     * @memberof AccountRatedTvEpisodes200ResponseResultsInner
     */
    voteCount?: number;
    /**
     * 
     * @type {number}
     * @memberof AccountRatedTvEpisodes200ResponseResultsInner
     */
    rating?: number;
}

/**
 * Check if a given object implements the AccountRatedTvEpisodes200ResponseResultsInner interface.
 */
export function instanceOfAccountRatedTvEpisodes200ResponseResultsInner(value: object): value is AccountRatedTvEpisodes200ResponseResultsInner {
    return true;
}

export function AccountRatedTvEpisodes200ResponseResultsInnerFromJSON(json: any): AccountRatedTvEpisodes200ResponseResultsInner {
    return AccountRatedTvEpisodes200ResponseResultsInnerFromJSONTyped(json, false);
}

export function AccountRatedTvEpisodes200ResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountRatedTvEpisodes200ResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'airDate': json['air_date'] == null ? undefined : json['air_date'],
        'episodeNumber': json['episode_number'] == null ? undefined : json['episode_number'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'overview': json['overview'] == null ? undefined : json['overview'],
        'productionCode': json['production_code'] == null ? undefined : json['production_code'],
        'runtime': json['runtime'] == null ? undefined : json['runtime'],
        'seasonNumber': json['season_number'] == null ? undefined : json['season_number'],
        'showId': json['show_id'] == null ? undefined : json['show_id'],
        'stillPath': json['still_path'] == null ? undefined : json['still_path'],
        'voteAverage': json['vote_average'] == null ? undefined : json['vote_average'],
        'voteCount': json['vote_count'] == null ? undefined : json['vote_count'],
        'rating': json['rating'] == null ? undefined : json['rating'],
    };
}

export function AccountRatedTvEpisodes200ResponseResultsInnerToJSON(json: any): AccountRatedTvEpisodes200ResponseResultsInner {
    return AccountRatedTvEpisodes200ResponseResultsInnerToJSONTyped(json, false);
}

export function AccountRatedTvEpisodes200ResponseResultsInnerToJSONTyped(value?: AccountRatedTvEpisodes200ResponseResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'air_date': value['airDate'],
        'episode_number': value['episodeNumber'],
        'id': value['id'],
        'name': value['name'],
        'overview': value['overview'],
        'production_code': value['productionCode'],
        'runtime': value['runtime'],
        'season_number': value['seasonNumber'],
        'show_id': value['showId'],
        'still_path': value['stillPath'],
        'vote_average': value['voteAverage'],
        'vote_count': value['voteCount'],
        'rating': value['rating'],
    };
}

