/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountWatchlistTv200ResponseResultsInner } from './AccountWatchlistTv200ResponseResultsInner';
import {
    AccountWatchlistTv200ResponseResultsInnerFromJSON,
    AccountWatchlistTv200ResponseResultsInnerFromJSONTyped,
    AccountWatchlistTv200ResponseResultsInnerToJSON,
    AccountWatchlistTv200ResponseResultsInnerToJSONTyped,
} from './AccountWatchlistTv200ResponseResultsInner';

/**
 * 
 * @export
 * @interface AccountWatchlistTv200Response
 */
export interface AccountWatchlistTv200Response {
    /**
     * 
     * @type {number}
     * @memberof AccountWatchlistTv200Response
     */
    page?: number;
    /**
     * 
     * @type {Array<AccountWatchlistTv200ResponseResultsInner>}
     * @memberof AccountWatchlistTv200Response
     */
    results?: Array<AccountWatchlistTv200ResponseResultsInner>;
    /**
     * 
     * @type {number}
     * @memberof AccountWatchlistTv200Response
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof AccountWatchlistTv200Response
     */
    totalResults?: number;
}

/**
 * Check if a given object implements the AccountWatchlistTv200Response interface.
 */
export function instanceOfAccountWatchlistTv200Response(value: object): value is AccountWatchlistTv200Response {
    return true;
}

export function AccountWatchlistTv200ResponseFromJSON(json: any): AccountWatchlistTv200Response {
    return AccountWatchlistTv200ResponseFromJSONTyped(json, false);
}

export function AccountWatchlistTv200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountWatchlistTv200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'] == null ? undefined : json['page'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(AccountWatchlistTv200ResponseResultsInnerFromJSON)),
        'totalPages': json['total_pages'] == null ? undefined : json['total_pages'],
        'totalResults': json['total_results'] == null ? undefined : json['total_results'],
    };
}

export function AccountWatchlistTv200ResponseToJSON(json: any): AccountWatchlistTv200Response {
    return AccountWatchlistTv200ResponseToJSONTyped(json, false);
}

export function AccountWatchlistTv200ResponseToJSONTyped(value?: AccountWatchlistTv200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(AccountWatchlistTv200ResponseResultsInnerToJSON)),
        'total_pages': value['totalPages'],
        'total_results': value['totalResults'],
    };
}

