/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountFavoriteTv200ResponseResultsInner } from './AccountFavoriteTv200ResponseResultsInner';
import {
    AccountFavoriteTv200ResponseResultsInnerFromJSON,
    AccountFavoriteTv200ResponseResultsInnerFromJSONTyped,
    AccountFavoriteTv200ResponseResultsInnerToJSON,
    AccountFavoriteTv200ResponseResultsInnerToJSONTyped,
} from './AccountFavoriteTv200ResponseResultsInner';

/**
 * 
 * @export
 * @interface AccountFavoriteTv200Response
 */
export interface AccountFavoriteTv200Response {
    /**
     * 
     * @type {number}
     * @memberof AccountFavoriteTv200Response
     */
    page?: number;
    /**
     * 
     * @type {Array<AccountFavoriteTv200ResponseResultsInner>}
     * @memberof AccountFavoriteTv200Response
     */
    results?: Array<AccountFavoriteTv200ResponseResultsInner>;
    /**
     * 
     * @type {number}
     * @memberof AccountFavoriteTv200Response
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof AccountFavoriteTv200Response
     */
    totalResults?: number;
}

/**
 * Check if a given object implements the AccountFavoriteTv200Response interface.
 */
export function instanceOfAccountFavoriteTv200Response(value: object): value is AccountFavoriteTv200Response {
    return true;
}

export function AccountFavoriteTv200ResponseFromJSON(json: any): AccountFavoriteTv200Response {
    return AccountFavoriteTv200ResponseFromJSONTyped(json, false);
}

export function AccountFavoriteTv200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountFavoriteTv200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'] == null ? undefined : json['page'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(AccountFavoriteTv200ResponseResultsInnerFromJSON)),
        'totalPages': json['total_pages'] == null ? undefined : json['total_pages'],
        'totalResults': json['total_results'] == null ? undefined : json['total_results'],
    };
}

export function AccountFavoriteTv200ResponseToJSON(json: any): AccountFavoriteTv200Response {
    return AccountFavoriteTv200ResponseToJSONTyped(json, false);
}

export function AccountFavoriteTv200ResponseToJSONTyped(value?: AccountFavoriteTv200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(AccountFavoriteTv200ResponseResultsInnerToJSON)),
        'total_pages': value['totalPages'],
        'total_results': value['totalResults'],
    };
}

