/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticationCreateSession200Response
 */
export interface AuthenticationCreateSession200Response {
    /**
     * 
     * @type {boolean}
     * @memberof AuthenticationCreateSession200Response
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationCreateSession200Response
     */
    sessionId?: string;
}

/**
 * Check if a given object implements the AuthenticationCreateSession200Response interface.
 */
export function instanceOfAuthenticationCreateSession200Response(value: object): value is AuthenticationCreateSession200Response {
    return true;
}

export function AuthenticationCreateSession200ResponseFromJSON(json: any): AuthenticationCreateSession200Response {
    return AuthenticationCreateSession200ResponseFromJSONTyped(json, false);
}

export function AuthenticationCreateSession200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationCreateSession200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'sessionId': json['session_id'] == null ? undefined : json['session_id'],
    };
}

export function AuthenticationCreateSession200ResponseToJSON(json: any): AuthenticationCreateSession200Response {
    return AuthenticationCreateSession200ResponseToJSONTyped(json, false);
}

export function AuthenticationCreateSession200ResponseToJSONTyped(value?: AuthenticationCreateSession200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'session_id': value['sessionId'],
    };
}

