/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticationCreateRequestToken200Response
 */
export interface AuthenticationCreateRequestToken200Response {
    /**
     * 
     * @type {boolean}
     * @memberof AuthenticationCreateRequestToken200Response
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationCreateRequestToken200Response
     */
    expiresAt?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationCreateRequestToken200Response
     */
    requestToken?: string;
}

/**
 * Check if a given object implements the AuthenticationCreateRequestToken200Response interface.
 */
export function instanceOfAuthenticationCreateRequestToken200Response(value: object): value is AuthenticationCreateRequestToken200Response {
    return true;
}

export function AuthenticationCreateRequestToken200ResponseFromJSON(json: any): AuthenticationCreateRequestToken200Response {
    return AuthenticationCreateRequestToken200ResponseFromJSONTyped(json, false);
}

export function AuthenticationCreateRequestToken200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationCreateRequestToken200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'expiresAt': json['expires_at'] == null ? undefined : json['expires_at'],
        'requestToken': json['request_token'] == null ? undefined : json['request_token'],
    };
}

export function AuthenticationCreateRequestToken200ResponseToJSON(json: any): AuthenticationCreateRequestToken200Response {
    return AuthenticationCreateRequestToken200ResponseToJSONTyped(json, false);
}

export function AuthenticationCreateRequestToken200ResponseToJSONTyped(value?: AuthenticationCreateRequestToken200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'expires_at': value['expiresAt'],
        'request_token': value['requestToken'],
    };
}

