/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticationValidateKey200Response
 */
export interface AuthenticationValidateKey200Response {
    /**
     * 
     * @type {boolean}
     * @memberof AuthenticationValidateKey200Response
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof AuthenticationValidateKey200Response
     */
    statusCode?: number;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationValidateKey200Response
     */
    statusMessage?: string;
}

/**
 * Check if a given object implements the AuthenticationValidateKey200Response interface.
 */
export function instanceOfAuthenticationValidateKey200Response(value: object): value is AuthenticationValidateKey200Response {
    return true;
}

export function AuthenticationValidateKey200ResponseFromJSON(json: any): AuthenticationValidateKey200Response {
    return AuthenticationValidateKey200ResponseFromJSONTyped(json, false);
}

export function AuthenticationValidateKey200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationValidateKey200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'statusCode': json['status_code'] == null ? undefined : json['status_code'],
        'statusMessage': json['status_message'] == null ? undefined : json['status_message'],
    };
}

export function AuthenticationValidateKey200ResponseToJSON(json: any): AuthenticationValidateKey200Response {
    return AuthenticationValidateKey200ResponseToJSONTyped(json, false);
}

export function AuthenticationValidateKey200ResponseToJSONTyped(value?: AuthenticationValidateKey200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'status_code': value['statusCode'],
        'status_message': value['statusMessage'],
    };
}

