/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CertificationMovieList200ResponseCertifications } from './CertificationMovieList200ResponseCertifications';
import {
    CertificationMovieList200ResponseCertificationsFromJSON,
    CertificationMovieList200ResponseCertificationsFromJSONTyped,
    CertificationMovieList200ResponseCertificationsToJSON,
    CertificationMovieList200ResponseCertificationsToJSONTyped,
} from './CertificationMovieList200ResponseCertifications';

/**
 * 
 * @export
 * @interface CertificationMovieList200Response
 */
export interface CertificationMovieList200Response {
    /**
     * 
     * @type {CertificationMovieList200ResponseCertifications}
     * @memberof CertificationMovieList200Response
     */
    certifications?: CertificationMovieList200ResponseCertifications;
}

/**
 * Check if a given object implements the CertificationMovieList200Response interface.
 */
export function instanceOfCertificationMovieList200Response(value: object): value is CertificationMovieList200Response {
    return true;
}

export function CertificationMovieList200ResponseFromJSON(json: any): CertificationMovieList200Response {
    return CertificationMovieList200ResponseFromJSONTyped(json, false);
}

export function CertificationMovieList200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CertificationMovieList200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'certifications': json['certifications'] == null ? undefined : CertificationMovieList200ResponseCertificationsFromJSON(json['certifications']),
    };
}

export function CertificationMovieList200ResponseToJSON(json: any): CertificationMovieList200Response {
    return CertificationMovieList200ResponseToJSONTyped(json, false);
}

export function CertificationMovieList200ResponseToJSONTyped(value?: CertificationMovieList200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'certifications': CertificationMovieList200ResponseCertificationsToJSON(value['certifications']),
    };
}

