/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CertificationsTvList200ResponseCertificationsTHInner
 */
export interface CertificationsTvList200ResponseCertificationsTHInner {
    /**
     * 
     * @type {string}
     * @memberof CertificationsTvList200ResponseCertificationsTHInner
     */
    certification?: string;
    /**
     * 
     * @type {string}
     * @memberof CertificationsTvList200ResponseCertificationsTHInner
     */
    meaning?: string;
    /**
     * 
     * @type {number}
     * @memberof CertificationsTvList200ResponseCertificationsTHInner
     */
    order?: number;
}

/**
 * Check if a given object implements the CertificationsTvList200ResponseCertificationsTHInner interface.
 */
export function instanceOfCertificationsTvList200ResponseCertificationsTHInner(value: object): value is CertificationsTvList200ResponseCertificationsTHInner {
    return true;
}

export function CertificationsTvList200ResponseCertificationsTHInnerFromJSON(json: any): CertificationsTvList200ResponseCertificationsTHInner {
    return CertificationsTvList200ResponseCertificationsTHInnerFromJSONTyped(json, false);
}

export function CertificationsTvList200ResponseCertificationsTHInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CertificationsTvList200ResponseCertificationsTHInner {
    if (json == null) {
        return json;
    }
    return {
        
        'certification': json['certification'] == null ? undefined : json['certification'],
        'meaning': json['meaning'] == null ? undefined : json['meaning'],
        'order': json['order'] == null ? undefined : json['order'],
    };
}

export function CertificationsTvList200ResponseCertificationsTHInnerToJSON(json: any): CertificationsTvList200ResponseCertificationsTHInner {
    return CertificationsTvList200ResponseCertificationsTHInnerToJSONTyped(json, false);
}

export function CertificationsTvList200ResponseCertificationsTHInnerToJSONTyped(value?: CertificationsTvList200ResponseCertificationsTHInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'certification': value['certification'],
        'meaning': value['meaning'],
        'order': value['order'],
    };
}

