/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CertificationMovieList200ResponseCertificationsCHInner
 */
export interface CertificationMovieList200ResponseCertificationsCHInner {
    /**
     * 
     * @type {string}
     * @memberof CertificationMovieList200ResponseCertificationsCHInner
     */
    certification?: string;
    /**
     * 
     * @type {string}
     * @memberof CertificationMovieList200ResponseCertificationsCHInner
     */
    meaning?: string;
    /**
     * 
     * @type {number}
     * @memberof CertificationMovieList200ResponseCertificationsCHInner
     */
    order?: number;
}

/**
 * Check if a given object implements the CertificationMovieList200ResponseCertificationsCHInner interface.
 */
export function instanceOfCertificationMovieList200ResponseCertificationsCHInner(value: object): value is CertificationMovieList200ResponseCertificationsCHInner {
    return true;
}

export function CertificationMovieList200ResponseCertificationsCHInnerFromJSON(json: any): CertificationMovieList200ResponseCertificationsCHInner {
    return CertificationMovieList200ResponseCertificationsCHInnerFromJSONTyped(json, false);
}

export function CertificationMovieList200ResponseCertificationsCHInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CertificationMovieList200ResponseCertificationsCHInner {
    if (json == null) {
        return json;
    }
    return {
        
        'certification': json['certification'] == null ? undefined : json['certification'],
        'meaning': json['meaning'] == null ? undefined : json['meaning'],
        'order': json['order'] == null ? undefined : json['order'],
    };
}

export function CertificationMovieList200ResponseCertificationsCHInnerToJSON(json: any): CertificationMovieList200ResponseCertificationsCHInner {
    return CertificationMovieList200ResponseCertificationsCHInnerToJSONTyped(json, false);
}

export function CertificationMovieList200ResponseCertificationsCHInnerToJSONTyped(value?: CertificationMovieList200ResponseCertificationsCHInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'certification': value['certification'],
        'meaning': value['meaning'],
        'order': value['order'],
    };
}

