/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CertificationsTvList200ResponseCertificationsZAInner
 */
export interface CertificationsTvList200ResponseCertificationsZAInner {
    /**
     * 
     * @type {string}
     * @memberof CertificationsTvList200ResponseCertificationsZAInner
     */
    certification?: string;
    /**
     * 
     * @type {string}
     * @memberof CertificationsTvList200ResponseCertificationsZAInner
     */
    meaning?: string;
    /**
     * 
     * @type {number}
     * @memberof CertificationsTvList200ResponseCertificationsZAInner
     */
    order?: number;
}

/**
 * Check if a given object implements the CertificationsTvList200ResponseCertificationsZAInner interface.
 */
export function instanceOfCertificationsTvList200ResponseCertificationsZAInner(value: object): value is CertificationsTvList200ResponseCertificationsZAInner {
    return true;
}

export function CertificationsTvList200ResponseCertificationsZAInnerFromJSON(json: any): CertificationsTvList200ResponseCertificationsZAInner {
    return CertificationsTvList200ResponseCertificationsZAInnerFromJSONTyped(json, false);
}

export function CertificationsTvList200ResponseCertificationsZAInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CertificationsTvList200ResponseCertificationsZAInner {
    if (json == null) {
        return json;
    }
    return {
        
        'certification': json['certification'] == null ? undefined : json['certification'],
        'meaning': json['meaning'] == null ? undefined : json['meaning'],
        'order': json['order'] == null ? undefined : json['order'],
    };
}

export function CertificationsTvList200ResponseCertificationsZAInnerToJSON(json: any): CertificationsTvList200ResponseCertificationsZAInner {
    return CertificationsTvList200ResponseCertificationsZAInnerToJSONTyped(json, false);
}

export function CertificationsTvList200ResponseCertificationsZAInnerToJSONTyped(value?: CertificationsTvList200ResponseCertificationsZAInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'certification': value['certification'],
        'meaning': value['meaning'],
        'order': value['order'],
    };
}

