/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CollectionTranslations200ResponseTranslationsInnerData
 */
export interface CollectionTranslations200ResponseTranslationsInnerData {
    /**
     * 
     * @type {string}
     * @memberof CollectionTranslations200ResponseTranslationsInnerData
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionTranslations200ResponseTranslationsInnerData
     */
    overview?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionTranslations200ResponseTranslationsInnerData
     */
    homepage?: string;
}

/**
 * Check if a given object implements the CollectionTranslations200ResponseTranslationsInnerData interface.
 */
export function instanceOfCollectionTranslations200ResponseTranslationsInnerData(value: object): value is CollectionTranslations200ResponseTranslationsInnerData {
    return true;
}

export function CollectionTranslations200ResponseTranslationsInnerDataFromJSON(json: any): CollectionTranslations200ResponseTranslationsInnerData {
    return CollectionTranslations200ResponseTranslationsInnerDataFromJSONTyped(json, false);
}

export function CollectionTranslations200ResponseTranslationsInnerDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionTranslations200ResponseTranslationsInnerData {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'overview': json['overview'] == null ? undefined : json['overview'],
        'homepage': json['homepage'] == null ? undefined : json['homepage'],
    };
}

export function CollectionTranslations200ResponseTranslationsInnerDataToJSON(json: any): CollectionTranslations200ResponseTranslationsInnerData {
    return CollectionTranslations200ResponseTranslationsInnerDataToJSONTyped(json, false);
}

export function CollectionTranslations200ResponseTranslationsInnerDataToJSONTyped(value?: CollectionTranslations200ResponseTranslationsInnerData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'overview': value['overview'],
        'homepage': value['homepage'],
    };
}

