/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreditDetails200ResponsePerson } from './CreditDetails200ResponsePerson';
import {
    CreditDetails200ResponsePersonFromJSON,
    CreditDetails200ResponsePersonFromJSONTyped,
    CreditDetails200ResponsePersonToJSON,
    CreditDetails200ResponsePersonToJSONTyped,
} from './CreditDetails200ResponsePerson';
import type { CreditDetails200ResponseMedia } from './CreditDetails200ResponseMedia';
import {
    CreditDetails200ResponseMediaFromJSON,
    CreditDetails200ResponseMediaFromJSONTyped,
    CreditDetails200ResponseMediaToJSON,
    CreditDetails200ResponseMediaToJSONTyped,
} from './CreditDetails200ResponseMedia';

/**
 * 
 * @export
 * @interface CreditDetails200Response
 */
export interface CreditDetails200Response {
    /**
     * 
     * @type {string}
     * @memberof CreditDetails200Response
     */
    creditType?: string;
    /**
     * 
     * @type {string}
     * @memberof CreditDetails200Response
     */
    department?: string;
    /**
     * 
     * @type {string}
     * @memberof CreditDetails200Response
     */
    job?: string;
    /**
     * 
     * @type {CreditDetails200ResponseMedia}
     * @memberof CreditDetails200Response
     */
    media?: CreditDetails200ResponseMedia;
    /**
     * 
     * @type {string}
     * @memberof CreditDetails200Response
     */
    mediaType?: string;
    /**
     * 
     * @type {string}
     * @memberof CreditDetails200Response
     */
    id?: string;
    /**
     * 
     * @type {CreditDetails200ResponsePerson}
     * @memberof CreditDetails200Response
     */
    person?: CreditDetails200ResponsePerson;
}

/**
 * Check if a given object implements the CreditDetails200Response interface.
 */
export function instanceOfCreditDetails200Response(value: object): value is CreditDetails200Response {
    return true;
}

export function CreditDetails200ResponseFromJSON(json: any): CreditDetails200Response {
    return CreditDetails200ResponseFromJSONTyped(json, false);
}

export function CreditDetails200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreditDetails200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'creditType': json['credit_type'] == null ? undefined : json['credit_type'],
        'department': json['department'] == null ? undefined : json['department'],
        'job': json['job'] == null ? undefined : json['job'],
        'media': json['media'] == null ? undefined : CreditDetails200ResponseMediaFromJSON(json['media']),
        'mediaType': json['media_type'] == null ? undefined : json['media_type'],
        'id': json['id'] == null ? undefined : json['id'],
        'person': json['person'] == null ? undefined : CreditDetails200ResponsePersonFromJSON(json['person']),
    };
}

export function CreditDetails200ResponseToJSON(json: any): CreditDetails200Response {
    return CreditDetails200ResponseToJSONTyped(json, false);
}

export function CreditDetails200ResponseToJSONTyped(value?: CreditDetails200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'credit_type': value['creditType'],
        'department': value['department'],
        'job': value['job'],
        'media': CreditDetails200ResponseMediaToJSON(value['media']),
        'media_type': value['mediaType'],
        'id': value['id'],
        'person': CreditDetails200ResponsePersonToJSON(value['person']),
    };
}

