/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FindById200ResponseMovieResultsInner
 */
export interface FindById200ResponseMovieResultsInner {
    /**
     * 
     * @type {boolean}
     * @memberof FindById200ResponseMovieResultsInner
     */
    adult?: boolean;
    /**
     * 
     * @type {string}
     * @memberof FindById200ResponseMovieResultsInner
     */
    backdropPath?: string;
    /**
     * 
     * @type {number}
     * @memberof FindById200ResponseMovieResultsInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof FindById200ResponseMovieResultsInner
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof FindById200ResponseMovieResultsInner
     */
    originalLanguage?: string;
    /**
     * 
     * @type {string}
     * @memberof FindById200ResponseMovieResultsInner
     */
    originalTitle?: string;
    /**
     * 
     * @type {string}
     * @memberof FindById200ResponseMovieResultsInner
     */
    overview?: string;
    /**
     * 
     * @type {string}
     * @memberof FindById200ResponseMovieResultsInner
     */
    posterPath?: string;
    /**
     * 
     * @type {string}
     * @memberof FindById200ResponseMovieResultsInner
     */
    mediaType?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof FindById200ResponseMovieResultsInner
     */
    genreIds?: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof FindById200ResponseMovieResultsInner
     */
    popularity?: number;
    /**
     * 
     * @type {string}
     * @memberof FindById200ResponseMovieResultsInner
     */
    releaseDate?: string;
    /**
     * 
     * @type {boolean}
     * @memberof FindById200ResponseMovieResultsInner
     */
    video?: boolean;
    /**
     * 
     * @type {number}
     * @memberof FindById200ResponseMovieResultsInner
     */
    voteAverage?: number;
    /**
     * 
     * @type {number}
     * @memberof FindById200ResponseMovieResultsInner
     */
    voteCount?: number;
}

/**
 * Check if a given object implements the FindById200ResponseMovieResultsInner interface.
 */
export function instanceOfFindById200ResponseMovieResultsInner(value: object): value is FindById200ResponseMovieResultsInner {
    return true;
}

export function FindById200ResponseMovieResultsInnerFromJSON(json: any): FindById200ResponseMovieResultsInner {
    return FindById200ResponseMovieResultsInnerFromJSONTyped(json, false);
}

export function FindById200ResponseMovieResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindById200ResponseMovieResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'adult': json['adult'] == null ? undefined : json['adult'],
        'backdropPath': json['backdrop_path'] == null ? undefined : json['backdrop_path'],
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'originalLanguage': json['original_language'] == null ? undefined : json['original_language'],
        'originalTitle': json['original_title'] == null ? undefined : json['original_title'],
        'overview': json['overview'] == null ? undefined : json['overview'],
        'posterPath': json['poster_path'] == null ? undefined : json['poster_path'],
        'mediaType': json['media_type'] == null ? undefined : json['media_type'],
        'genreIds': json['genre_ids'] == null ? undefined : json['genre_ids'],
        'popularity': json['popularity'] == null ? undefined : json['popularity'],
        'releaseDate': json['release_date'] == null ? undefined : json['release_date'],
        'video': json['video'] == null ? undefined : json['video'],
        'voteAverage': json['vote_average'] == null ? undefined : json['vote_average'],
        'voteCount': json['vote_count'] == null ? undefined : json['vote_count'],
    };
}

export function FindById200ResponseMovieResultsInnerToJSON(json: any): FindById200ResponseMovieResultsInner {
    return FindById200ResponseMovieResultsInnerToJSONTyped(json, false);
}

export function FindById200ResponseMovieResultsInnerToJSONTyped(value?: FindById200ResponseMovieResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'adult': value['adult'],
        'backdrop_path': value['backdropPath'],
        'id': value['id'],
        'title': value['title'],
        'original_language': value['originalLanguage'],
        'original_title': value['originalTitle'],
        'overview': value['overview'],
        'poster_path': value['posterPath'],
        'media_type': value['mediaType'],
        'genre_ids': value['genreIds'],
        'popularity': value['popularity'],
        'release_date': value['releaseDate'],
        'video': value['video'],
        'vote_average': value['voteAverage'],
        'vote_count': value['voteCount'],
    };
}

