/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenreTvList200ResponseGenresInner
 */
export interface GenreTvList200ResponseGenresInner {
    /**
     * 
     * @type {number}
     * @memberof GenreTvList200ResponseGenresInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof GenreTvList200ResponseGenresInner
     */
    name?: string;
}

/**
 * Check if a given object implements the GenreTvList200ResponseGenresInner interface.
 */
export function instanceOfGenreTvList200ResponseGenresInner(value: object): value is GenreTvList200ResponseGenresInner {
    return true;
}

export function GenreTvList200ResponseGenresInnerFromJSON(json: any): GenreTvList200ResponseGenresInner {
    return GenreTvList200ResponseGenresInnerFromJSONTyped(json, false);
}

export function GenreTvList200ResponseGenresInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenreTvList200ResponseGenresInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function GenreTvList200ResponseGenresInnerToJSON(json: any): GenreTvList200ResponseGenresInner {
    return GenreTvList200ResponseGenresInnerToJSONTyped(json, false);
}

export function GenreTvList200ResponseGenresInnerToJSONTyped(value?: GenreTvList200ResponseGenresInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

