/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListCreate200Response
 */
export interface ListCreate200Response {
    /**
     * 
     * @type {string}
     * @memberof ListCreate200Response
     */
    statusMessage?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ListCreate200Response
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ListCreate200Response
     */
    statusCode?: number;
    /**
     * 
     * @type {number}
     * @memberof ListCreate200Response
     */
    listId?: number;
}

/**
 * Check if a given object implements the ListCreate200Response interface.
 */
export function instanceOfListCreate200Response(value: object): value is ListCreate200Response {
    return true;
}

export function ListCreate200ResponseFromJSON(json: any): ListCreate200Response {
    return ListCreate200ResponseFromJSONTyped(json, false);
}

export function ListCreate200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListCreate200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'statusMessage': json['status_message'] == null ? undefined : json['status_message'],
        'success': json['success'] == null ? undefined : json['success'],
        'statusCode': json['status_code'] == null ? undefined : json['status_code'],
        'listId': json['list_id'] == null ? undefined : json['list_id'],
    };
}

export function ListCreate200ResponseToJSON(json: any): ListCreate200Response {
    return ListCreate200ResponseToJSONTyped(json, false);
}

export function ListCreate200ResponseToJSONTyped(value?: ListCreate200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status_message': value['statusMessage'],
        'success': value['success'],
        'status_code': value['statusCode'],
        'list_id': value['listId'],
    };
}

