/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MovieWatchProviders200ResponseResultsAUFlatrateInner } from './MovieWatchProviders200ResponseResultsAUFlatrateInner';
import {
    MovieWatchProviders200ResponseResultsAUFlatrateInnerFromJSON,
    MovieWatchProviders200ResponseResultsAUFlatrateInnerFromJSONTyped,
    MovieWatchProviders200ResponseResultsAUFlatrateInnerToJSON,
    MovieWatchProviders200ResponseResultsAUFlatrateInnerToJSONTyped,
} from './MovieWatchProviders200ResponseResultsAUFlatrateInner';
import type { MovieWatchProviders200ResponseResultsALBuyInner } from './MovieWatchProviders200ResponseResultsALBuyInner';
import {
    MovieWatchProviders200ResponseResultsALBuyInnerFromJSON,
    MovieWatchProviders200ResponseResultsALBuyInnerFromJSONTyped,
    MovieWatchProviders200ResponseResultsALBuyInnerToJSON,
    MovieWatchProviders200ResponseResultsALBuyInnerToJSONTyped,
} from './MovieWatchProviders200ResponseResultsALBuyInner';

/**
 * 
 * @export
 * @interface MovieWatchProviders200ResponseResultsMT
 */
export interface MovieWatchProviders200ResponseResultsMT {
    /**
     * 
     * @type {string}
     * @memberof MovieWatchProviders200ResponseResultsMT
     */
    link?: string;
    /**
     * 
     * @type {Array<MovieWatchProviders200ResponseResultsAUFlatrateInner>}
     * @memberof MovieWatchProviders200ResponseResultsMT
     */
    flatrate?: Array<MovieWatchProviders200ResponseResultsAUFlatrateInner>;
    /**
     * 
     * @type {Array<MovieWatchProviders200ResponseResultsALBuyInner>}
     * @memberof MovieWatchProviders200ResponseResultsMT
     */
    buy?: Array<MovieWatchProviders200ResponseResultsALBuyInner>;
    /**
     * 
     * @type {Array<MovieWatchProviders200ResponseResultsALBuyInner>}
     * @memberof MovieWatchProviders200ResponseResultsMT
     */
    rent?: Array<MovieWatchProviders200ResponseResultsALBuyInner>;
}

/**
 * Check if a given object implements the MovieWatchProviders200ResponseResultsMT interface.
 */
export function instanceOfMovieWatchProviders200ResponseResultsMT(value: object): value is MovieWatchProviders200ResponseResultsMT {
    return true;
}

export function MovieWatchProviders200ResponseResultsMTFromJSON(json: any): MovieWatchProviders200ResponseResultsMT {
    return MovieWatchProviders200ResponseResultsMTFromJSONTyped(json, false);
}

export function MovieWatchProviders200ResponseResultsMTFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieWatchProviders200ResponseResultsMT {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'] == null ? undefined : json['link'],
        'flatrate': json['flatrate'] == null ? undefined : ((json['flatrate'] as Array<any>).map(MovieWatchProviders200ResponseResultsAUFlatrateInnerFromJSON)),
        'buy': json['buy'] == null ? undefined : ((json['buy'] as Array<any>).map(MovieWatchProviders200ResponseResultsALBuyInnerFromJSON)),
        'rent': json['rent'] == null ? undefined : ((json['rent'] as Array<any>).map(MovieWatchProviders200ResponseResultsALBuyInnerFromJSON)),
    };
}

export function MovieWatchProviders200ResponseResultsMTToJSON(json: any): MovieWatchProviders200ResponseResultsMT {
    return MovieWatchProviders200ResponseResultsMTToJSONTyped(json, false);
}

export function MovieWatchProviders200ResponseResultsMTToJSONTyped(value?: MovieWatchProviders200ResponseResultsMT | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
        'flatrate': value['flatrate'] == null ? undefined : ((value['flatrate'] as Array<any>).map(MovieWatchProviders200ResponseResultsAUFlatrateInnerToJSON)),
        'buy': value['buy'] == null ? undefined : ((value['buy'] as Array<any>).map(MovieWatchProviders200ResponseResultsALBuyInnerToJSON)),
        'rent': value['rent'] == null ? undefined : ((value['rent'] as Array<any>).map(MovieWatchProviders200ResponseResultsALBuyInnerToJSON)),
    };
}

