/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MovieAddRatingRequest
 */
export interface MovieAddRatingRequest {
    /**
     * 
     * @type {string}
     * @memberof MovieAddRatingRequest
     */
    rAWBODY: string;
}

/**
 * Check if a given object implements the MovieAddRatingRequest interface.
 */
export function instanceOfMovieAddRatingRequest(value: object): value is MovieAddRatingRequest {
    if (!('rAWBODY' in value) || value['rAWBODY'] === undefined) return false;
    return true;
}

export function MovieAddRatingRequestFromJSON(json: any): MovieAddRatingRequest {
    return MovieAddRatingRequestFromJSONTyped(json, false);
}

export function MovieAddRatingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieAddRatingRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'rAWBODY': json['RAW_BODY'],
    };
}

export function MovieAddRatingRequestToJSON(json: any): MovieAddRatingRequest {
    return MovieAddRatingRequestToJSONTyped(json, false);
}

export function MovieAddRatingRequestToJSONTyped(value?: MovieAddRatingRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'RAW_BODY': value['rAWBODY'],
    };
}

