/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MovieWatchProviders200ResponseResultsDKRentInner } from './MovieWatchProviders200ResponseResultsDKRentInner';
import {
    MovieWatchProviders200ResponseResultsDKRentInnerFromJSON,
    MovieWatchProviders200ResponseResultsDKRentInnerFromJSONTyped,
    MovieWatchProviders200ResponseResultsDKRentInnerToJSON,
    MovieWatchProviders200ResponseResultsDKRentInnerToJSONTyped,
} from './MovieWatchProviders200ResponseResultsDKRentInner';
import type { MovieWatchProviders200ResponseResultsBEFlatrateInner } from './MovieWatchProviders200ResponseResultsBEFlatrateInner';
import {
    MovieWatchProviders200ResponseResultsBEFlatrateInnerFromJSON,
    MovieWatchProviders200ResponseResultsBEFlatrateInnerFromJSONTyped,
    MovieWatchProviders200ResponseResultsBEFlatrateInnerToJSON,
    MovieWatchProviders200ResponseResultsBEFlatrateInnerToJSONTyped,
} from './MovieWatchProviders200ResponseResultsBEFlatrateInner';

/**
 * 
 * @export
 * @interface MovieWatchProviders200ResponseResultsDK
 */
export interface MovieWatchProviders200ResponseResultsDK {
    /**
     * 
     * @type {string}
     * @memberof MovieWatchProviders200ResponseResultsDK
     */
    link?: string;
    /**
     * 
     * @type {Array<MovieWatchProviders200ResponseResultsDKRentInner>}
     * @memberof MovieWatchProviders200ResponseResultsDK
     */
    rent?: Array<MovieWatchProviders200ResponseResultsDKRentInner>;
    /**
     * 
     * @type {Array<MovieWatchProviders200ResponseResultsBEFlatrateInner>}
     * @memberof MovieWatchProviders200ResponseResultsDK
     */
    flatrate?: Array<MovieWatchProviders200ResponseResultsBEFlatrateInner>;
    /**
     * 
     * @type {Array<MovieWatchProviders200ResponseResultsDKRentInner>}
     * @memberof MovieWatchProviders200ResponseResultsDK
     */
    buy?: Array<MovieWatchProviders200ResponseResultsDKRentInner>;
}

/**
 * Check if a given object implements the MovieWatchProviders200ResponseResultsDK interface.
 */
export function instanceOfMovieWatchProviders200ResponseResultsDK(value: object): value is MovieWatchProviders200ResponseResultsDK {
    return true;
}

export function MovieWatchProviders200ResponseResultsDKFromJSON(json: any): MovieWatchProviders200ResponseResultsDK {
    return MovieWatchProviders200ResponseResultsDKFromJSONTyped(json, false);
}

export function MovieWatchProviders200ResponseResultsDKFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieWatchProviders200ResponseResultsDK {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'] == null ? undefined : json['link'],
        'rent': json['rent'] == null ? undefined : ((json['rent'] as Array<any>).map(MovieWatchProviders200ResponseResultsDKRentInnerFromJSON)),
        'flatrate': json['flatrate'] == null ? undefined : ((json['flatrate'] as Array<any>).map(MovieWatchProviders200ResponseResultsBEFlatrateInnerFromJSON)),
        'buy': json['buy'] == null ? undefined : ((json['buy'] as Array<any>).map(MovieWatchProviders200ResponseResultsDKRentInnerFromJSON)),
    };
}

export function MovieWatchProviders200ResponseResultsDKToJSON(json: any): MovieWatchProviders200ResponseResultsDK {
    return MovieWatchProviders200ResponseResultsDKToJSONTyped(json, false);
}

export function MovieWatchProviders200ResponseResultsDKToJSONTyped(value?: MovieWatchProviders200ResponseResultsDK | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
        'rent': value['rent'] == null ? undefined : ((value['rent'] as Array<any>).map(MovieWatchProviders200ResponseResultsDKRentInnerToJSON)),
        'flatrate': value['flatrate'] == null ? undefined : ((value['flatrate'] as Array<any>).map(MovieWatchProviders200ResponseResultsBEFlatrateInnerToJSON)),
        'buy': value['buy'] == null ? undefined : ((value['buy'] as Array<any>).map(MovieWatchProviders200ResponseResultsDKRentInnerToJSON)),
    };
}

