/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MovieWatchProviders200ResponseResultsCHBuyInner } from './MovieWatchProviders200ResponseResultsCHBuyInner';
import {
    MovieWatchProviders200ResponseResultsCHBuyInnerFromJSON,
    MovieWatchProviders200ResponseResultsCHBuyInnerFromJSONTyped,
    MovieWatchProviders200ResponseResultsCHBuyInnerToJSON,
    MovieWatchProviders200ResponseResultsCHBuyInnerToJSONTyped,
} from './MovieWatchProviders200ResponseResultsCHBuyInner';
import type { MovieWatchProviders200ResponseResultsAUFlatrateInner } from './MovieWatchProviders200ResponseResultsAUFlatrateInner';
import {
    MovieWatchProviders200ResponseResultsAUFlatrateInnerFromJSON,
    MovieWatchProviders200ResponseResultsAUFlatrateInnerFromJSONTyped,
    MovieWatchProviders200ResponseResultsAUFlatrateInnerToJSON,
    MovieWatchProviders200ResponseResultsAUFlatrateInnerToJSONTyped,
} from './MovieWatchProviders200ResponseResultsAUFlatrateInner';

/**
 * 
 * @export
 * @interface MovieWatchProviders200ResponseResultsCH
 */
export interface MovieWatchProviders200ResponseResultsCH {
    /**
     * 
     * @type {string}
     * @memberof MovieWatchProviders200ResponseResultsCH
     */
    link?: string;
    /**
     * 
     * @type {Array<MovieWatchProviders200ResponseResultsAUFlatrateInner>}
     * @memberof MovieWatchProviders200ResponseResultsCH
     */
    flatrate?: Array<MovieWatchProviders200ResponseResultsAUFlatrateInner>;
    /**
     * 
     * @type {Array<MovieWatchProviders200ResponseResultsCHBuyInner>}
     * @memberof MovieWatchProviders200ResponseResultsCH
     */
    buy?: Array<MovieWatchProviders200ResponseResultsCHBuyInner>;
    /**
     * 
     * @type {Array<MovieWatchProviders200ResponseResultsCHBuyInner>}
     * @memberof MovieWatchProviders200ResponseResultsCH
     */
    rent?: Array<MovieWatchProviders200ResponseResultsCHBuyInner>;
}

/**
 * Check if a given object implements the MovieWatchProviders200ResponseResultsCH interface.
 */
export function instanceOfMovieWatchProviders200ResponseResultsCH(value: object): value is MovieWatchProviders200ResponseResultsCH {
    return true;
}

export function MovieWatchProviders200ResponseResultsCHFromJSON(json: any): MovieWatchProviders200ResponseResultsCH {
    return MovieWatchProviders200ResponseResultsCHFromJSONTyped(json, false);
}

export function MovieWatchProviders200ResponseResultsCHFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieWatchProviders200ResponseResultsCH {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'] == null ? undefined : json['link'],
        'flatrate': json['flatrate'] == null ? undefined : ((json['flatrate'] as Array<any>).map(MovieWatchProviders200ResponseResultsAUFlatrateInnerFromJSON)),
        'buy': json['buy'] == null ? undefined : ((json['buy'] as Array<any>).map(MovieWatchProviders200ResponseResultsCHBuyInnerFromJSON)),
        'rent': json['rent'] == null ? undefined : ((json['rent'] as Array<any>).map(MovieWatchProviders200ResponseResultsCHBuyInnerFromJSON)),
    };
}

export function MovieWatchProviders200ResponseResultsCHToJSON(json: any): MovieWatchProviders200ResponseResultsCH {
    return MovieWatchProviders200ResponseResultsCHToJSONTyped(json, false);
}

export function MovieWatchProviders200ResponseResultsCHToJSONTyped(value?: MovieWatchProviders200ResponseResultsCH | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
        'flatrate': value['flatrate'] == null ? undefined : ((value['flatrate'] as Array<any>).map(MovieWatchProviders200ResponseResultsAUFlatrateInnerToJSON)),
        'buy': value['buy'] == null ? undefined : ((value['buy'] as Array<any>).map(MovieWatchProviders200ResponseResultsCHBuyInnerToJSON)),
        'rent': value['rent'] == null ? undefined : ((value['rent'] as Array<any>).map(MovieWatchProviders200ResponseResultsCHBuyInnerToJSON)),
    };
}

