/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MovieWatchProviders200ResponseResultsBERentInner } from './MovieWatchProviders200ResponseResultsBERentInner';
import {
    MovieWatchProviders200ResponseResultsBERentInnerFromJSON,
    MovieWatchProviders200ResponseResultsBERentInnerFromJSONTyped,
    MovieWatchProviders200ResponseResultsBERentInnerToJSON,
    MovieWatchProviders200ResponseResultsBERentInnerToJSONTyped,
} from './MovieWatchProviders200ResponseResultsBERentInner';
import type { MovieWatchProviders200ResponseResultsCARentInner } from './MovieWatchProviders200ResponseResultsCARentInner';
import {
    MovieWatchProviders200ResponseResultsCARentInnerFromJSON,
    MovieWatchProviders200ResponseResultsCARentInnerFromJSONTyped,
    MovieWatchProviders200ResponseResultsCARentInnerToJSON,
    MovieWatchProviders200ResponseResultsCARentInnerToJSONTyped,
} from './MovieWatchProviders200ResponseResultsCARentInner';
import type { MovieWatchProviders200ResponseResultsCAFlatrateInner } from './MovieWatchProviders200ResponseResultsCAFlatrateInner';
import {
    MovieWatchProviders200ResponseResultsCAFlatrateInnerFromJSON,
    MovieWatchProviders200ResponseResultsCAFlatrateInnerFromJSONTyped,
    MovieWatchProviders200ResponseResultsCAFlatrateInnerToJSON,
    MovieWatchProviders200ResponseResultsCAFlatrateInnerToJSONTyped,
} from './MovieWatchProviders200ResponseResultsCAFlatrateInner';

/**
 * 
 * @export
 * @interface MovieWatchProviders200ResponseResultsCA
 */
export interface MovieWatchProviders200ResponseResultsCA {
    /**
     * 
     * @type {string}
     * @memberof MovieWatchProviders200ResponseResultsCA
     */
    link?: string;
    /**
     * 
     * @type {Array<MovieWatchProviders200ResponseResultsCARentInner>}
     * @memberof MovieWatchProviders200ResponseResultsCA
     */
    rent?: Array<MovieWatchProviders200ResponseResultsCARentInner>;
    /**
     * 
     * @type {Array<MovieWatchProviders200ResponseResultsBERentInner>}
     * @memberof MovieWatchProviders200ResponseResultsCA
     */
    buy?: Array<MovieWatchProviders200ResponseResultsBERentInner>;
    /**
     * 
     * @type {Array<MovieWatchProviders200ResponseResultsCAFlatrateInner>}
     * @memberof MovieWatchProviders200ResponseResultsCA
     */
    flatrate?: Array<MovieWatchProviders200ResponseResultsCAFlatrateInner>;
}

/**
 * Check if a given object implements the MovieWatchProviders200ResponseResultsCA interface.
 */
export function instanceOfMovieWatchProviders200ResponseResultsCA(value: object): value is MovieWatchProviders200ResponseResultsCA {
    return true;
}

export function MovieWatchProviders200ResponseResultsCAFromJSON(json: any): MovieWatchProviders200ResponseResultsCA {
    return MovieWatchProviders200ResponseResultsCAFromJSONTyped(json, false);
}

export function MovieWatchProviders200ResponseResultsCAFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieWatchProviders200ResponseResultsCA {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'] == null ? undefined : json['link'],
        'rent': json['rent'] == null ? undefined : ((json['rent'] as Array<any>).map(MovieWatchProviders200ResponseResultsCARentInnerFromJSON)),
        'buy': json['buy'] == null ? undefined : ((json['buy'] as Array<any>).map(MovieWatchProviders200ResponseResultsBERentInnerFromJSON)),
        'flatrate': json['flatrate'] == null ? undefined : ((json['flatrate'] as Array<any>).map(MovieWatchProviders200ResponseResultsCAFlatrateInnerFromJSON)),
    };
}

export function MovieWatchProviders200ResponseResultsCAToJSON(json: any): MovieWatchProviders200ResponseResultsCA {
    return MovieWatchProviders200ResponseResultsCAToJSONTyped(json, false);
}

export function MovieWatchProviders200ResponseResultsCAToJSONTyped(value?: MovieWatchProviders200ResponseResultsCA | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
        'rent': value['rent'] == null ? undefined : ((value['rent'] as Array<any>).map(MovieWatchProviders200ResponseResultsCARentInnerToJSON)),
        'buy': value['buy'] == null ? undefined : ((value['buy'] as Array<any>).map(MovieWatchProviders200ResponseResultsBERentInnerToJSON)),
        'flatrate': value['flatrate'] == null ? undefined : ((value['flatrate'] as Array<any>).map(MovieWatchProviders200ResponseResultsCAFlatrateInnerToJSON)),
    };
}

