/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MovieWatchProviders200ResponseResultsAUFlatrateInner } from './MovieWatchProviders200ResponseResultsAUFlatrateInner';
import {
    MovieWatchProviders200ResponseResultsAUFlatrateInnerFromJSON,
    MovieWatchProviders200ResponseResultsAUFlatrateInnerFromJSONTyped,
    MovieWatchProviders200ResponseResultsAUFlatrateInnerToJSON,
    MovieWatchProviders200ResponseResultsAUFlatrateInnerToJSONTyped,
} from './MovieWatchProviders200ResponseResultsAUFlatrateInner';

/**
 * 
 * @export
 * @interface MovieWatchProviders200ResponseResultsSG
 */
export interface MovieWatchProviders200ResponseResultsSG {
    /**
     * 
     * @type {string}
     * @memberof MovieWatchProviders200ResponseResultsSG
     */
    link?: string;
    /**
     * 
     * @type {Array<MovieWatchProviders200ResponseResultsAUFlatrateInner>}
     * @memberof MovieWatchProviders200ResponseResultsSG
     */
    flatrate?: Array<MovieWatchProviders200ResponseResultsAUFlatrateInner>;
}

/**
 * Check if a given object implements the MovieWatchProviders200ResponseResultsSG interface.
 */
export function instanceOfMovieWatchProviders200ResponseResultsSG(value: object): value is MovieWatchProviders200ResponseResultsSG {
    return true;
}

export function MovieWatchProviders200ResponseResultsSGFromJSON(json: any): MovieWatchProviders200ResponseResultsSG {
    return MovieWatchProviders200ResponseResultsSGFromJSONTyped(json, false);
}

export function MovieWatchProviders200ResponseResultsSGFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieWatchProviders200ResponseResultsSG {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'] == null ? undefined : json['link'],
        'flatrate': json['flatrate'] == null ? undefined : ((json['flatrate'] as Array<any>).map(MovieWatchProviders200ResponseResultsAUFlatrateInnerFromJSON)),
    };
}

export function MovieWatchProviders200ResponseResultsSGToJSON(json: any): MovieWatchProviders200ResponseResultsSG {
    return MovieWatchProviders200ResponseResultsSGToJSONTyped(json, false);
}

export function MovieWatchProviders200ResponseResultsSGToJSONTyped(value?: MovieWatchProviders200ResponseResultsSG | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
        'flatrate': value['flatrate'] == null ? undefined : ((value['flatrate'] as Array<any>).map(MovieWatchProviders200ResponseResultsAUFlatrateInnerToJSON)),
    };
}

