/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MovieWatchProviders200ResponseResultsBEFlatrateInner } from './MovieWatchProviders200ResponseResultsBEFlatrateInner';
import {
    MovieWatchProviders200ResponseResultsBEFlatrateInnerFromJSON,
    MovieWatchProviders200ResponseResultsBEFlatrateInnerFromJSONTyped,
    MovieWatchProviders200ResponseResultsBEFlatrateInnerToJSON,
    MovieWatchProviders200ResponseResultsBEFlatrateInnerToJSONTyped,
} from './MovieWatchProviders200ResponseResultsBEFlatrateInner';
import type { MovieWatchProviders200ResponseResultsSEBuyInner } from './MovieWatchProviders200ResponseResultsSEBuyInner';
import {
    MovieWatchProviders200ResponseResultsSEBuyInnerFromJSON,
    MovieWatchProviders200ResponseResultsSEBuyInnerFromJSONTyped,
    MovieWatchProviders200ResponseResultsSEBuyInnerToJSON,
    MovieWatchProviders200ResponseResultsSEBuyInnerToJSONTyped,
} from './MovieWatchProviders200ResponseResultsSEBuyInner';

/**
 * 
 * @export
 * @interface MovieWatchProviders200ResponseResultsSE
 */
export interface MovieWatchProviders200ResponseResultsSE {
    /**
     * 
     * @type {string}
     * @memberof MovieWatchProviders200ResponseResultsSE
     */
    link?: string;
    /**
     * 
     * @type {Array<MovieWatchProviders200ResponseResultsSEBuyInner>}
     * @memberof MovieWatchProviders200ResponseResultsSE
     */
    buy?: Array<MovieWatchProviders200ResponseResultsSEBuyInner>;
    /**
     * 
     * @type {Array<MovieWatchProviders200ResponseResultsSEBuyInner>}
     * @memberof MovieWatchProviders200ResponseResultsSE
     */
    rent?: Array<MovieWatchProviders200ResponseResultsSEBuyInner>;
    /**
     * 
     * @type {Array<MovieWatchProviders200ResponseResultsBEFlatrateInner>}
     * @memberof MovieWatchProviders200ResponseResultsSE
     */
    flatrate?: Array<MovieWatchProviders200ResponseResultsBEFlatrateInner>;
}

/**
 * Check if a given object implements the MovieWatchProviders200ResponseResultsSE interface.
 */
export function instanceOfMovieWatchProviders200ResponseResultsSE(value: object): value is MovieWatchProviders200ResponseResultsSE {
    return true;
}

export function MovieWatchProviders200ResponseResultsSEFromJSON(json: any): MovieWatchProviders200ResponseResultsSE {
    return MovieWatchProviders200ResponseResultsSEFromJSONTyped(json, false);
}

export function MovieWatchProviders200ResponseResultsSEFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieWatchProviders200ResponseResultsSE {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'] == null ? undefined : json['link'],
        'buy': json['buy'] == null ? undefined : ((json['buy'] as Array<any>).map(MovieWatchProviders200ResponseResultsSEBuyInnerFromJSON)),
        'rent': json['rent'] == null ? undefined : ((json['rent'] as Array<any>).map(MovieWatchProviders200ResponseResultsSEBuyInnerFromJSON)),
        'flatrate': json['flatrate'] == null ? undefined : ((json['flatrate'] as Array<any>).map(MovieWatchProviders200ResponseResultsBEFlatrateInnerFromJSON)),
    };
}

export function MovieWatchProviders200ResponseResultsSEToJSON(json: any): MovieWatchProviders200ResponseResultsSE {
    return MovieWatchProviders200ResponseResultsSEToJSONTyped(json, false);
}

export function MovieWatchProviders200ResponseResultsSEToJSONTyped(value?: MovieWatchProviders200ResponseResultsSE | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
        'buy': value['buy'] == null ? undefined : ((value['buy'] as Array<any>).map(MovieWatchProviders200ResponseResultsSEBuyInnerToJSON)),
        'rent': value['rent'] == null ? undefined : ((value['rent'] as Array<any>).map(MovieWatchProviders200ResponseResultsSEBuyInnerToJSON)),
        'flatrate': value['flatrate'] == null ? undefined : ((value['flatrate'] as Array<any>).map(MovieWatchProviders200ResponseResultsBEFlatrateInnerToJSON)),
    };
}

