/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MovieDetails200ResponseProductionCountriesInner
 */
export interface MovieDetails200ResponseProductionCountriesInner {
    /**
     * 
     * @type {string}
     * @memberof MovieDetails200ResponseProductionCountriesInner
     */
    iso31661?: string;
    /**
     * 
     * @type {string}
     * @memberof MovieDetails200ResponseProductionCountriesInner
     */
    name?: string;
}

/**
 * Check if a given object implements the MovieDetails200ResponseProductionCountriesInner interface.
 */
export function instanceOfMovieDetails200ResponseProductionCountriesInner(value: object): value is MovieDetails200ResponseProductionCountriesInner {
    return true;
}

export function MovieDetails200ResponseProductionCountriesInnerFromJSON(json: any): MovieDetails200ResponseProductionCountriesInner {
    return MovieDetails200ResponseProductionCountriesInnerFromJSONTyped(json, false);
}

export function MovieDetails200ResponseProductionCountriesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieDetails200ResponseProductionCountriesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'iso31661': json['iso_3166_1'] == null ? undefined : json['iso_3166_1'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function MovieDetails200ResponseProductionCountriesInnerToJSON(json: any): MovieDetails200ResponseProductionCountriesInner {
    return MovieDetails200ResponseProductionCountriesInnerToJSONTyped(json, false);
}

export function MovieDetails200ResponseProductionCountriesInnerToJSONTyped(value?: MovieDetails200ResponseProductionCountriesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'iso_3166_1': value['iso31661'],
        'name': value['name'],
    };
}

