/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MovieWatchProviders200ResponseResultsCLBuyInner } from './MovieWatchProviders200ResponseResultsCLBuyInner';
import {
    MovieWatchProviders200ResponseResultsCLBuyInnerFromJSON,
    MovieWatchProviders200ResponseResultsCLBuyInnerFromJSONTyped,
    MovieWatchProviders200ResponseResultsCLBuyInnerToJSON,
    MovieWatchProviders200ResponseResultsCLBuyInnerToJSONTyped,
} from './MovieWatchProviders200ResponseResultsCLBuyInner';
import type { MovieWatchProviders200ResponseResultsBEFlatrateInner } from './MovieWatchProviders200ResponseResultsBEFlatrateInner';
import {
    MovieWatchProviders200ResponseResultsBEFlatrateInnerFromJSON,
    MovieWatchProviders200ResponseResultsBEFlatrateInnerFromJSONTyped,
    MovieWatchProviders200ResponseResultsBEFlatrateInnerToJSON,
    MovieWatchProviders200ResponseResultsBEFlatrateInnerToJSONTyped,
} from './MovieWatchProviders200ResponseResultsBEFlatrateInner';

/**
 * 
 * @export
 * @interface MovieWatchProviders200ResponseResultsIS
 */
export interface MovieWatchProviders200ResponseResultsIS {
    /**
     * 
     * @type {string}
     * @memberof MovieWatchProviders200ResponseResultsIS
     */
    link?: string;
    /**
     * 
     * @type {Array<MovieWatchProviders200ResponseResultsCLBuyInner>}
     * @memberof MovieWatchProviders200ResponseResultsIS
     */
    buy?: Array<MovieWatchProviders200ResponseResultsCLBuyInner>;
    /**
     * 
     * @type {Array<MovieWatchProviders200ResponseResultsBEFlatrateInner>}
     * @memberof MovieWatchProviders200ResponseResultsIS
     */
    flatrate?: Array<MovieWatchProviders200ResponseResultsBEFlatrateInner>;
}

/**
 * Check if a given object implements the MovieWatchProviders200ResponseResultsIS interface.
 */
export function instanceOfMovieWatchProviders200ResponseResultsIS(value: object): value is MovieWatchProviders200ResponseResultsIS {
    return true;
}

export function MovieWatchProviders200ResponseResultsISFromJSON(json: any): MovieWatchProviders200ResponseResultsIS {
    return MovieWatchProviders200ResponseResultsISFromJSONTyped(json, false);
}

export function MovieWatchProviders200ResponseResultsISFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieWatchProviders200ResponseResultsIS {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'] == null ? undefined : json['link'],
        'buy': json['buy'] == null ? undefined : ((json['buy'] as Array<any>).map(MovieWatchProviders200ResponseResultsCLBuyInnerFromJSON)),
        'flatrate': json['flatrate'] == null ? undefined : ((json['flatrate'] as Array<any>).map(MovieWatchProviders200ResponseResultsBEFlatrateInnerFromJSON)),
    };
}

export function MovieWatchProviders200ResponseResultsISToJSON(json: any): MovieWatchProviders200ResponseResultsIS {
    return MovieWatchProviders200ResponseResultsISToJSONTyped(json, false);
}

export function MovieWatchProviders200ResponseResultsISToJSONTyped(value?: MovieWatchProviders200ResponseResultsIS | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
        'buy': value['buy'] == null ? undefined : ((value['buy'] as Array<any>).map(MovieWatchProviders200ResponseResultsCLBuyInnerToJSON)),
        'flatrate': value['flatrate'] == null ? undefined : ((value['flatrate'] as Array<any>).map(MovieWatchProviders200ResponseResultsBEFlatrateInnerToJSON)),
    };
}

