/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MovieTranslations200ResponseTranslationsInnerData } from './MovieTranslations200ResponseTranslationsInnerData';
import {
    MovieTranslations200ResponseTranslationsInnerDataFromJSON,
    MovieTranslations200ResponseTranslationsInnerDataFromJSONTyped,
    MovieTranslations200ResponseTranslationsInnerDataToJSON,
    MovieTranslations200ResponseTranslationsInnerDataToJSONTyped,
} from './MovieTranslations200ResponseTranslationsInnerData';

/**
 * 
 * @export
 * @interface MovieTranslations200ResponseTranslationsInner
 */
export interface MovieTranslations200ResponseTranslationsInner {
    /**
     * 
     * @type {string}
     * @memberof MovieTranslations200ResponseTranslationsInner
     */
    iso31661?: string;
    /**
     * 
     * @type {string}
     * @memberof MovieTranslations200ResponseTranslationsInner
     */
    iso6391?: string;
    /**
     * 
     * @type {string}
     * @memberof MovieTranslations200ResponseTranslationsInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof MovieTranslations200ResponseTranslationsInner
     */
    englishName?: string;
    /**
     * 
     * @type {MovieTranslations200ResponseTranslationsInnerData}
     * @memberof MovieTranslations200ResponseTranslationsInner
     */
    data?: MovieTranslations200ResponseTranslationsInnerData;
}

/**
 * Check if a given object implements the MovieTranslations200ResponseTranslationsInner interface.
 */
export function instanceOfMovieTranslations200ResponseTranslationsInner(value: object): value is MovieTranslations200ResponseTranslationsInner {
    return true;
}

export function MovieTranslations200ResponseTranslationsInnerFromJSON(json: any): MovieTranslations200ResponseTranslationsInner {
    return MovieTranslations200ResponseTranslationsInnerFromJSONTyped(json, false);
}

export function MovieTranslations200ResponseTranslationsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieTranslations200ResponseTranslationsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'iso31661': json['iso_3166_1'] == null ? undefined : json['iso_3166_1'],
        'iso6391': json['iso_639_1'] == null ? undefined : json['iso_639_1'],
        'name': json['name'] == null ? undefined : json['name'],
        'englishName': json['english_name'] == null ? undefined : json['english_name'],
        'data': json['data'] == null ? undefined : MovieTranslations200ResponseTranslationsInnerDataFromJSON(json['data']),
    };
}

export function MovieTranslations200ResponseTranslationsInnerToJSON(json: any): MovieTranslations200ResponseTranslationsInner {
    return MovieTranslations200ResponseTranslationsInnerToJSONTyped(json, false);
}

export function MovieTranslations200ResponseTranslationsInnerToJSONTyped(value?: MovieTranslations200ResponseTranslationsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'iso_3166_1': value['iso31661'],
        'iso_639_1': value['iso6391'],
        'name': value['name'],
        'english_name': value['englishName'],
        'data': MovieTranslations200ResponseTranslationsInnerDataToJSON(value['data']),
    };
}

