/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MovieWatchProviders200ResponseResultsPLFlatrateInner } from './MovieWatchProviders200ResponseResultsPLFlatrateInner';
import {
    MovieWatchProviders200ResponseResultsPLFlatrateInnerFromJSON,
    MovieWatchProviders200ResponseResultsPLFlatrateInnerFromJSONTyped,
    MovieWatchProviders200ResponseResultsPLFlatrateInnerToJSON,
    MovieWatchProviders200ResponseResultsPLFlatrateInnerToJSONTyped,
} from './MovieWatchProviders200ResponseResultsPLFlatrateInner';
import type { MovieWatchProviders200ResponseResultsAERentInner } from './MovieWatchProviders200ResponseResultsAERentInner';
import {
    MovieWatchProviders200ResponseResultsAERentInnerFromJSON,
    MovieWatchProviders200ResponseResultsAERentInnerFromJSONTyped,
    MovieWatchProviders200ResponseResultsAERentInnerToJSON,
    MovieWatchProviders200ResponseResultsAERentInnerToJSONTyped,
} from './MovieWatchProviders200ResponseResultsAERentInner';

/**
 * 
 * @export
 * @interface MovieWatchProviders200ResponseResultsPL
 */
export interface MovieWatchProviders200ResponseResultsPL {
    /**
     * 
     * @type {string}
     * @memberof MovieWatchProviders200ResponseResultsPL
     */
    link?: string;
    /**
     * 
     * @type {Array<MovieWatchProviders200ResponseResultsAERentInner>}
     * @memberof MovieWatchProviders200ResponseResultsPL
     */
    buy?: Array<MovieWatchProviders200ResponseResultsAERentInner>;
    /**
     * 
     * @type {Array<MovieWatchProviders200ResponseResultsPLFlatrateInner>}
     * @memberof MovieWatchProviders200ResponseResultsPL
     */
    flatrate?: Array<MovieWatchProviders200ResponseResultsPLFlatrateInner>;
    /**
     * 
     * @type {Array<MovieWatchProviders200ResponseResultsAERentInner>}
     * @memberof MovieWatchProviders200ResponseResultsPL
     */
    rent?: Array<MovieWatchProviders200ResponseResultsAERentInner>;
}

/**
 * Check if a given object implements the MovieWatchProviders200ResponseResultsPL interface.
 */
export function instanceOfMovieWatchProviders200ResponseResultsPL(value: object): value is MovieWatchProviders200ResponseResultsPL {
    return true;
}

export function MovieWatchProviders200ResponseResultsPLFromJSON(json: any): MovieWatchProviders200ResponseResultsPL {
    return MovieWatchProviders200ResponseResultsPLFromJSONTyped(json, false);
}

export function MovieWatchProviders200ResponseResultsPLFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieWatchProviders200ResponseResultsPL {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'] == null ? undefined : json['link'],
        'buy': json['buy'] == null ? undefined : ((json['buy'] as Array<any>).map(MovieWatchProviders200ResponseResultsAERentInnerFromJSON)),
        'flatrate': json['flatrate'] == null ? undefined : ((json['flatrate'] as Array<any>).map(MovieWatchProviders200ResponseResultsPLFlatrateInnerFromJSON)),
        'rent': json['rent'] == null ? undefined : ((json['rent'] as Array<any>).map(MovieWatchProviders200ResponseResultsAERentInnerFromJSON)),
    };
}

export function MovieWatchProviders200ResponseResultsPLToJSON(json: any): MovieWatchProviders200ResponseResultsPL {
    return MovieWatchProviders200ResponseResultsPLToJSONTyped(json, false);
}

export function MovieWatchProviders200ResponseResultsPLToJSONTyped(value?: MovieWatchProviders200ResponseResultsPL | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
        'buy': value['buy'] == null ? undefined : ((value['buy'] as Array<any>).map(MovieWatchProviders200ResponseResultsAERentInnerToJSON)),
        'flatrate': value['flatrate'] == null ? undefined : ((value['flatrate'] as Array<any>).map(MovieWatchProviders200ResponseResultsPLFlatrateInnerToJSON)),
        'rent': value['rent'] == null ? undefined : ((value['rent'] as Array<any>).map(MovieWatchProviders200ResponseResultsAERentInnerToJSON)),
    };
}

