/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MovieWatchProviders200ResponseResultsCZBuyInner } from './MovieWatchProviders200ResponseResultsCZBuyInner';
import {
    MovieWatchProviders200ResponseResultsCZBuyInnerFromJSON,
    MovieWatchProviders200ResponseResultsCZBuyInnerFromJSONTyped,
    MovieWatchProviders200ResponseResultsCZBuyInnerToJSON,
    MovieWatchProviders200ResponseResultsCZBuyInnerToJSONTyped,
} from './MovieWatchProviders200ResponseResultsCZBuyInner';
import type { MovieWatchProviders200ResponseResultsAUFlatrateInner } from './MovieWatchProviders200ResponseResultsAUFlatrateInner';
import {
    MovieWatchProviders200ResponseResultsAUFlatrateInnerFromJSON,
    MovieWatchProviders200ResponseResultsAUFlatrateInnerFromJSONTyped,
    MovieWatchProviders200ResponseResultsAUFlatrateInnerToJSON,
    MovieWatchProviders200ResponseResultsAUFlatrateInnerToJSONTyped,
} from './MovieWatchProviders200ResponseResultsAUFlatrateInner';

/**
 * 
 * @export
 * @interface MovieWatchProviders200ResponseResultsSK
 */
export interface MovieWatchProviders200ResponseResultsSK {
    /**
     * 
     * @type {string}
     * @memberof MovieWatchProviders200ResponseResultsSK
     */
    link?: string;
    /**
     * 
     * @type {Array<MovieWatchProviders200ResponseResultsCZBuyInner>}
     * @memberof MovieWatchProviders200ResponseResultsSK
     */
    buy?: Array<MovieWatchProviders200ResponseResultsCZBuyInner>;
    /**
     * 
     * @type {Array<MovieWatchProviders200ResponseResultsAUFlatrateInner>}
     * @memberof MovieWatchProviders200ResponseResultsSK
     */
    flatrate?: Array<MovieWatchProviders200ResponseResultsAUFlatrateInner>;
    /**
     * 
     * @type {Array<MovieWatchProviders200ResponseResultsCZBuyInner>}
     * @memberof MovieWatchProviders200ResponseResultsSK
     */
    rent?: Array<MovieWatchProviders200ResponseResultsCZBuyInner>;
}

/**
 * Check if a given object implements the MovieWatchProviders200ResponseResultsSK interface.
 */
export function instanceOfMovieWatchProviders200ResponseResultsSK(value: object): value is MovieWatchProviders200ResponseResultsSK {
    return true;
}

export function MovieWatchProviders200ResponseResultsSKFromJSON(json: any): MovieWatchProviders200ResponseResultsSK {
    return MovieWatchProviders200ResponseResultsSKFromJSONTyped(json, false);
}

export function MovieWatchProviders200ResponseResultsSKFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieWatchProviders200ResponseResultsSK {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'] == null ? undefined : json['link'],
        'buy': json['buy'] == null ? undefined : ((json['buy'] as Array<any>).map(MovieWatchProviders200ResponseResultsCZBuyInnerFromJSON)),
        'flatrate': json['flatrate'] == null ? undefined : ((json['flatrate'] as Array<any>).map(MovieWatchProviders200ResponseResultsAUFlatrateInnerFromJSON)),
        'rent': json['rent'] == null ? undefined : ((json['rent'] as Array<any>).map(MovieWatchProviders200ResponseResultsCZBuyInnerFromJSON)),
    };
}

export function MovieWatchProviders200ResponseResultsSKToJSON(json: any): MovieWatchProviders200ResponseResultsSK {
    return MovieWatchProviders200ResponseResultsSKToJSONTyped(json, false);
}

export function MovieWatchProviders200ResponseResultsSKToJSONTyped(value?: MovieWatchProviders200ResponseResultsSK | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
        'buy': value['buy'] == null ? undefined : ((value['buy'] as Array<any>).map(MovieWatchProviders200ResponseResultsCZBuyInnerToJSON)),
        'flatrate': value['flatrate'] == null ? undefined : ((value['flatrate'] as Array<any>).map(MovieWatchProviders200ResponseResultsAUFlatrateInnerToJSON)),
        'rent': value['rent'] == null ? undefined : ((value['rent'] as Array<any>).map(MovieWatchProviders200ResponseResultsCZBuyInnerToJSON)),
    };
}

