/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MovieWatchProviders200ResponseResultsMYFlatrateInner } from './MovieWatchProviders200ResponseResultsMYFlatrateInner';
import {
    MovieWatchProviders200ResponseResultsMYFlatrateInnerFromJSON,
    MovieWatchProviders200ResponseResultsMYFlatrateInnerFromJSONTyped,
    MovieWatchProviders200ResponseResultsMYFlatrateInnerToJSON,
    MovieWatchProviders200ResponseResultsMYFlatrateInnerToJSONTyped,
} from './MovieWatchProviders200ResponseResultsMYFlatrateInner';

/**
 * 
 * @export
 * @interface MovieWatchProviders200ResponseResultsMY
 */
export interface MovieWatchProviders200ResponseResultsMY {
    /**
     * 
     * @type {string}
     * @memberof MovieWatchProviders200ResponseResultsMY
     */
    link?: string;
    /**
     * 
     * @type {Array<MovieWatchProviders200ResponseResultsMYFlatrateInner>}
     * @memberof MovieWatchProviders200ResponseResultsMY
     */
    flatrate?: Array<MovieWatchProviders200ResponseResultsMYFlatrateInner>;
}

/**
 * Check if a given object implements the MovieWatchProviders200ResponseResultsMY interface.
 */
export function instanceOfMovieWatchProviders200ResponseResultsMY(value: object): value is MovieWatchProviders200ResponseResultsMY {
    return true;
}

export function MovieWatchProviders200ResponseResultsMYFromJSON(json: any): MovieWatchProviders200ResponseResultsMY {
    return MovieWatchProviders200ResponseResultsMYFromJSONTyped(json, false);
}

export function MovieWatchProviders200ResponseResultsMYFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieWatchProviders200ResponseResultsMY {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'] == null ? undefined : json['link'],
        'flatrate': json['flatrate'] == null ? undefined : ((json['flatrate'] as Array<any>).map(MovieWatchProviders200ResponseResultsMYFlatrateInnerFromJSON)),
    };
}

export function MovieWatchProviders200ResponseResultsMYToJSON(json: any): MovieWatchProviders200ResponseResultsMY {
    return MovieWatchProviders200ResponseResultsMYToJSONTyped(json, false);
}

export function MovieWatchProviders200ResponseResultsMYToJSONTyped(value?: MovieWatchProviders200ResponseResultsMY | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
        'flatrate': value['flatrate'] == null ? undefined : ((value['flatrate'] as Array<any>).map(MovieWatchProviders200ResponseResultsMYFlatrateInnerToJSON)),
    };
}

