/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MovieWatchProviders200ResponseResultsPTRentInner
 */
export interface MovieWatchProviders200ResponseResultsPTRentInner {
    /**
     * 
     * @type {string}
     * @memberof MovieWatchProviders200ResponseResultsPTRentInner
     */
    logoPath?: string;
    /**
     * 
     * @type {number}
     * @memberof MovieWatchProviders200ResponseResultsPTRentInner
     */
    providerId?: number;
    /**
     * 
     * @type {string}
     * @memberof MovieWatchProviders200ResponseResultsPTRentInner
     */
    providerName?: string;
    /**
     * 
     * @type {number}
     * @memberof MovieWatchProviders200ResponseResultsPTRentInner
     */
    displayPriority?: number;
}

/**
 * Check if a given object implements the MovieWatchProviders200ResponseResultsPTRentInner interface.
 */
export function instanceOfMovieWatchProviders200ResponseResultsPTRentInner(value: object): value is MovieWatchProviders200ResponseResultsPTRentInner {
    return true;
}

export function MovieWatchProviders200ResponseResultsPTRentInnerFromJSON(json: any): MovieWatchProviders200ResponseResultsPTRentInner {
    return MovieWatchProviders200ResponseResultsPTRentInnerFromJSONTyped(json, false);
}

export function MovieWatchProviders200ResponseResultsPTRentInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieWatchProviders200ResponseResultsPTRentInner {
    if (json == null) {
        return json;
    }
    return {
        
        'logoPath': json['logo_path'] == null ? undefined : json['logo_path'],
        'providerId': json['provider_id'] == null ? undefined : json['provider_id'],
        'providerName': json['provider_name'] == null ? undefined : json['provider_name'],
        'displayPriority': json['display_priority'] == null ? undefined : json['display_priority'],
    };
}

export function MovieWatchProviders200ResponseResultsPTRentInnerToJSON(json: any): MovieWatchProviders200ResponseResultsPTRentInner {
    return MovieWatchProviders200ResponseResultsPTRentInnerToJSONTyped(json, false);
}

export function MovieWatchProviders200ResponseResultsPTRentInnerToJSONTyped(value?: MovieWatchProviders200ResponseResultsPTRentInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'logo_path': value['logoPath'],
        'provider_id': value['providerId'],
        'provider_name': value['providerName'],
        'display_priority': value['displayPriority'],
    };
}

