/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MovieWatchProviders200ResponseResultsBHBuyInner } from './MovieWatchProviders200ResponseResultsBHBuyInner';
import {
    MovieWatchProviders200ResponseResultsBHBuyInnerFromJSON,
    MovieWatchProviders200ResponseResultsBHBuyInnerFromJSONTyped,
    MovieWatchProviders200ResponseResultsBHBuyInnerToJSON,
    MovieWatchProviders200ResponseResultsBHBuyInnerToJSONTyped,
} from './MovieWatchProviders200ResponseResultsBHBuyInner';
import type { MovieWatchProviders200ResponseResultsAUFlatrateInner } from './MovieWatchProviders200ResponseResultsAUFlatrateInner';
import {
    MovieWatchProviders200ResponseResultsAUFlatrateInnerFromJSON,
    MovieWatchProviders200ResponseResultsAUFlatrateInnerFromJSONTyped,
    MovieWatchProviders200ResponseResultsAUFlatrateInnerToJSON,
    MovieWatchProviders200ResponseResultsAUFlatrateInnerToJSONTyped,
} from './MovieWatchProviders200ResponseResultsAUFlatrateInner';

/**
 * 
 * @export
 * @interface MovieWatchProviders200ResponseResultsQA
 */
export interface MovieWatchProviders200ResponseResultsQA {
    /**
     * 
     * @type {string}
     * @memberof MovieWatchProviders200ResponseResultsQA
     */
    link?: string;
    /**
     * 
     * @type {Array<MovieWatchProviders200ResponseResultsAUFlatrateInner>}
     * @memberof MovieWatchProviders200ResponseResultsQA
     */
    flatrate?: Array<MovieWatchProviders200ResponseResultsAUFlatrateInner>;
    /**
     * 
     * @type {Array<MovieWatchProviders200ResponseResultsBHBuyInner>}
     * @memberof MovieWatchProviders200ResponseResultsQA
     */
    buy?: Array<MovieWatchProviders200ResponseResultsBHBuyInner>;
}

/**
 * Check if a given object implements the MovieWatchProviders200ResponseResultsQA interface.
 */
export function instanceOfMovieWatchProviders200ResponseResultsQA(value: object): value is MovieWatchProviders200ResponseResultsQA {
    return true;
}

export function MovieWatchProviders200ResponseResultsQAFromJSON(json: any): MovieWatchProviders200ResponseResultsQA {
    return MovieWatchProviders200ResponseResultsQAFromJSONTyped(json, false);
}

export function MovieWatchProviders200ResponseResultsQAFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieWatchProviders200ResponseResultsQA {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'] == null ? undefined : json['link'],
        'flatrate': json['flatrate'] == null ? undefined : ((json['flatrate'] as Array<any>).map(MovieWatchProviders200ResponseResultsAUFlatrateInnerFromJSON)),
        'buy': json['buy'] == null ? undefined : ((json['buy'] as Array<any>).map(MovieWatchProviders200ResponseResultsBHBuyInnerFromJSON)),
    };
}

export function MovieWatchProviders200ResponseResultsQAToJSON(json: any): MovieWatchProviders200ResponseResultsQA {
    return MovieWatchProviders200ResponseResultsQAToJSONTyped(json, false);
}

export function MovieWatchProviders200ResponseResultsQAToJSONTyped(value?: MovieWatchProviders200ResponseResultsQA | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
        'flatrate': value['flatrate'] == null ? undefined : ((value['flatrate'] as Array<any>).map(MovieWatchProviders200ResponseResultsAUFlatrateInnerToJSON)),
        'buy': value['buy'] == null ? undefined : ((value['buy'] as Array<any>).map(MovieWatchProviders200ResponseResultsBHBuyInnerToJSON)),
    };
}

