/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MovieAccountStates200ResponseRated } from './MovieAccountStates200ResponseRated';
import {
    MovieAccountStates200ResponseRatedFromJSON,
    MovieAccountStates200ResponseRatedFromJSONTyped,
    MovieAccountStates200ResponseRatedToJSON,
    MovieAccountStates200ResponseRatedToJSONTyped,
} from './MovieAccountStates200ResponseRated';

/**
 * 
 * @export
 * @interface MovieAccountStates200Response
 */
export interface MovieAccountStates200Response {
    /**
     * 
     * @type {number}
     * @memberof MovieAccountStates200Response
     */
    id?: number;
    /**
     * 
     * @type {boolean}
     * @memberof MovieAccountStates200Response
     */
    favorite?: boolean;
    /**
     * 
     * @type {MovieAccountStates200ResponseRated}
     * @memberof MovieAccountStates200Response
     */
    rated?: MovieAccountStates200ResponseRated;
    /**
     * 
     * @type {boolean}
     * @memberof MovieAccountStates200Response
     */
    watchlist?: boolean;
}

/**
 * Check if a given object implements the MovieAccountStates200Response interface.
 */
export function instanceOfMovieAccountStates200Response(value: object): value is MovieAccountStates200Response {
    return true;
}

export function MovieAccountStates200ResponseFromJSON(json: any): MovieAccountStates200Response {
    return MovieAccountStates200ResponseFromJSONTyped(json, false);
}

export function MovieAccountStates200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieAccountStates200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'favorite': json['favorite'] == null ? undefined : json['favorite'],
        'rated': json['rated'] == null ? undefined : MovieAccountStates200ResponseRatedFromJSON(json['rated']),
        'watchlist': json['watchlist'] == null ? undefined : json['watchlist'],
    };
}

export function MovieAccountStates200ResponseToJSON(json: any): MovieAccountStates200Response {
    return MovieAccountStates200ResponseToJSONTyped(json, false);
}

export function MovieAccountStates200ResponseToJSONTyped(value?: MovieAccountStates200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'favorite': value['favorite'],
        'rated': MovieAccountStates200ResponseRatedToJSON(value['rated']),
        'watchlist': value['watchlist'],
    };
}

