/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MovieTopRatedList200ResponseResultsInner } from './MovieTopRatedList200ResponseResultsInner';
import {
    MovieTopRatedList200ResponseResultsInnerFromJSON,
    MovieTopRatedList200ResponseResultsInnerFromJSONTyped,
    MovieTopRatedList200ResponseResultsInnerToJSON,
    MovieTopRatedList200ResponseResultsInnerToJSONTyped,
} from './MovieTopRatedList200ResponseResultsInner';

/**
 * 
 * @export
 * @interface MovieTopRatedList200Response
 */
export interface MovieTopRatedList200Response {
    /**
     * 
     * @type {number}
     * @memberof MovieTopRatedList200Response
     */
    page?: number;
    /**
     * 
     * @type {Array<MovieTopRatedList200ResponseResultsInner>}
     * @memberof MovieTopRatedList200Response
     */
    results?: Array<MovieTopRatedList200ResponseResultsInner>;
    /**
     * 
     * @type {number}
     * @memberof MovieTopRatedList200Response
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof MovieTopRatedList200Response
     */
    totalResults?: number;
}

/**
 * Check if a given object implements the MovieTopRatedList200Response interface.
 */
export function instanceOfMovieTopRatedList200Response(value: object): value is MovieTopRatedList200Response {
    return true;
}

export function MovieTopRatedList200ResponseFromJSON(json: any): MovieTopRatedList200Response {
    return MovieTopRatedList200ResponseFromJSONTyped(json, false);
}

export function MovieTopRatedList200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieTopRatedList200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'] == null ? undefined : json['page'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(MovieTopRatedList200ResponseResultsInnerFromJSON)),
        'totalPages': json['total_pages'] == null ? undefined : json['total_pages'],
        'totalResults': json['total_results'] == null ? undefined : json['total_results'],
    };
}

export function MovieTopRatedList200ResponseToJSON(json: any): MovieTopRatedList200Response {
    return MovieTopRatedList200ResponseToJSONTyped(json, false);
}

export function MovieTopRatedList200ResponseToJSONTyped(value?: MovieTopRatedList200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(MovieTopRatedList200ResponseResultsInnerToJSON)),
        'total_pages': value['totalPages'],
        'total_results': value['totalResults'],
    };
}

