/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MovieWatchProviders200ResponseResultsAEFlatrateInner } from './MovieWatchProviders200ResponseResultsAEFlatrateInner';
import {
    MovieWatchProviders200ResponseResultsAEFlatrateInnerFromJSON,
    MovieWatchProviders200ResponseResultsAEFlatrateInnerFromJSONTyped,
    MovieWatchProviders200ResponseResultsAEFlatrateInnerToJSON,
    MovieWatchProviders200ResponseResultsAEFlatrateInnerToJSONTyped,
} from './MovieWatchProviders200ResponseResultsAEFlatrateInner';
import type { MovieWatchProviders200ResponseResultsAERentInner } from './MovieWatchProviders200ResponseResultsAERentInner';
import {
    MovieWatchProviders200ResponseResultsAERentInnerFromJSON,
    MovieWatchProviders200ResponseResultsAERentInnerFromJSONTyped,
    MovieWatchProviders200ResponseResultsAERentInnerToJSON,
    MovieWatchProviders200ResponseResultsAERentInnerToJSONTyped,
} from './MovieWatchProviders200ResponseResultsAERentInner';

/**
 * 
 * @export
 * @interface MovieWatchProviders200ResponseResultsAE
 */
export interface MovieWatchProviders200ResponseResultsAE {
    /**
     * 
     * @type {string}
     * @memberof MovieWatchProviders200ResponseResultsAE
     */
    link?: string;
    /**
     * 
     * @type {Array<MovieWatchProviders200ResponseResultsAEFlatrateInner>}
     * @memberof MovieWatchProviders200ResponseResultsAE
     */
    flatrate?: Array<MovieWatchProviders200ResponseResultsAEFlatrateInner>;
    /**
     * 
     * @type {Array<MovieWatchProviders200ResponseResultsAERentInner>}
     * @memberof MovieWatchProviders200ResponseResultsAE
     */
    rent?: Array<MovieWatchProviders200ResponseResultsAERentInner>;
    /**
     * 
     * @type {Array<MovieWatchProviders200ResponseResultsAERentInner>}
     * @memberof MovieWatchProviders200ResponseResultsAE
     */
    buy?: Array<MovieWatchProviders200ResponseResultsAERentInner>;
}

/**
 * Check if a given object implements the MovieWatchProviders200ResponseResultsAE interface.
 */
export function instanceOfMovieWatchProviders200ResponseResultsAE(value: object): value is MovieWatchProviders200ResponseResultsAE {
    return true;
}

export function MovieWatchProviders200ResponseResultsAEFromJSON(json: any): MovieWatchProviders200ResponseResultsAE {
    return MovieWatchProviders200ResponseResultsAEFromJSONTyped(json, false);
}

export function MovieWatchProviders200ResponseResultsAEFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieWatchProviders200ResponseResultsAE {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'] == null ? undefined : json['link'],
        'flatrate': json['flatrate'] == null ? undefined : ((json['flatrate'] as Array<any>).map(MovieWatchProviders200ResponseResultsAEFlatrateInnerFromJSON)),
        'rent': json['rent'] == null ? undefined : ((json['rent'] as Array<any>).map(MovieWatchProviders200ResponseResultsAERentInnerFromJSON)),
        'buy': json['buy'] == null ? undefined : ((json['buy'] as Array<any>).map(MovieWatchProviders200ResponseResultsAERentInnerFromJSON)),
    };
}

export function MovieWatchProviders200ResponseResultsAEToJSON(json: any): MovieWatchProviders200ResponseResultsAE {
    return MovieWatchProviders200ResponseResultsAEToJSONTyped(json, false);
}

export function MovieWatchProviders200ResponseResultsAEToJSONTyped(value?: MovieWatchProviders200ResponseResultsAE | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
        'flatrate': value['flatrate'] == null ? undefined : ((value['flatrate'] as Array<any>).map(MovieWatchProviders200ResponseResultsAEFlatrateInnerToJSON)),
        'rent': value['rent'] == null ? undefined : ((value['rent'] as Array<any>).map(MovieWatchProviders200ResponseResultsAERentInnerToJSON)),
        'buy': value['buy'] == null ? undefined : ((value['buy'] as Array<any>).map(MovieWatchProviders200ResponseResultsAERentInnerToJSON)),
    };
}

