/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MovieCredits200ResponseCastInner } from './MovieCredits200ResponseCastInner';
import {
    MovieCredits200ResponseCastInnerFromJSON,
    MovieCredits200ResponseCastInnerFromJSONTyped,
    MovieCredits200ResponseCastInnerToJSON,
    MovieCredits200ResponseCastInnerToJSONTyped,
} from './MovieCredits200ResponseCastInner';
import type { MovieCredits200ResponseCrewInner } from './MovieCredits200ResponseCrewInner';
import {
    MovieCredits200ResponseCrewInnerFromJSON,
    MovieCredits200ResponseCrewInnerFromJSONTyped,
    MovieCredits200ResponseCrewInnerToJSON,
    MovieCredits200ResponseCrewInnerToJSONTyped,
} from './MovieCredits200ResponseCrewInner';

/**
 * 
 * @export
 * @interface MovieCredits200Response
 */
export interface MovieCredits200Response {
    /**
     * 
     * @type {number}
     * @memberof MovieCredits200Response
     */
    id?: number;
    /**
     * 
     * @type {Array<MovieCredits200ResponseCastInner>}
     * @memberof MovieCredits200Response
     */
    cast?: Array<MovieCredits200ResponseCastInner>;
    /**
     * 
     * @type {Array<MovieCredits200ResponseCrewInner>}
     * @memberof MovieCredits200Response
     */
    crew?: Array<MovieCredits200ResponseCrewInner>;
}

/**
 * Check if a given object implements the MovieCredits200Response interface.
 */
export function instanceOfMovieCredits200Response(value: object): value is MovieCredits200Response {
    return true;
}

export function MovieCredits200ResponseFromJSON(json: any): MovieCredits200Response {
    return MovieCredits200ResponseFromJSONTyped(json, false);
}

export function MovieCredits200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieCredits200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'cast': json['cast'] == null ? undefined : ((json['cast'] as Array<any>).map(MovieCredits200ResponseCastInnerFromJSON)),
        'crew': json['crew'] == null ? undefined : ((json['crew'] as Array<any>).map(MovieCredits200ResponseCrewInnerFromJSON)),
    };
}

export function MovieCredits200ResponseToJSON(json: any): MovieCredits200Response {
    return MovieCredits200ResponseToJSONTyped(json, false);
}

export function MovieCredits200ResponseToJSONTyped(value?: MovieCredits200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'cast': value['cast'] == null ? undefined : ((value['cast'] as Array<any>).map(MovieCredits200ResponseCastInnerToJSON)),
        'crew': value['crew'] == null ? undefined : ((value['crew'] as Array<any>).map(MovieCredits200ResponseCrewInnerToJSON)),
    };
}

