/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MovieWatchProviders200ResponseResultsCOBuyInner } from './MovieWatchProviders200ResponseResultsCOBuyInner';
import {
    MovieWatchProviders200ResponseResultsCOBuyInnerFromJSON,
    MovieWatchProviders200ResponseResultsCOBuyInnerFromJSONTyped,
    MovieWatchProviders200ResponseResultsCOBuyInnerToJSON,
    MovieWatchProviders200ResponseResultsCOBuyInnerToJSONTyped,
} from './MovieWatchProviders200ResponseResultsCOBuyInner';
import type { MovieWatchProviders200ResponseResultsARFlatrateInner } from './MovieWatchProviders200ResponseResultsARFlatrateInner';
import {
    MovieWatchProviders200ResponseResultsARFlatrateInnerFromJSON,
    MovieWatchProviders200ResponseResultsARFlatrateInnerFromJSONTyped,
    MovieWatchProviders200ResponseResultsARFlatrateInnerToJSON,
    MovieWatchProviders200ResponseResultsARFlatrateInnerToJSONTyped,
} from './MovieWatchProviders200ResponseResultsARFlatrateInner';

/**
 * 
 * @export
 * @interface MovieWatchProviders200ResponseResultsVE
 */
export interface MovieWatchProviders200ResponseResultsVE {
    /**
     * 
     * @type {string}
     * @memberof MovieWatchProviders200ResponseResultsVE
     */
    link?: string;
    /**
     * 
     * @type {Array<MovieWatchProviders200ResponseResultsCOBuyInner>}
     * @memberof MovieWatchProviders200ResponseResultsVE
     */
    rent?: Array<MovieWatchProviders200ResponseResultsCOBuyInner>;
    /**
     * 
     * @type {Array<MovieWatchProviders200ResponseResultsARFlatrateInner>}
     * @memberof MovieWatchProviders200ResponseResultsVE
     */
    flatrate?: Array<MovieWatchProviders200ResponseResultsARFlatrateInner>;
    /**
     * 
     * @type {Array<MovieWatchProviders200ResponseResultsCOBuyInner>}
     * @memberof MovieWatchProviders200ResponseResultsVE
     */
    buy?: Array<MovieWatchProviders200ResponseResultsCOBuyInner>;
}

/**
 * Check if a given object implements the MovieWatchProviders200ResponseResultsVE interface.
 */
export function instanceOfMovieWatchProviders200ResponseResultsVE(value: object): value is MovieWatchProviders200ResponseResultsVE {
    return true;
}

export function MovieWatchProviders200ResponseResultsVEFromJSON(json: any): MovieWatchProviders200ResponseResultsVE {
    return MovieWatchProviders200ResponseResultsVEFromJSONTyped(json, false);
}

export function MovieWatchProviders200ResponseResultsVEFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieWatchProviders200ResponseResultsVE {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'] == null ? undefined : json['link'],
        'rent': json['rent'] == null ? undefined : ((json['rent'] as Array<any>).map(MovieWatchProviders200ResponseResultsCOBuyInnerFromJSON)),
        'flatrate': json['flatrate'] == null ? undefined : ((json['flatrate'] as Array<any>).map(MovieWatchProviders200ResponseResultsARFlatrateInnerFromJSON)),
        'buy': json['buy'] == null ? undefined : ((json['buy'] as Array<any>).map(MovieWatchProviders200ResponseResultsCOBuyInnerFromJSON)),
    };
}

export function MovieWatchProviders200ResponseResultsVEToJSON(json: any): MovieWatchProviders200ResponseResultsVE {
    return MovieWatchProviders200ResponseResultsVEToJSONTyped(json, false);
}

export function MovieWatchProviders200ResponseResultsVEToJSONTyped(value?: MovieWatchProviders200ResponseResultsVE | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
        'rent': value['rent'] == null ? undefined : ((value['rent'] as Array<any>).map(MovieWatchProviders200ResponseResultsCOBuyInnerToJSON)),
        'flatrate': value['flatrate'] == null ? undefined : ((value['flatrate'] as Array<any>).map(MovieWatchProviders200ResponseResultsARFlatrateInnerToJSON)),
        'buy': value['buy'] == null ? undefined : ((value['buy'] as Array<any>).map(MovieWatchProviders200ResponseResultsCOBuyInnerToJSON)),
    };
}

