/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PersonImages200ResponseProfilesInner } from './PersonImages200ResponseProfilesInner';
import {
    PersonImages200ResponseProfilesInnerFromJSON,
    PersonImages200ResponseProfilesInnerFromJSONTyped,
    PersonImages200ResponseProfilesInnerToJSON,
    PersonImages200ResponseProfilesInnerToJSONTyped,
} from './PersonImages200ResponseProfilesInner';

/**
 * 
 * @export
 * @interface PersonImages200Response
 */
export interface PersonImages200Response {
    /**
     * 
     * @type {number}
     * @memberof PersonImages200Response
     */
    id?: number;
    /**
     * 
     * @type {Array<PersonImages200ResponseProfilesInner>}
     * @memberof PersonImages200Response
     */
    profiles?: Array<PersonImages200ResponseProfilesInner>;
}

/**
 * Check if a given object implements the PersonImages200Response interface.
 */
export function instanceOfPersonImages200Response(value: object): value is PersonImages200Response {
    return true;
}

export function PersonImages200ResponseFromJSON(json: any): PersonImages200Response {
    return PersonImages200ResponseFromJSONTyped(json, false);
}

export function PersonImages200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonImages200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'profiles': json['profiles'] == null ? undefined : ((json['profiles'] as Array<any>).map(PersonImages200ResponseProfilesInnerFromJSON)),
    };
}

export function PersonImages200ResponseToJSON(json: any): PersonImages200Response {
    return PersonImages200ResponseToJSONTyped(json, false);
}

export function PersonImages200ResponseToJSONTyped(value?: PersonImages200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'profiles': value['profiles'] == null ? undefined : ((value['profiles'] as Array<any>).map(PersonImages200ResponseProfilesInnerToJSON)),
    };
}

