/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PersonExternalIds200Response
 */
export interface PersonExternalIds200Response {
    /**
     * 
     * @type {number}
     * @memberof PersonExternalIds200Response
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof PersonExternalIds200Response
     */
    freebaseMid?: string;
    /**
     * 
     * @type {string}
     * @memberof PersonExternalIds200Response
     */
    freebaseId?: string;
    /**
     * 
     * @type {string}
     * @memberof PersonExternalIds200Response
     */
    imdbId?: string;
    /**
     * 
     * @type {number}
     * @memberof PersonExternalIds200Response
     */
    tvrageId?: number;
    /**
     * 
     * @type {string}
     * @memberof PersonExternalIds200Response
     */
    wikidataId?: string;
    /**
     * 
     * @type {string}
     * @memberof PersonExternalIds200Response
     */
    facebookId?: string;
    /**
     * 
     * @type {string}
     * @memberof PersonExternalIds200Response
     */
    instagramId?: string;
    /**
     * 
     * @type {string}
     * @memberof PersonExternalIds200Response
     */
    tiktokId?: string;
    /**
     * 
     * @type {string}
     * @memberof PersonExternalIds200Response
     */
    twitterId?: string;
    /**
     * 
     * @type {any}
     * @memberof PersonExternalIds200Response
     */
    youtubeId?: any | null;
}

/**
 * Check if a given object implements the PersonExternalIds200Response interface.
 */
export function instanceOfPersonExternalIds200Response(value: object): value is PersonExternalIds200Response {
    return true;
}

export function PersonExternalIds200ResponseFromJSON(json: any): PersonExternalIds200Response {
    return PersonExternalIds200ResponseFromJSONTyped(json, false);
}

export function PersonExternalIds200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonExternalIds200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'freebaseMid': json['freebase_mid'] == null ? undefined : json['freebase_mid'],
        'freebaseId': json['freebase_id'] == null ? undefined : json['freebase_id'],
        'imdbId': json['imdb_id'] == null ? undefined : json['imdb_id'],
        'tvrageId': json['tvrage_id'] == null ? undefined : json['tvrage_id'],
        'wikidataId': json['wikidata_id'] == null ? undefined : json['wikidata_id'],
        'facebookId': json['facebook_id'] == null ? undefined : json['facebook_id'],
        'instagramId': json['instagram_id'] == null ? undefined : json['instagram_id'],
        'tiktokId': json['tiktok_id'] == null ? undefined : json['tiktok_id'],
        'twitterId': json['twitter_id'] == null ? undefined : json['twitter_id'],
        'youtubeId': json['youtube_id'] == null ? undefined : json['youtube_id'],
    };
}

export function PersonExternalIds200ResponseToJSON(json: any): PersonExternalIds200Response {
    return PersonExternalIds200ResponseToJSONTyped(json, false);
}

export function PersonExternalIds200ResponseToJSONTyped(value?: PersonExternalIds200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'freebase_mid': value['freebaseMid'],
        'freebase_id': value['freebaseId'],
        'imdb_id': value['imdbId'],
        'tvrage_id': value['tvrageId'],
        'wikidata_id': value['wikidataId'],
        'facebook_id': value['facebookId'],
        'instagram_id': value['instagramId'],
        'tiktok_id': value['tiktokId'],
        'twitter_id': value['twitterId'],
        'youtube_id': value['youtubeId'],
    };
}

