/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PersonCombinedCredits200ResponseCastInner } from './PersonCombinedCredits200ResponseCastInner';
import {
    PersonCombinedCredits200ResponseCastInnerFromJSON,
    PersonCombinedCredits200ResponseCastInnerFromJSONTyped,
    PersonCombinedCredits200ResponseCastInnerToJSON,
    PersonCombinedCredits200ResponseCastInnerToJSONTyped,
} from './PersonCombinedCredits200ResponseCastInner';
import type { PersonCombinedCredits200ResponseCrewInner } from './PersonCombinedCredits200ResponseCrewInner';
import {
    PersonCombinedCredits200ResponseCrewInnerFromJSON,
    PersonCombinedCredits200ResponseCrewInnerFromJSONTyped,
    PersonCombinedCredits200ResponseCrewInnerToJSON,
    PersonCombinedCredits200ResponseCrewInnerToJSONTyped,
} from './PersonCombinedCredits200ResponseCrewInner';

/**
 * 
 * @export
 * @interface PersonCombinedCredits200Response
 */
export interface PersonCombinedCredits200Response {
    /**
     * 
     * @type {Array<PersonCombinedCredits200ResponseCastInner>}
     * @memberof PersonCombinedCredits200Response
     */
    cast?: Array<PersonCombinedCredits200ResponseCastInner>;
    /**
     * 
     * @type {Array<PersonCombinedCredits200ResponseCrewInner>}
     * @memberof PersonCombinedCredits200Response
     */
    crew?: Array<PersonCombinedCredits200ResponseCrewInner>;
    /**
     * 
     * @type {number}
     * @memberof PersonCombinedCredits200Response
     */
    id?: number;
}

/**
 * Check if a given object implements the PersonCombinedCredits200Response interface.
 */
export function instanceOfPersonCombinedCredits200Response(value: object): value is PersonCombinedCredits200Response {
    return true;
}

export function PersonCombinedCredits200ResponseFromJSON(json: any): PersonCombinedCredits200Response {
    return PersonCombinedCredits200ResponseFromJSONTyped(json, false);
}

export function PersonCombinedCredits200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonCombinedCredits200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'cast': json['cast'] == null ? undefined : ((json['cast'] as Array<any>).map(PersonCombinedCredits200ResponseCastInnerFromJSON)),
        'crew': json['crew'] == null ? undefined : ((json['crew'] as Array<any>).map(PersonCombinedCredits200ResponseCrewInnerFromJSON)),
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function PersonCombinedCredits200ResponseToJSON(json: any): PersonCombinedCredits200Response {
    return PersonCombinedCredits200ResponseToJSONTyped(json, false);
}

export function PersonCombinedCredits200ResponseToJSONTyped(value?: PersonCombinedCredits200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cast': value['cast'] == null ? undefined : ((value['cast'] as Array<any>).map(PersonCombinedCredits200ResponseCastInnerToJSON)),
        'crew': value['crew'] == null ? undefined : ((value['crew'] as Array<any>).map(PersonCombinedCredits200ResponseCrewInnerToJSON)),
        'id': value['id'],
    };
}

