/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SearchMulti200ResponseResultsInner } from './SearchMulti200ResponseResultsInner';
import {
    SearchMulti200ResponseResultsInnerFromJSON,
    SearchMulti200ResponseResultsInnerFromJSONTyped,
    SearchMulti200ResponseResultsInnerToJSON,
    SearchMulti200ResponseResultsInnerToJSONTyped,
} from './SearchMulti200ResponseResultsInner';

/**
 * 
 * @export
 * @interface SearchMulti200Response
 */
export interface SearchMulti200Response {
    /**
     * 
     * @type {number}
     * @memberof SearchMulti200Response
     */
    page?: number;
    /**
     * 
     * @type {Array<SearchMulti200ResponseResultsInner>}
     * @memberof SearchMulti200Response
     */
    results?: Array<SearchMulti200ResponseResultsInner>;
    /**
     * 
     * @type {number}
     * @memberof SearchMulti200Response
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof SearchMulti200Response
     */
    totalResults?: number;
}

/**
 * Check if a given object implements the SearchMulti200Response interface.
 */
export function instanceOfSearchMulti200Response(value: object): value is SearchMulti200Response {
    return true;
}

export function SearchMulti200ResponseFromJSON(json: any): SearchMulti200Response {
    return SearchMulti200ResponseFromJSONTyped(json, false);
}

export function SearchMulti200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchMulti200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'] == null ? undefined : json['page'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(SearchMulti200ResponseResultsInnerFromJSON)),
        'totalPages': json['total_pages'] == null ? undefined : json['total_pages'],
        'totalResults': json['total_results'] == null ? undefined : json['total_results'],
    };
}

export function SearchMulti200ResponseToJSON(json: any): SearchMulti200Response {
    return SearchMulti200ResponseToJSONTyped(json, false);
}

export function SearchMulti200ResponseToJSONTyped(value?: SearchMulti200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(SearchMulti200ResponseResultsInnerToJSON)),
        'total_pages': value['totalPages'],
        'total_results': value['totalResults'],
    };
}

