/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SearchCompany200ResponseResultsInner } from './SearchCompany200ResponseResultsInner';
import {
    SearchCompany200ResponseResultsInnerFromJSON,
    SearchCompany200ResponseResultsInnerFromJSONTyped,
    SearchCompany200ResponseResultsInnerToJSON,
    SearchCompany200ResponseResultsInnerToJSONTyped,
} from './SearchCompany200ResponseResultsInner';

/**
 * 
 * @export
 * @interface SearchCompany200Response
 */
export interface SearchCompany200Response {
    /**
     * 
     * @type {number}
     * @memberof SearchCompany200Response
     */
    page?: number;
    /**
     * 
     * @type {Array<SearchCompany200ResponseResultsInner>}
     * @memberof SearchCompany200Response
     */
    results?: Array<SearchCompany200ResponseResultsInner>;
    /**
     * 
     * @type {number}
     * @memberof SearchCompany200Response
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof SearchCompany200Response
     */
    totalResults?: number;
}

/**
 * Check if a given object implements the SearchCompany200Response interface.
 */
export function instanceOfSearchCompany200Response(value: object): value is SearchCompany200Response {
    return true;
}

export function SearchCompany200ResponseFromJSON(json: any): SearchCompany200Response {
    return SearchCompany200ResponseFromJSONTyped(json, false);
}

export function SearchCompany200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchCompany200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'] == null ? undefined : json['page'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(SearchCompany200ResponseResultsInnerFromJSON)),
        'totalPages': json['total_pages'] == null ? undefined : json['total_pages'],
        'totalResults': json['total_results'] == null ? undefined : json['total_results'],
    };
}

export function SearchCompany200ResponseToJSON(json: any): SearchCompany200Response {
    return SearchCompany200ResponseToJSONTyped(json, false);
}

export function SearchCompany200ResponseToJSONTyped(value?: SearchCompany200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(SearchCompany200ResponseResultsInnerToJSON)),
        'total_pages': value['totalPages'],
        'total_results': value['totalResults'],
    };
}

