/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TrendingPeople200ResponseResultsInnerKnownForInner } from './TrendingPeople200ResponseResultsInnerKnownForInner';
import {
    TrendingPeople200ResponseResultsInnerKnownForInnerFromJSON,
    TrendingPeople200ResponseResultsInnerKnownForInnerFromJSONTyped,
    TrendingPeople200ResponseResultsInnerKnownForInnerToJSON,
    TrendingPeople200ResponseResultsInnerKnownForInnerToJSONTyped,
} from './TrendingPeople200ResponseResultsInnerKnownForInner';

/**
 * 
 * @export
 * @interface TrendingPeople200ResponseResultsInner
 */
export interface TrendingPeople200ResponseResultsInner {
    /**
     * 
     * @type {boolean}
     * @memberof TrendingPeople200ResponseResultsInner
     */
    adult?: boolean;
    /**
     * 
     * @type {number}
     * @memberof TrendingPeople200ResponseResultsInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TrendingPeople200ResponseResultsInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof TrendingPeople200ResponseResultsInner
     */
    originalName?: string;
    /**
     * 
     * @type {string}
     * @memberof TrendingPeople200ResponseResultsInner
     */
    mediaType?: string;
    /**
     * 
     * @type {number}
     * @memberof TrendingPeople200ResponseResultsInner
     */
    popularity?: number;
    /**
     * 
     * @type {number}
     * @memberof TrendingPeople200ResponseResultsInner
     */
    gender?: number;
    /**
     * 
     * @type {string}
     * @memberof TrendingPeople200ResponseResultsInner
     */
    knownForDepartment?: string;
    /**
     * 
     * @type {string}
     * @memberof TrendingPeople200ResponseResultsInner
     */
    profilePath?: string;
    /**
     * 
     * @type {Array<TrendingPeople200ResponseResultsInnerKnownForInner>}
     * @memberof TrendingPeople200ResponseResultsInner
     */
    knownFor?: Array<TrendingPeople200ResponseResultsInnerKnownForInner>;
}

/**
 * Check if a given object implements the TrendingPeople200ResponseResultsInner interface.
 */
export function instanceOfTrendingPeople200ResponseResultsInner(value: object): value is TrendingPeople200ResponseResultsInner {
    return true;
}

export function TrendingPeople200ResponseResultsInnerFromJSON(json: any): TrendingPeople200ResponseResultsInner {
    return TrendingPeople200ResponseResultsInnerFromJSONTyped(json, false);
}

export function TrendingPeople200ResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrendingPeople200ResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'adult': json['adult'] == null ? undefined : json['adult'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'originalName': json['original_name'] == null ? undefined : json['original_name'],
        'mediaType': json['media_type'] == null ? undefined : json['media_type'],
        'popularity': json['popularity'] == null ? undefined : json['popularity'],
        'gender': json['gender'] == null ? undefined : json['gender'],
        'knownForDepartment': json['known_for_department'] == null ? undefined : json['known_for_department'],
        'profilePath': json['profile_path'] == null ? undefined : json['profile_path'],
        'knownFor': json['known_for'] == null ? undefined : ((json['known_for'] as Array<any>).map(TrendingPeople200ResponseResultsInnerKnownForInnerFromJSON)),
    };
}

export function TrendingPeople200ResponseResultsInnerToJSON(json: any): TrendingPeople200ResponseResultsInner {
    return TrendingPeople200ResponseResultsInnerToJSONTyped(json, false);
}

export function TrendingPeople200ResponseResultsInnerToJSONTyped(value?: TrendingPeople200ResponseResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'adult': value['adult'],
        'id': value['id'],
        'name': value['name'],
        'original_name': value['originalName'],
        'media_type': value['mediaType'],
        'popularity': value['popularity'],
        'gender': value['gender'],
        'known_for_department': value['knownForDepartment'],
        'profile_path': value['profilePath'],
        'known_for': value['knownFor'] == null ? undefined : ((value['knownFor'] as Array<any>).map(TrendingPeople200ResponseResultsInnerKnownForInnerToJSON)),
    };
}

