/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TrendingAll200ResponseResultsInner } from './TrendingAll200ResponseResultsInner';
import {
    TrendingAll200ResponseResultsInnerFromJSON,
    TrendingAll200ResponseResultsInnerFromJSONTyped,
    TrendingAll200ResponseResultsInnerToJSON,
    TrendingAll200ResponseResultsInnerToJSONTyped,
} from './TrendingAll200ResponseResultsInner';

/**
 * 
 * @export
 * @interface TrendingAll200Response
 */
export interface TrendingAll200Response {
    /**
     * 
     * @type {number}
     * @memberof TrendingAll200Response
     */
    page?: number;
    /**
     * 
     * @type {Array<TrendingAll200ResponseResultsInner>}
     * @memberof TrendingAll200Response
     */
    results?: Array<TrendingAll200ResponseResultsInner>;
    /**
     * 
     * @type {number}
     * @memberof TrendingAll200Response
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof TrendingAll200Response
     */
    totalResults?: number;
}

/**
 * Check if a given object implements the TrendingAll200Response interface.
 */
export function instanceOfTrendingAll200Response(value: object): value is TrendingAll200Response {
    return true;
}

export function TrendingAll200ResponseFromJSON(json: any): TrendingAll200Response {
    return TrendingAll200ResponseFromJSONTyped(json, false);
}

export function TrendingAll200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrendingAll200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'] == null ? undefined : json['page'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(TrendingAll200ResponseResultsInnerFromJSON)),
        'totalPages': json['total_pages'] == null ? undefined : json['total_pages'],
        'totalResults': json['total_results'] == null ? undefined : json['total_results'],
    };
}

export function TrendingAll200ResponseToJSON(json: any): TrendingAll200Response {
    return TrendingAll200ResponseToJSONTyped(json, false);
}

export function TrendingAll200ResponseToJSONTyped(value?: TrendingAll200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(TrendingAll200ResponseResultsInnerToJSON)),
        'total_pages': value['totalPages'],
        'total_results': value['totalResults'],
    };
}

