/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TvEpisodeGroupDetails200ResponseGroupsInnerEpisodesInner } from './TvEpisodeGroupDetails200ResponseGroupsInnerEpisodesInner';
import {
    TvEpisodeGroupDetails200ResponseGroupsInnerEpisodesInnerFromJSON,
    TvEpisodeGroupDetails200ResponseGroupsInnerEpisodesInnerFromJSONTyped,
    TvEpisodeGroupDetails200ResponseGroupsInnerEpisodesInnerToJSON,
    TvEpisodeGroupDetails200ResponseGroupsInnerEpisodesInnerToJSONTyped,
} from './TvEpisodeGroupDetails200ResponseGroupsInnerEpisodesInner';

/**
 * 
 * @export
 * @interface TvEpisodeGroupDetails200ResponseGroupsInner
 */
export interface TvEpisodeGroupDetails200ResponseGroupsInner {
    /**
     * 
     * @type {string}
     * @memberof TvEpisodeGroupDetails200ResponseGroupsInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof TvEpisodeGroupDetails200ResponseGroupsInner
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof TvEpisodeGroupDetails200ResponseGroupsInner
     */
    order?: number;
    /**
     * 
     * @type {Array<TvEpisodeGroupDetails200ResponseGroupsInnerEpisodesInner>}
     * @memberof TvEpisodeGroupDetails200ResponseGroupsInner
     */
    episodes?: Array<TvEpisodeGroupDetails200ResponseGroupsInnerEpisodesInner>;
    /**
     * 
     * @type {boolean}
     * @memberof TvEpisodeGroupDetails200ResponseGroupsInner
     */
    locked?: boolean;
}

/**
 * Check if a given object implements the TvEpisodeGroupDetails200ResponseGroupsInner interface.
 */
export function instanceOfTvEpisodeGroupDetails200ResponseGroupsInner(value: object): value is TvEpisodeGroupDetails200ResponseGroupsInner {
    return true;
}

export function TvEpisodeGroupDetails200ResponseGroupsInnerFromJSON(json: any): TvEpisodeGroupDetails200ResponseGroupsInner {
    return TvEpisodeGroupDetails200ResponseGroupsInnerFromJSONTyped(json, false);
}

export function TvEpisodeGroupDetails200ResponseGroupsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvEpisodeGroupDetails200ResponseGroupsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'order': json['order'] == null ? undefined : json['order'],
        'episodes': json['episodes'] == null ? undefined : ((json['episodes'] as Array<any>).map(TvEpisodeGroupDetails200ResponseGroupsInnerEpisodesInnerFromJSON)),
        'locked': json['locked'] == null ? undefined : json['locked'],
    };
}

export function TvEpisodeGroupDetails200ResponseGroupsInnerToJSON(json: any): TvEpisodeGroupDetails200ResponseGroupsInner {
    return TvEpisodeGroupDetails200ResponseGroupsInnerToJSONTyped(json, false);
}

export function TvEpisodeGroupDetails200ResponseGroupsInnerToJSONTyped(value?: TvEpisodeGroupDetails200ResponseGroupsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'order': value['order'],
        'episodes': value['episodes'] == null ? undefined : ((value['episodes'] as Array<any>).map(TvEpisodeGroupDetails200ResponseGroupsInnerEpisodesInnerToJSON)),
        'locked': value['locked'],
    };
}

