/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TvEpisodeImages200ResponseStillsInner } from './TvEpisodeImages200ResponseStillsInner';
import {
    TvEpisodeImages200ResponseStillsInnerFromJSON,
    TvEpisodeImages200ResponseStillsInnerFromJSONTyped,
    TvEpisodeImages200ResponseStillsInnerToJSON,
    TvEpisodeImages200ResponseStillsInnerToJSONTyped,
} from './TvEpisodeImages200ResponseStillsInner';

/**
 * 
 * @export
 * @interface TvEpisodeImages200Response
 */
export interface TvEpisodeImages200Response {
    /**
     * 
     * @type {number}
     * @memberof TvEpisodeImages200Response
     */
    id?: number;
    /**
     * 
     * @type {Array<TvEpisodeImages200ResponseStillsInner>}
     * @memberof TvEpisodeImages200Response
     */
    stills?: Array<TvEpisodeImages200ResponseStillsInner>;
}

/**
 * Check if a given object implements the TvEpisodeImages200Response interface.
 */
export function instanceOfTvEpisodeImages200Response(value: object): value is TvEpisodeImages200Response {
    return true;
}

export function TvEpisodeImages200ResponseFromJSON(json: any): TvEpisodeImages200Response {
    return TvEpisodeImages200ResponseFromJSONTyped(json, false);
}

export function TvEpisodeImages200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvEpisodeImages200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'stills': json['stills'] == null ? undefined : ((json['stills'] as Array<any>).map(TvEpisodeImages200ResponseStillsInnerFromJSON)),
    };
}

export function TvEpisodeImages200ResponseToJSON(json: any): TvEpisodeImages200Response {
    return TvEpisodeImages200ResponseToJSONTyped(json, false);
}

export function TvEpisodeImages200ResponseToJSONTyped(value?: TvEpisodeImages200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'stills': value['stills'] == null ? undefined : ((value['stills'] as Array<any>).map(TvEpisodeImages200ResponseStillsInnerToJSON)),
    };
}

