/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TvEpisodeChangesById200ResponseChangesInner } from './TvEpisodeChangesById200ResponseChangesInner';
import {
    TvEpisodeChangesById200ResponseChangesInnerFromJSON,
    TvEpisodeChangesById200ResponseChangesInnerFromJSONTyped,
    TvEpisodeChangesById200ResponseChangesInnerToJSON,
    TvEpisodeChangesById200ResponseChangesInnerToJSONTyped,
} from './TvEpisodeChangesById200ResponseChangesInner';

/**
 * 
 * @export
 * @interface TvEpisodeChangesById200Response
 */
export interface TvEpisodeChangesById200Response {
    /**
     * 
     * @type {Array<TvEpisodeChangesById200ResponseChangesInner>}
     * @memberof TvEpisodeChangesById200Response
     */
    changes?: Array<TvEpisodeChangesById200ResponseChangesInner>;
}

/**
 * Check if a given object implements the TvEpisodeChangesById200Response interface.
 */
export function instanceOfTvEpisodeChangesById200Response(value: object): value is TvEpisodeChangesById200Response {
    return true;
}

export function TvEpisodeChangesById200ResponseFromJSON(json: any): TvEpisodeChangesById200Response {
    return TvEpisodeChangesById200ResponseFromJSONTyped(json, false);
}

export function TvEpisodeChangesById200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvEpisodeChangesById200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'changes': json['changes'] == null ? undefined : ((json['changes'] as Array<any>).map(TvEpisodeChangesById200ResponseChangesInnerFromJSON)),
    };
}

export function TvEpisodeChangesById200ResponseToJSON(json: any): TvEpisodeChangesById200Response {
    return TvEpisodeChangesById200ResponseToJSONTyped(json, false);
}

export function TvEpisodeChangesById200ResponseToJSONTyped(value?: TvEpisodeChangesById200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'changes': value['changes'] == null ? undefined : ((value['changes'] as Array<any>).map(TvEpisodeChangesById200ResponseChangesInnerToJSON)),
    };
}

