/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TvSeasonCredits200ResponseCrewInner
 */
export interface TvSeasonCredits200ResponseCrewInner {
    /**
     * 
     * @type {boolean}
     * @memberof TvSeasonCredits200ResponseCrewInner
     */
    adult?: boolean;
    /**
     * 
     * @type {number}
     * @memberof TvSeasonCredits200ResponseCrewInner
     */
    gender?: number;
    /**
     * 
     * @type {number}
     * @memberof TvSeasonCredits200ResponseCrewInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TvSeasonCredits200ResponseCrewInner
     */
    knownForDepartment?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeasonCredits200ResponseCrewInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeasonCredits200ResponseCrewInner
     */
    originalName?: string;
    /**
     * 
     * @type {number}
     * @memberof TvSeasonCredits200ResponseCrewInner
     */
    popularity?: number;
    /**
     * 
     * @type {any}
     * @memberof TvSeasonCredits200ResponseCrewInner
     */
    profilePath?: any | null;
    /**
     * 
     * @type {string}
     * @memberof TvSeasonCredits200ResponseCrewInner
     */
    creditId?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeasonCredits200ResponseCrewInner
     */
    department?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeasonCredits200ResponseCrewInner
     */
    job?: string;
}

/**
 * Check if a given object implements the TvSeasonCredits200ResponseCrewInner interface.
 */
export function instanceOfTvSeasonCredits200ResponseCrewInner(value: object): value is TvSeasonCredits200ResponseCrewInner {
    return true;
}

export function TvSeasonCredits200ResponseCrewInnerFromJSON(json: any): TvSeasonCredits200ResponseCrewInner {
    return TvSeasonCredits200ResponseCrewInnerFromJSONTyped(json, false);
}

export function TvSeasonCredits200ResponseCrewInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeasonCredits200ResponseCrewInner {
    if (json == null) {
        return json;
    }
    return {
        
        'adult': json['adult'] == null ? undefined : json['adult'],
        'gender': json['gender'] == null ? undefined : json['gender'],
        'id': json['id'] == null ? undefined : json['id'],
        'knownForDepartment': json['known_for_department'] == null ? undefined : json['known_for_department'],
        'name': json['name'] == null ? undefined : json['name'],
        'originalName': json['original_name'] == null ? undefined : json['original_name'],
        'popularity': json['popularity'] == null ? undefined : json['popularity'],
        'profilePath': json['profile_path'] == null ? undefined : json['profile_path'],
        'creditId': json['credit_id'] == null ? undefined : json['credit_id'],
        'department': json['department'] == null ? undefined : json['department'],
        'job': json['job'] == null ? undefined : json['job'],
    };
}

export function TvSeasonCredits200ResponseCrewInnerToJSON(json: any): TvSeasonCredits200ResponseCrewInner {
    return TvSeasonCredits200ResponseCrewInnerToJSONTyped(json, false);
}

export function TvSeasonCredits200ResponseCrewInnerToJSONTyped(value?: TvSeasonCredits200ResponseCrewInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'adult': value['adult'],
        'gender': value['gender'],
        'id': value['id'],
        'known_for_department': value['knownForDepartment'],
        'name': value['name'],
        'original_name': value['originalName'],
        'popularity': value['popularity'],
        'profile_path': value['profilePath'],
        'credit_id': value['creditId'],
        'department': value['department'],
        'job': value['job'],
    };
}

