/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TvSeriesEpisodeGroups200ResponseResultsInner } from './TvSeriesEpisodeGroups200ResponseResultsInner';
import {
    TvSeriesEpisodeGroups200ResponseResultsInnerFromJSON,
    TvSeriesEpisodeGroups200ResponseResultsInnerFromJSONTyped,
    TvSeriesEpisodeGroups200ResponseResultsInnerToJSON,
    TvSeriesEpisodeGroups200ResponseResultsInnerToJSONTyped,
} from './TvSeriesEpisodeGroups200ResponseResultsInner';

/**
 * 
 * @export
 * @interface TvSeriesEpisodeGroups200Response
 */
export interface TvSeriesEpisodeGroups200Response {
    /**
     * 
     * @type {Array<TvSeriesEpisodeGroups200ResponseResultsInner>}
     * @memberof TvSeriesEpisodeGroups200Response
     */
    results?: Array<TvSeriesEpisodeGroups200ResponseResultsInner>;
    /**
     * 
     * @type {number}
     * @memberof TvSeriesEpisodeGroups200Response
     */
    id?: number;
}

/**
 * Check if a given object implements the TvSeriesEpisodeGroups200Response interface.
 */
export function instanceOfTvSeriesEpisodeGroups200Response(value: object): value is TvSeriesEpisodeGroups200Response {
    return true;
}

export function TvSeriesEpisodeGroups200ResponseFromJSON(json: any): TvSeriesEpisodeGroups200Response {
    return TvSeriesEpisodeGroups200ResponseFromJSONTyped(json, false);
}

export function TvSeriesEpisodeGroups200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeriesEpisodeGroups200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(TvSeriesEpisodeGroups200ResponseResultsInnerFromJSON)),
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function TvSeriesEpisodeGroups200ResponseToJSON(json: any): TvSeriesEpisodeGroups200Response {
    return TvSeriesEpisodeGroups200ResponseToJSONTyped(json, false);
}

export function TvSeriesEpisodeGroups200ResponseToJSONTyped(value?: TvSeriesEpisodeGroups200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(TvSeriesEpisodeGroups200ResponseResultsInnerToJSON)),
        'id': value['id'],
    };
}

