/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TvSeriesWatchProviders200ResponseResultsDZFlatrateInner } from './TvSeriesWatchProviders200ResponseResultsDZFlatrateInner';
import {
    TvSeriesWatchProviders200ResponseResultsDZFlatrateInnerFromJSON,
    TvSeriesWatchProviders200ResponseResultsDZFlatrateInnerFromJSONTyped,
    TvSeriesWatchProviders200ResponseResultsDZFlatrateInnerToJSON,
    TvSeriesWatchProviders200ResponseResultsDZFlatrateInnerToJSONTyped,
} from './TvSeriesWatchProviders200ResponseResultsDZFlatrateInner';

/**
 * 
 * @export
 * @interface TvSeasonWatchProviders200ResponseResultsLY
 */
export interface TvSeasonWatchProviders200ResponseResultsLY {
    /**
     * 
     * @type {string}
     * @memberof TvSeasonWatchProviders200ResponseResultsLY
     */
    link?: string;
    /**
     * 
     * @type {Array<TvSeriesWatchProviders200ResponseResultsDZFlatrateInner>}
     * @memberof TvSeasonWatchProviders200ResponseResultsLY
     */
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsDZFlatrateInner>;
}

/**
 * Check if a given object implements the TvSeasonWatchProviders200ResponseResultsLY interface.
 */
export function instanceOfTvSeasonWatchProviders200ResponseResultsLY(value: object): value is TvSeasonWatchProviders200ResponseResultsLY {
    return true;
}

export function TvSeasonWatchProviders200ResponseResultsLYFromJSON(json: any): TvSeasonWatchProviders200ResponseResultsLY {
    return TvSeasonWatchProviders200ResponseResultsLYFromJSONTyped(json, false);
}

export function TvSeasonWatchProviders200ResponseResultsLYFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeasonWatchProviders200ResponseResultsLY {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'] == null ? undefined : json['link'],
        'flatrate': json['flatrate'] == null ? undefined : ((json['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsDZFlatrateInnerFromJSON)),
    };
}

export function TvSeasonWatchProviders200ResponseResultsLYToJSON(json: any): TvSeasonWatchProviders200ResponseResultsLY {
    return TvSeasonWatchProviders200ResponseResultsLYToJSONTyped(json, false);
}

export function TvSeasonWatchProviders200ResponseResultsLYToJSONTyped(value?: TvSeasonWatchProviders200ResponseResultsLY | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
        'flatrate': value['flatrate'] == null ? undefined : ((value['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsDZFlatrateInnerToJSON)),
    };
}

