/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TvSeriesWatchProviders200ResponseResultsRSFlatrateInner } from './TvSeriesWatchProviders200ResponseResultsRSFlatrateInner';
import {
    TvSeriesWatchProviders200ResponseResultsRSFlatrateInnerFromJSON,
    TvSeriesWatchProviders200ResponseResultsRSFlatrateInnerFromJSONTyped,
    TvSeriesWatchProviders200ResponseResultsRSFlatrateInnerToJSON,
    TvSeriesWatchProviders200ResponseResultsRSFlatrateInnerToJSONTyped,
} from './TvSeriesWatchProviders200ResponseResultsRSFlatrateInner';

/**
 * 
 * @export
 * @interface TvSeasonWatchProviders200ResponseResultsRS
 */
export interface TvSeasonWatchProviders200ResponseResultsRS {
    /**
     * 
     * @type {string}
     * @memberof TvSeasonWatchProviders200ResponseResultsRS
     */
    link?: string;
    /**
     * 
     * @type {Array<TvSeriesWatchProviders200ResponseResultsRSFlatrateInner>}
     * @memberof TvSeasonWatchProviders200ResponseResultsRS
     */
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsRSFlatrateInner>;
}

/**
 * Check if a given object implements the TvSeasonWatchProviders200ResponseResultsRS interface.
 */
export function instanceOfTvSeasonWatchProviders200ResponseResultsRS(value: object): value is TvSeasonWatchProviders200ResponseResultsRS {
    return true;
}

export function TvSeasonWatchProviders200ResponseResultsRSFromJSON(json: any): TvSeasonWatchProviders200ResponseResultsRS {
    return TvSeasonWatchProviders200ResponseResultsRSFromJSONTyped(json, false);
}

export function TvSeasonWatchProviders200ResponseResultsRSFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeasonWatchProviders200ResponseResultsRS {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'] == null ? undefined : json['link'],
        'flatrate': json['flatrate'] == null ? undefined : ((json['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsRSFlatrateInnerFromJSON)),
    };
}

export function TvSeasonWatchProviders200ResponseResultsRSToJSON(json: any): TvSeasonWatchProviders200ResponseResultsRS {
    return TvSeasonWatchProviders200ResponseResultsRSToJSONTyped(json, false);
}

export function TvSeasonWatchProviders200ResponseResultsRSToJSONTyped(value?: TvSeasonWatchProviders200ResponseResultsRS | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
        'flatrate': value['flatrate'] == null ? undefined : ((value['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsRSFlatrateInnerToJSON)),
    };
}

