/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TvSeasonWatchProviders200ResponseResultsEGFlatrateInner
 */
export interface TvSeasonWatchProviders200ResponseResultsEGFlatrateInner {
    /**
     * 
     * @type {string}
     * @memberof TvSeasonWatchProviders200ResponseResultsEGFlatrateInner
     */
    logoPath?: string;
    /**
     * 
     * @type {number}
     * @memberof TvSeasonWatchProviders200ResponseResultsEGFlatrateInner
     */
    providerId?: number;
    /**
     * 
     * @type {string}
     * @memberof TvSeasonWatchProviders200ResponseResultsEGFlatrateInner
     */
    providerName?: string;
    /**
     * 
     * @type {number}
     * @memberof TvSeasonWatchProviders200ResponseResultsEGFlatrateInner
     */
    displayPriority?: number;
}

/**
 * Check if a given object implements the TvSeasonWatchProviders200ResponseResultsEGFlatrateInner interface.
 */
export function instanceOfTvSeasonWatchProviders200ResponseResultsEGFlatrateInner(value: object): value is TvSeasonWatchProviders200ResponseResultsEGFlatrateInner {
    return true;
}

export function TvSeasonWatchProviders200ResponseResultsEGFlatrateInnerFromJSON(json: any): TvSeasonWatchProviders200ResponseResultsEGFlatrateInner {
    return TvSeasonWatchProviders200ResponseResultsEGFlatrateInnerFromJSONTyped(json, false);
}

export function TvSeasonWatchProviders200ResponseResultsEGFlatrateInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeasonWatchProviders200ResponseResultsEGFlatrateInner {
    if (json == null) {
        return json;
    }
    return {
        
        'logoPath': json['logo_path'] == null ? undefined : json['logo_path'],
        'providerId': json['provider_id'] == null ? undefined : json['provider_id'],
        'providerName': json['provider_name'] == null ? undefined : json['provider_name'],
        'displayPriority': json['display_priority'] == null ? undefined : json['display_priority'],
    };
}

export function TvSeasonWatchProviders200ResponseResultsEGFlatrateInnerToJSON(json: any): TvSeasonWatchProviders200ResponseResultsEGFlatrateInner {
    return TvSeasonWatchProviders200ResponseResultsEGFlatrateInnerToJSONTyped(json, false);
}

export function TvSeasonWatchProviders200ResponseResultsEGFlatrateInnerToJSONTyped(value?: TvSeasonWatchProviders200ResponseResultsEGFlatrateInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'logo_path': value['logoPath'],
        'provider_id': value['providerId'],
        'provider_name': value['providerName'],
        'display_priority': value['displayPriority'],
    };
}

