/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TvSeriesChanges200ResponseChangesInnerItemsInnerValuePoster } from './TvSeriesChanges200ResponseChangesInnerItemsInnerValuePoster';
import {
    TvSeriesChanges200ResponseChangesInnerItemsInnerValuePosterFromJSON,
    TvSeriesChanges200ResponseChangesInnerItemsInnerValuePosterFromJSONTyped,
    TvSeriesChanges200ResponseChangesInnerItemsInnerValuePosterToJSON,
    TvSeriesChanges200ResponseChangesInnerItemsInnerValuePosterToJSONTyped,
} from './TvSeriesChanges200ResponseChangesInnerItemsInnerValuePoster';

/**
 * 
 * @export
 * @interface TvSeriesChanges200ResponseChangesInnerItemsInnerValue
 */
export interface TvSeriesChanges200ResponseChangesInnerItemsInnerValue {
    /**
     * 
     * @type {TvSeriesChanges200ResponseChangesInnerItemsInnerValuePoster}
     * @memberof TvSeriesChanges200ResponseChangesInnerItemsInnerValue
     */
    poster?: TvSeriesChanges200ResponseChangesInnerItemsInnerValuePoster;
}

/**
 * Check if a given object implements the TvSeriesChanges200ResponseChangesInnerItemsInnerValue interface.
 */
export function instanceOfTvSeriesChanges200ResponseChangesInnerItemsInnerValue(value: object): value is TvSeriesChanges200ResponseChangesInnerItemsInnerValue {
    return true;
}

export function TvSeriesChanges200ResponseChangesInnerItemsInnerValueFromJSON(json: any): TvSeriesChanges200ResponseChangesInnerItemsInnerValue {
    return TvSeriesChanges200ResponseChangesInnerItemsInnerValueFromJSONTyped(json, false);
}

export function TvSeriesChanges200ResponseChangesInnerItemsInnerValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeriesChanges200ResponseChangesInnerItemsInnerValue {
    if (json == null) {
        return json;
    }
    return {
        
        'poster': json['poster'] == null ? undefined : TvSeriesChanges200ResponseChangesInnerItemsInnerValuePosterFromJSON(json['poster']),
    };
}

export function TvSeriesChanges200ResponseChangesInnerItemsInnerValueToJSON(json: any): TvSeriesChanges200ResponseChangesInnerItemsInnerValue {
    return TvSeriesChanges200ResponseChangesInnerItemsInnerValueToJSONTyped(json, false);
}

export function TvSeriesChanges200ResponseChangesInnerItemsInnerValueToJSONTyped(value?: TvSeriesChanges200ResponseChangesInnerItemsInnerValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'poster': TvSeriesChanges200ResponseChangesInnerItemsInnerValuePosterToJSON(value['poster']),
    };
}

