/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TvSeasonCredits200ResponseCrewInner } from './TvSeasonCredits200ResponseCrewInner';
import {
    TvSeasonCredits200ResponseCrewInnerFromJSON,
    TvSeasonCredits200ResponseCrewInnerFromJSONTyped,
    TvSeasonCredits200ResponseCrewInnerToJSON,
    TvSeasonCredits200ResponseCrewInnerToJSONTyped,
} from './TvSeasonCredits200ResponseCrewInner';
import type { TvSeriesCredits200ResponseCastInner } from './TvSeriesCredits200ResponseCastInner';
import {
    TvSeriesCredits200ResponseCastInnerFromJSON,
    TvSeriesCredits200ResponseCastInnerFromJSONTyped,
    TvSeriesCredits200ResponseCastInnerToJSON,
    TvSeriesCredits200ResponseCastInnerToJSONTyped,
} from './TvSeriesCredits200ResponseCastInner';

/**
 * 
 * @export
 * @interface TvSeasonCredits200Response
 */
export interface TvSeasonCredits200Response {
    /**
     * 
     * @type {Array<TvSeriesCredits200ResponseCastInner>}
     * @memberof TvSeasonCredits200Response
     */
    cast?: Array<TvSeriesCredits200ResponseCastInner>;
    /**
     * 
     * @type {Array<TvSeasonCredits200ResponseCrewInner>}
     * @memberof TvSeasonCredits200Response
     */
    crew?: Array<TvSeasonCredits200ResponseCrewInner>;
    /**
     * 
     * @type {number}
     * @memberof TvSeasonCredits200Response
     */
    id?: number;
}

/**
 * Check if a given object implements the TvSeasonCredits200Response interface.
 */
export function instanceOfTvSeasonCredits200Response(value: object): value is TvSeasonCredits200Response {
    return true;
}

export function TvSeasonCredits200ResponseFromJSON(json: any): TvSeasonCredits200Response {
    return TvSeasonCredits200ResponseFromJSONTyped(json, false);
}

export function TvSeasonCredits200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeasonCredits200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'cast': json['cast'] == null ? undefined : ((json['cast'] as Array<any>).map(TvSeriesCredits200ResponseCastInnerFromJSON)),
        'crew': json['crew'] == null ? undefined : ((json['crew'] as Array<any>).map(TvSeasonCredits200ResponseCrewInnerFromJSON)),
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function TvSeasonCredits200ResponseToJSON(json: any): TvSeasonCredits200Response {
    return TvSeasonCredits200ResponseToJSONTyped(json, false);
}

export function TvSeasonCredits200ResponseToJSONTyped(value?: TvSeasonCredits200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cast': value['cast'] == null ? undefined : ((value['cast'] as Array<any>).map(TvSeriesCredits200ResponseCastInnerToJSON)),
        'crew': value['crew'] == null ? undefined : ((value['crew'] as Array<any>).map(TvSeasonCredits200ResponseCrewInnerToJSON)),
        'id': value['id'],
    };
}

