/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TvSeriesChanges200ResponseChangesInnerItemsInnerValue } from './TvSeriesChanges200ResponseChangesInnerItemsInnerValue';
import {
    TvSeriesChanges200ResponseChangesInnerItemsInnerValueFromJSON,
    TvSeriesChanges200ResponseChangesInnerItemsInnerValueFromJSONTyped,
    TvSeriesChanges200ResponseChangesInnerItemsInnerValueToJSON,
    TvSeriesChanges200ResponseChangesInnerItemsInnerValueToJSONTyped,
} from './TvSeriesChanges200ResponseChangesInnerItemsInnerValue';
import type { TvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValue } from './TvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValue';
import {
    TvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValueFromJSON,
    TvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValueFromJSONTyped,
    TvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValueToJSON,
    TvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValueToJSONTyped,
} from './TvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValue';

/**
 * 
 * @export
 * @interface TvSeriesChanges200ResponseChangesInnerItemsInner
 */
export interface TvSeriesChanges200ResponseChangesInnerItemsInner {
    /**
     * 
     * @type {string}
     * @memberof TvSeriesChanges200ResponseChangesInnerItemsInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesChanges200ResponseChangesInnerItemsInner
     */
    action?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesChanges200ResponseChangesInnerItemsInner
     */
    time?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesChanges200ResponseChangesInnerItemsInner
     */
    iso6391?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesChanges200ResponseChangesInnerItemsInner
     */
    iso31661?: string;
    /**
     * 
     * @type {TvSeriesChanges200ResponseChangesInnerItemsInnerValue}
     * @memberof TvSeriesChanges200ResponseChangesInnerItemsInner
     */
    value?: TvSeriesChanges200ResponseChangesInnerItemsInnerValue;
    /**
     * 
     * @type {TvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValue}
     * @memberof TvSeriesChanges200ResponseChangesInnerItemsInner
     */
    originalValue?: TvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValue;
}

/**
 * Check if a given object implements the TvSeriesChanges200ResponseChangesInnerItemsInner interface.
 */
export function instanceOfTvSeriesChanges200ResponseChangesInnerItemsInner(value: object): value is TvSeriesChanges200ResponseChangesInnerItemsInner {
    return true;
}

export function TvSeriesChanges200ResponseChangesInnerItemsInnerFromJSON(json: any): TvSeriesChanges200ResponseChangesInnerItemsInner {
    return TvSeriesChanges200ResponseChangesInnerItemsInnerFromJSONTyped(json, false);
}

export function TvSeriesChanges200ResponseChangesInnerItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeriesChanges200ResponseChangesInnerItemsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'action': json['action'] == null ? undefined : json['action'],
        'time': json['time'] == null ? undefined : json['time'],
        'iso6391': json['iso_639_1'] == null ? undefined : json['iso_639_1'],
        'iso31661': json['iso_3166_1'] == null ? undefined : json['iso_3166_1'],
        'value': json['value'] == null ? undefined : TvSeriesChanges200ResponseChangesInnerItemsInnerValueFromJSON(json['value']),
        'originalValue': json['original_value'] == null ? undefined : TvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValueFromJSON(json['original_value']),
    };
}

export function TvSeriesChanges200ResponseChangesInnerItemsInnerToJSON(json: any): TvSeriesChanges200ResponseChangesInnerItemsInner {
    return TvSeriesChanges200ResponseChangesInnerItemsInnerToJSONTyped(json, false);
}

export function TvSeriesChanges200ResponseChangesInnerItemsInnerToJSONTyped(value?: TvSeriesChanges200ResponseChangesInnerItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'action': value['action'],
        'time': value['time'],
        'iso_639_1': value['iso6391'],
        'iso_3166_1': value['iso31661'],
        'value': TvSeriesChanges200ResponseChangesInnerItemsInnerValueToJSON(value['value']),
        'original_value': TvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValueToJSON(value['originalValue']),
    };
}

