/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TvSeriesWatchProviders200ResponseResultsCRFlatrateInner } from './TvSeriesWatchProviders200ResponseResultsCRFlatrateInner';
import {
    TvSeriesWatchProviders200ResponseResultsCRFlatrateInnerFromJSON,
    TvSeriesWatchProviders200ResponseResultsCRFlatrateInnerFromJSONTyped,
    TvSeriesWatchProviders200ResponseResultsCRFlatrateInnerToJSON,
    TvSeriesWatchProviders200ResponseResultsCRFlatrateInnerToJSONTyped,
} from './TvSeriesWatchProviders200ResponseResultsCRFlatrateInner';

/**
 * 
 * @export
 * @interface TvSeriesWatchProviders200ResponseResultsHN
 */
export interface TvSeriesWatchProviders200ResponseResultsHN {
    /**
     * 
     * @type {string}
     * @memberof TvSeriesWatchProviders200ResponseResultsHN
     */
    link?: string;
    /**
     * 
     * @type {Array<TvSeriesWatchProviders200ResponseResultsCRFlatrateInner>}
     * @memberof TvSeriesWatchProviders200ResponseResultsHN
     */
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsCRFlatrateInner>;
}

/**
 * Check if a given object implements the TvSeriesWatchProviders200ResponseResultsHN interface.
 */
export function instanceOfTvSeriesWatchProviders200ResponseResultsHN(value: object): value is TvSeriesWatchProviders200ResponseResultsHN {
    return true;
}

export function TvSeriesWatchProviders200ResponseResultsHNFromJSON(json: any): TvSeriesWatchProviders200ResponseResultsHN {
    return TvSeriesWatchProviders200ResponseResultsHNFromJSONTyped(json, false);
}

export function TvSeriesWatchProviders200ResponseResultsHNFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeriesWatchProviders200ResponseResultsHN {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'] == null ? undefined : json['link'],
        'flatrate': json['flatrate'] == null ? undefined : ((json['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsCRFlatrateInnerFromJSON)),
    };
}

export function TvSeriesWatchProviders200ResponseResultsHNToJSON(json: any): TvSeriesWatchProviders200ResponseResultsHN {
    return TvSeriesWatchProviders200ResponseResultsHNToJSONTyped(json, false);
}

export function TvSeriesWatchProviders200ResponseResultsHNToJSONTyped(value?: TvSeriesWatchProviders200ResponseResultsHN | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
        'flatrate': value['flatrate'] == null ? undefined : ((value['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsCRFlatrateInnerToJSON)),
    };
}

