/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MovieWatchProviders200ResponseResultsAUBuyInner } from './MovieWatchProviders200ResponseResultsAUBuyInner';
import {
    MovieWatchProviders200ResponseResultsAUBuyInnerFromJSON,
    MovieWatchProviders200ResponseResultsAUBuyInnerFromJSONTyped,
    MovieWatchProviders200ResponseResultsAUBuyInnerToJSON,
    MovieWatchProviders200ResponseResultsAUBuyInnerToJSONTyped,
} from './MovieWatchProviders200ResponseResultsAUBuyInner';
import type { TvSeriesWatchProviders200ResponseResultsAUFlatrateInner } from './TvSeriesWatchProviders200ResponseResultsAUFlatrateInner';
import {
    TvSeriesWatchProviders200ResponseResultsAUFlatrateInnerFromJSON,
    TvSeriesWatchProviders200ResponseResultsAUFlatrateInnerFromJSONTyped,
    TvSeriesWatchProviders200ResponseResultsAUFlatrateInnerToJSON,
    TvSeriesWatchProviders200ResponseResultsAUFlatrateInnerToJSONTyped,
} from './TvSeriesWatchProviders200ResponseResultsAUFlatrateInner';

/**
 * 
 * @export
 * @interface TvSeriesWatchProviders200ResponseResultsAU
 */
export interface TvSeriesWatchProviders200ResponseResultsAU {
    /**
     * 
     * @type {string}
     * @memberof TvSeriesWatchProviders200ResponseResultsAU
     */
    link?: string;
    /**
     * 
     * @type {Array<TvSeriesWatchProviders200ResponseResultsAUFlatrateInner>}
     * @memberof TvSeriesWatchProviders200ResponseResultsAU
     */
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsAUFlatrateInner>;
    /**
     * 
     * @type {Array<MovieWatchProviders200ResponseResultsAUBuyInner>}
     * @memberof TvSeriesWatchProviders200ResponseResultsAU
     */
    buy?: Array<MovieWatchProviders200ResponseResultsAUBuyInner>;
}

/**
 * Check if a given object implements the TvSeriesWatchProviders200ResponseResultsAU interface.
 */
export function instanceOfTvSeriesWatchProviders200ResponseResultsAU(value: object): value is TvSeriesWatchProviders200ResponseResultsAU {
    return true;
}

export function TvSeriesWatchProviders200ResponseResultsAUFromJSON(json: any): TvSeriesWatchProviders200ResponseResultsAU {
    return TvSeriesWatchProviders200ResponseResultsAUFromJSONTyped(json, false);
}

export function TvSeriesWatchProviders200ResponseResultsAUFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeriesWatchProviders200ResponseResultsAU {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'] == null ? undefined : json['link'],
        'flatrate': json['flatrate'] == null ? undefined : ((json['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsAUFlatrateInnerFromJSON)),
        'buy': json['buy'] == null ? undefined : ((json['buy'] as Array<any>).map(MovieWatchProviders200ResponseResultsAUBuyInnerFromJSON)),
    };
}

export function TvSeriesWatchProviders200ResponseResultsAUToJSON(json: any): TvSeriesWatchProviders200ResponseResultsAU {
    return TvSeriesWatchProviders200ResponseResultsAUToJSONTyped(json, false);
}

export function TvSeriesWatchProviders200ResponseResultsAUToJSONTyped(value?: TvSeriesWatchProviders200ResponseResultsAU | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
        'flatrate': value['flatrate'] == null ? undefined : ((value['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsAUFlatrateInnerToJSON)),
        'buy': value['buy'] == null ? undefined : ((value['buy'] as Array<any>).map(MovieWatchProviders200ResponseResultsAUBuyInnerToJSON)),
    };
}

