/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TvSeasonTranslations200ResponseTranslationsInnerData } from './TvSeasonTranslations200ResponseTranslationsInnerData';
import {
    TvSeasonTranslations200ResponseTranslationsInnerDataFromJSON,
    TvSeasonTranslations200ResponseTranslationsInnerDataFromJSONTyped,
    TvSeasonTranslations200ResponseTranslationsInnerDataToJSON,
    TvSeasonTranslations200ResponseTranslationsInnerDataToJSONTyped,
} from './TvSeasonTranslations200ResponseTranslationsInnerData';

/**
 * 
 * @export
 * @interface TvSeasonTranslations200ResponseTranslationsInner
 */
export interface TvSeasonTranslations200ResponseTranslationsInner {
    /**
     * 
     * @type {string}
     * @memberof TvSeasonTranslations200ResponseTranslationsInner
     */
    iso31661?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeasonTranslations200ResponseTranslationsInner
     */
    iso6391?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeasonTranslations200ResponseTranslationsInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeasonTranslations200ResponseTranslationsInner
     */
    englishName?: string;
    /**
     * 
     * @type {TvSeasonTranslations200ResponseTranslationsInnerData}
     * @memberof TvSeasonTranslations200ResponseTranslationsInner
     */
    data?: TvSeasonTranslations200ResponseTranslationsInnerData;
}

/**
 * Check if a given object implements the TvSeasonTranslations200ResponseTranslationsInner interface.
 */
export function instanceOfTvSeasonTranslations200ResponseTranslationsInner(value: object): value is TvSeasonTranslations200ResponseTranslationsInner {
    return true;
}

export function TvSeasonTranslations200ResponseTranslationsInnerFromJSON(json: any): TvSeasonTranslations200ResponseTranslationsInner {
    return TvSeasonTranslations200ResponseTranslationsInnerFromJSONTyped(json, false);
}

export function TvSeasonTranslations200ResponseTranslationsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeasonTranslations200ResponseTranslationsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'iso31661': json['iso_3166_1'] == null ? undefined : json['iso_3166_1'],
        'iso6391': json['iso_639_1'] == null ? undefined : json['iso_639_1'],
        'name': json['name'] == null ? undefined : json['name'],
        'englishName': json['english_name'] == null ? undefined : json['english_name'],
        'data': json['data'] == null ? undefined : TvSeasonTranslations200ResponseTranslationsInnerDataFromJSON(json['data']),
    };
}

export function TvSeasonTranslations200ResponseTranslationsInnerToJSON(json: any): TvSeasonTranslations200ResponseTranslationsInner {
    return TvSeasonTranslations200ResponseTranslationsInnerToJSONTyped(json, false);
}

export function TvSeasonTranslations200ResponseTranslationsInnerToJSONTyped(value?: TvSeasonTranslations200ResponseTranslationsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'iso_3166_1': value['iso31661'],
        'iso_639_1': value['iso6391'],
        'name': value['name'],
        'english_name': value['englishName'],
        'data': TvSeasonTranslations200ResponseTranslationsInnerDataToJSON(value['data']),
    };
}

