/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TvSeasonDetails200ResponseEpisodesInnerGuestStarsInner
 */
export interface TvSeasonDetails200ResponseEpisodesInnerGuestStarsInner {
    /**
     * 
     * @type {string}
     * @memberof TvSeasonDetails200ResponseEpisodesInnerGuestStarsInner
     */
    character?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeasonDetails200ResponseEpisodesInnerGuestStarsInner
     */
    creditId?: string;
    /**
     * 
     * @type {number}
     * @memberof TvSeasonDetails200ResponseEpisodesInnerGuestStarsInner
     */
    order?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TvSeasonDetails200ResponseEpisodesInnerGuestStarsInner
     */
    adult?: boolean;
    /**
     * 
     * @type {number}
     * @memberof TvSeasonDetails200ResponseEpisodesInnerGuestStarsInner
     */
    gender?: number;
    /**
     * 
     * @type {number}
     * @memberof TvSeasonDetails200ResponseEpisodesInnerGuestStarsInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TvSeasonDetails200ResponseEpisodesInnerGuestStarsInner
     */
    knownForDepartment?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeasonDetails200ResponseEpisodesInnerGuestStarsInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeasonDetails200ResponseEpisodesInnerGuestStarsInner
     */
    originalName?: string;
    /**
     * 
     * @type {number}
     * @memberof TvSeasonDetails200ResponseEpisodesInnerGuestStarsInner
     */
    popularity?: number;
    /**
     * 
     * @type {string}
     * @memberof TvSeasonDetails200ResponseEpisodesInnerGuestStarsInner
     */
    profilePath?: string;
}

/**
 * Check if a given object implements the TvSeasonDetails200ResponseEpisodesInnerGuestStarsInner interface.
 */
export function instanceOfTvSeasonDetails200ResponseEpisodesInnerGuestStarsInner(value: object): value is TvSeasonDetails200ResponseEpisodesInnerGuestStarsInner {
    return true;
}

export function TvSeasonDetails200ResponseEpisodesInnerGuestStarsInnerFromJSON(json: any): TvSeasonDetails200ResponseEpisodesInnerGuestStarsInner {
    return TvSeasonDetails200ResponseEpisodesInnerGuestStarsInnerFromJSONTyped(json, false);
}

export function TvSeasonDetails200ResponseEpisodesInnerGuestStarsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeasonDetails200ResponseEpisodesInnerGuestStarsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'character': json['character'] == null ? undefined : json['character'],
        'creditId': json['credit_id'] == null ? undefined : json['credit_id'],
        'order': json['order'] == null ? undefined : json['order'],
        'adult': json['adult'] == null ? undefined : json['adult'],
        'gender': json['gender'] == null ? undefined : json['gender'],
        'id': json['id'] == null ? undefined : json['id'],
        'knownForDepartment': json['known_for_department'] == null ? undefined : json['known_for_department'],
        'name': json['name'] == null ? undefined : json['name'],
        'originalName': json['original_name'] == null ? undefined : json['original_name'],
        'popularity': json['popularity'] == null ? undefined : json['popularity'],
        'profilePath': json['profile_path'] == null ? undefined : json['profile_path'],
    };
}

export function TvSeasonDetails200ResponseEpisodesInnerGuestStarsInnerToJSON(json: any): TvSeasonDetails200ResponseEpisodesInnerGuestStarsInner {
    return TvSeasonDetails200ResponseEpisodesInnerGuestStarsInnerToJSONTyped(json, false);
}

export function TvSeasonDetails200ResponseEpisodesInnerGuestStarsInnerToJSONTyped(value?: TvSeasonDetails200ResponseEpisodesInnerGuestStarsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'character': value['character'],
        'credit_id': value['creditId'],
        'order': value['order'],
        'adult': value['adult'],
        'gender': value['gender'],
        'id': value['id'],
        'known_for_department': value['knownForDepartment'],
        'name': value['name'],
        'original_name': value['originalName'],
        'popularity': value['popularity'],
        'profile_path': value['profilePath'],
    };
}

