/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TvSeriesWatchProviders200ResponseResultsNZFlatrateInner } from './TvSeriesWatchProviders200ResponseResultsNZFlatrateInner';
import {
    TvSeriesWatchProviders200ResponseResultsNZFlatrateInnerFromJSON,
    TvSeriesWatchProviders200ResponseResultsNZFlatrateInnerFromJSONTyped,
    TvSeriesWatchProviders200ResponseResultsNZFlatrateInnerToJSON,
    TvSeriesWatchProviders200ResponseResultsNZFlatrateInnerToJSONTyped,
} from './TvSeriesWatchProviders200ResponseResultsNZFlatrateInner';

/**
 * 
 * @export
 * @interface TvSeriesWatchProviders200ResponseResultsNZ
 */
export interface TvSeriesWatchProviders200ResponseResultsNZ {
    /**
     * 
     * @type {string}
     * @memberof TvSeriesWatchProviders200ResponseResultsNZ
     */
    link?: string;
    /**
     * 
     * @type {Array<TvSeriesWatchProviders200ResponseResultsNZFlatrateInner>}
     * @memberof TvSeriesWatchProviders200ResponseResultsNZ
     */
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsNZFlatrateInner>;
}

/**
 * Check if a given object implements the TvSeriesWatchProviders200ResponseResultsNZ interface.
 */
export function instanceOfTvSeriesWatchProviders200ResponseResultsNZ(value: object): value is TvSeriesWatchProviders200ResponseResultsNZ {
    return true;
}

export function TvSeriesWatchProviders200ResponseResultsNZFromJSON(json: any): TvSeriesWatchProviders200ResponseResultsNZ {
    return TvSeriesWatchProviders200ResponseResultsNZFromJSONTyped(json, false);
}

export function TvSeriesWatchProviders200ResponseResultsNZFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeriesWatchProviders200ResponseResultsNZ {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'] == null ? undefined : json['link'],
        'flatrate': json['flatrate'] == null ? undefined : ((json['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsNZFlatrateInnerFromJSON)),
    };
}

export function TvSeriesWatchProviders200ResponseResultsNZToJSON(json: any): TvSeriesWatchProviders200ResponseResultsNZ {
    return TvSeriesWatchProviders200ResponseResultsNZToJSONTyped(json, false);
}

export function TvSeriesWatchProviders200ResponseResultsNZToJSONTyped(value?: TvSeriesWatchProviders200ResponseResultsNZ | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
        'flatrate': value['flatrate'] == null ? undefined : ((value['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsNZFlatrateInnerToJSON)),
    };
}

