/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TvSeasonImages200ResponsePostersInner
 */
export interface TvSeasonImages200ResponsePostersInner {
    /**
     * 
     * @type {number}
     * @memberof TvSeasonImages200ResponsePostersInner
     */
    aspectRatio?: number;
    /**
     * 
     * @type {number}
     * @memberof TvSeasonImages200ResponsePostersInner
     */
    height?: number;
    /**
     * 
     * @type {string}
     * @memberof TvSeasonImages200ResponsePostersInner
     */
    iso6391?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeasonImages200ResponsePostersInner
     */
    filePath?: string;
    /**
     * 
     * @type {number}
     * @memberof TvSeasonImages200ResponsePostersInner
     */
    voteAverage?: number;
    /**
     * 
     * @type {number}
     * @memberof TvSeasonImages200ResponsePostersInner
     */
    voteCount?: number;
    /**
     * 
     * @type {number}
     * @memberof TvSeasonImages200ResponsePostersInner
     */
    width?: number;
}

/**
 * Check if a given object implements the TvSeasonImages200ResponsePostersInner interface.
 */
export function instanceOfTvSeasonImages200ResponsePostersInner(value: object): value is TvSeasonImages200ResponsePostersInner {
    return true;
}

export function TvSeasonImages200ResponsePostersInnerFromJSON(json: any): TvSeasonImages200ResponsePostersInner {
    return TvSeasonImages200ResponsePostersInnerFromJSONTyped(json, false);
}

export function TvSeasonImages200ResponsePostersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeasonImages200ResponsePostersInner {
    if (json == null) {
        return json;
    }
    return {
        
        'aspectRatio': json['aspect_ratio'] == null ? undefined : json['aspect_ratio'],
        'height': json['height'] == null ? undefined : json['height'],
        'iso6391': json['iso_639_1'] == null ? undefined : json['iso_639_1'],
        'filePath': json['file_path'] == null ? undefined : json['file_path'],
        'voteAverage': json['vote_average'] == null ? undefined : json['vote_average'],
        'voteCount': json['vote_count'] == null ? undefined : json['vote_count'],
        'width': json['width'] == null ? undefined : json['width'],
    };
}

export function TvSeasonImages200ResponsePostersInnerToJSON(json: any): TvSeasonImages200ResponsePostersInner {
    return TvSeasonImages200ResponsePostersInnerToJSONTyped(json, false);
}

export function TvSeasonImages200ResponsePostersInnerToJSONTyped(value?: TvSeasonImages200ResponsePostersInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'aspect_ratio': value['aspectRatio'],
        'height': value['height'],
        'iso_639_1': value['iso6391'],
        'file_path': value['filePath'],
        'vote_average': value['voteAverage'],
        'vote_count': value['voteCount'],
        'width': value['width'],
    };
}

