/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TvSeriesAggregateCredits200ResponseCastInnerRolesInner
 */
export interface TvSeriesAggregateCredits200ResponseCastInnerRolesInner {
    /**
     * 
     * @type {string}
     * @memberof TvSeriesAggregateCredits200ResponseCastInnerRolesInner
     */
    creditId?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesAggregateCredits200ResponseCastInnerRolesInner
     */
    character?: string;
    /**
     * 
     * @type {number}
     * @memberof TvSeriesAggregateCredits200ResponseCastInnerRolesInner
     */
    episodeCount?: number;
}

/**
 * Check if a given object implements the TvSeriesAggregateCredits200ResponseCastInnerRolesInner interface.
 */
export function instanceOfTvSeriesAggregateCredits200ResponseCastInnerRolesInner(value: object): value is TvSeriesAggregateCredits200ResponseCastInnerRolesInner {
    return true;
}

export function TvSeriesAggregateCredits200ResponseCastInnerRolesInnerFromJSON(json: any): TvSeriesAggregateCredits200ResponseCastInnerRolesInner {
    return TvSeriesAggregateCredits200ResponseCastInnerRolesInnerFromJSONTyped(json, false);
}

export function TvSeriesAggregateCredits200ResponseCastInnerRolesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeriesAggregateCredits200ResponseCastInnerRolesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'creditId': json['credit_id'] == null ? undefined : json['credit_id'],
        'character': json['character'] == null ? undefined : json['character'],
        'episodeCount': json['episode_count'] == null ? undefined : json['episode_count'],
    };
}

export function TvSeriesAggregateCredits200ResponseCastInnerRolesInnerToJSON(json: any): TvSeriesAggregateCredits200ResponseCastInnerRolesInner {
    return TvSeriesAggregateCredits200ResponseCastInnerRolesInnerToJSONTyped(json, false);
}

export function TvSeriesAggregateCredits200ResponseCastInnerRolesInnerToJSONTyped(value?: TvSeriesAggregateCredits200ResponseCastInnerRolesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'credit_id': value['creditId'],
        'character': value['character'],
        'episode_count': value['episodeCount'],
    };
}

