/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TvSeriesWatchProviders200ResponseResultsFIBuyInner } from './TvSeriesWatchProviders200ResponseResultsFIBuyInner';
import {
    TvSeriesWatchProviders200ResponseResultsFIBuyInnerFromJSON,
    TvSeriesWatchProviders200ResponseResultsFIBuyInnerFromJSONTyped,
    TvSeriesWatchProviders200ResponseResultsFIBuyInnerToJSON,
    TvSeriesWatchProviders200ResponseResultsFIBuyInnerToJSONTyped,
} from './TvSeriesWatchProviders200ResponseResultsFIBuyInner';
import type { TvSeriesWatchProviders200ResponseResultsNLFlatrateInner } from './TvSeriesWatchProviders200ResponseResultsNLFlatrateInner';
import {
    TvSeriesWatchProviders200ResponseResultsNLFlatrateInnerFromJSON,
    TvSeriesWatchProviders200ResponseResultsNLFlatrateInnerFromJSONTyped,
    TvSeriesWatchProviders200ResponseResultsNLFlatrateInnerToJSON,
    TvSeriesWatchProviders200ResponseResultsNLFlatrateInnerToJSONTyped,
} from './TvSeriesWatchProviders200ResponseResultsNLFlatrateInner';

/**
 * 
 * @export
 * @interface TvSeriesWatchProviders200ResponseResultsNL
 */
export interface TvSeriesWatchProviders200ResponseResultsNL {
    /**
     * 
     * @type {string}
     * @memberof TvSeriesWatchProviders200ResponseResultsNL
     */
    link?: string;
    /**
     * 
     * @type {Array<TvSeriesWatchProviders200ResponseResultsNLFlatrateInner>}
     * @memberof TvSeriesWatchProviders200ResponseResultsNL
     */
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsNLFlatrateInner>;
    /**
     * 
     * @type {Array<TvSeriesWatchProviders200ResponseResultsFIBuyInner>}
     * @memberof TvSeriesWatchProviders200ResponseResultsNL
     */
    buy?: Array<TvSeriesWatchProviders200ResponseResultsFIBuyInner>;
}

/**
 * Check if a given object implements the TvSeriesWatchProviders200ResponseResultsNL interface.
 */
export function instanceOfTvSeriesWatchProviders200ResponseResultsNL(value: object): value is TvSeriesWatchProviders200ResponseResultsNL {
    return true;
}

export function TvSeriesWatchProviders200ResponseResultsNLFromJSON(json: any): TvSeriesWatchProviders200ResponseResultsNL {
    return TvSeriesWatchProviders200ResponseResultsNLFromJSONTyped(json, false);
}

export function TvSeriesWatchProviders200ResponseResultsNLFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeriesWatchProviders200ResponseResultsNL {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'] == null ? undefined : json['link'],
        'flatrate': json['flatrate'] == null ? undefined : ((json['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsNLFlatrateInnerFromJSON)),
        'buy': json['buy'] == null ? undefined : ((json['buy'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsFIBuyInnerFromJSON)),
    };
}

export function TvSeriesWatchProviders200ResponseResultsNLToJSON(json: any): TvSeriesWatchProviders200ResponseResultsNL {
    return TvSeriesWatchProviders200ResponseResultsNLToJSONTyped(json, false);
}

export function TvSeriesWatchProviders200ResponseResultsNLToJSONTyped(value?: TvSeriesWatchProviders200ResponseResultsNL | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
        'flatrate': value['flatrate'] == null ? undefined : ((value['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsNLFlatrateInnerToJSON)),
        'buy': value['buy'] == null ? undefined : ((value['buy'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsFIBuyInnerToJSON)),
    };
}

