/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TvSeriesWatchProviders200ResponseResultsCOFlatrateInner } from './TvSeriesWatchProviders200ResponseResultsCOFlatrateInner';
import {
    TvSeriesWatchProviders200ResponseResultsCOFlatrateInnerFromJSON,
    TvSeriesWatchProviders200ResponseResultsCOFlatrateInnerFromJSONTyped,
    TvSeriesWatchProviders200ResponseResultsCOFlatrateInnerToJSON,
    TvSeriesWatchProviders200ResponseResultsCOFlatrateInnerToJSONTyped,
} from './TvSeriesWatchProviders200ResponseResultsCOFlatrateInner';

/**
 * 
 * @export
 * @interface TvSeriesWatchProviders200ResponseResultsCO
 */
export interface TvSeriesWatchProviders200ResponseResultsCO {
    /**
     * 
     * @type {string}
     * @memberof TvSeriesWatchProviders200ResponseResultsCO
     */
    link?: string;
    /**
     * 
     * @type {Array<TvSeriesWatchProviders200ResponseResultsCOFlatrateInner>}
     * @memberof TvSeriesWatchProviders200ResponseResultsCO
     */
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsCOFlatrateInner>;
}

/**
 * Check if a given object implements the TvSeriesWatchProviders200ResponseResultsCO interface.
 */
export function instanceOfTvSeriesWatchProviders200ResponseResultsCO(value: object): value is TvSeriesWatchProviders200ResponseResultsCO {
    return true;
}

export function TvSeriesWatchProviders200ResponseResultsCOFromJSON(json: any): TvSeriesWatchProviders200ResponseResultsCO {
    return TvSeriesWatchProviders200ResponseResultsCOFromJSONTyped(json, false);
}

export function TvSeriesWatchProviders200ResponseResultsCOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeriesWatchProviders200ResponseResultsCO {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'] == null ? undefined : json['link'],
        'flatrate': json['flatrate'] == null ? undefined : ((json['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsCOFlatrateInnerFromJSON)),
    };
}

export function TvSeriesWatchProviders200ResponseResultsCOToJSON(json: any): TvSeriesWatchProviders200ResponseResultsCO {
    return TvSeriesWatchProviders200ResponseResultsCOToJSONTyped(json, false);
}

export function TvSeriesWatchProviders200ResponseResultsCOToJSONTyped(value?: TvSeriesWatchProviders200ResponseResultsCO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
        'flatrate': value['flatrate'] == null ? undefined : ((value['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsCOFlatrateInnerToJSON)),
    };
}

