/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TvSeriesWatchProviders200ResponseResultsSKFlatrateInner } from './TvSeriesWatchProviders200ResponseResultsSKFlatrateInner';
import {
    TvSeriesWatchProviders200ResponseResultsSKFlatrateInnerFromJSON,
    TvSeriesWatchProviders200ResponseResultsSKFlatrateInnerFromJSONTyped,
    TvSeriesWatchProviders200ResponseResultsSKFlatrateInnerToJSON,
    TvSeriesWatchProviders200ResponseResultsSKFlatrateInnerToJSONTyped,
} from './TvSeriesWatchProviders200ResponseResultsSKFlatrateInner';

/**
 * 
 * @export
 * @interface TvSeriesWatchProviders200ResponseResultsSK
 */
export interface TvSeriesWatchProviders200ResponseResultsSK {
    /**
     * 
     * @type {string}
     * @memberof TvSeriesWatchProviders200ResponseResultsSK
     */
    link?: string;
    /**
     * 
     * @type {Array<TvSeriesWatchProviders200ResponseResultsSKFlatrateInner>}
     * @memberof TvSeriesWatchProviders200ResponseResultsSK
     */
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsSKFlatrateInner>;
}

/**
 * Check if a given object implements the TvSeriesWatchProviders200ResponseResultsSK interface.
 */
export function instanceOfTvSeriesWatchProviders200ResponseResultsSK(value: object): value is TvSeriesWatchProviders200ResponseResultsSK {
    return true;
}

export function TvSeriesWatchProviders200ResponseResultsSKFromJSON(json: any): TvSeriesWatchProviders200ResponseResultsSK {
    return TvSeriesWatchProviders200ResponseResultsSKFromJSONTyped(json, false);
}

export function TvSeriesWatchProviders200ResponseResultsSKFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeriesWatchProviders200ResponseResultsSK {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'] == null ? undefined : json['link'],
        'flatrate': json['flatrate'] == null ? undefined : ((json['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsSKFlatrateInnerFromJSON)),
    };
}

export function TvSeriesWatchProviders200ResponseResultsSKToJSON(json: any): TvSeriesWatchProviders200ResponseResultsSK {
    return TvSeriesWatchProviders200ResponseResultsSKToJSONTyped(json, false);
}

export function TvSeriesWatchProviders200ResponseResultsSKToJSONTyped(value?: TvSeriesWatchProviders200ResponseResultsSK | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
        'flatrate': value['flatrate'] == null ? undefined : ((value['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsSKFlatrateInnerToJSON)),
    };
}

