/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MovieWatchProviders200ResponseResultsBBFlatrateInner } from './MovieWatchProviders200ResponseResultsBBFlatrateInner';
import {
    MovieWatchProviders200ResponseResultsBBFlatrateInnerFromJSON,
    MovieWatchProviders200ResponseResultsBBFlatrateInnerFromJSONTyped,
    MovieWatchProviders200ResponseResultsBBFlatrateInnerToJSON,
    MovieWatchProviders200ResponseResultsBBFlatrateInnerToJSONTyped,
} from './MovieWatchProviders200ResponseResultsBBFlatrateInner';

/**
 * 
 * @export
 * @interface TvSeasonWatchProviders200ResponseResultsBS
 */
export interface TvSeasonWatchProviders200ResponseResultsBS {
    /**
     * 
     * @type {string}
     * @memberof TvSeasonWatchProviders200ResponseResultsBS
     */
    link?: string;
    /**
     * 
     * @type {Array<MovieWatchProviders200ResponseResultsBBFlatrateInner>}
     * @memberof TvSeasonWatchProviders200ResponseResultsBS
     */
    flatrate?: Array<MovieWatchProviders200ResponseResultsBBFlatrateInner>;
}

/**
 * Check if a given object implements the TvSeasonWatchProviders200ResponseResultsBS interface.
 */
export function instanceOfTvSeasonWatchProviders200ResponseResultsBS(value: object): value is TvSeasonWatchProviders200ResponseResultsBS {
    return true;
}

export function TvSeasonWatchProviders200ResponseResultsBSFromJSON(json: any): TvSeasonWatchProviders200ResponseResultsBS {
    return TvSeasonWatchProviders200ResponseResultsBSFromJSONTyped(json, false);
}

export function TvSeasonWatchProviders200ResponseResultsBSFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeasonWatchProviders200ResponseResultsBS {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'] == null ? undefined : json['link'],
        'flatrate': json['flatrate'] == null ? undefined : ((json['flatrate'] as Array<any>).map(MovieWatchProviders200ResponseResultsBBFlatrateInnerFromJSON)),
    };
}

export function TvSeasonWatchProviders200ResponseResultsBSToJSON(json: any): TvSeasonWatchProviders200ResponseResultsBS {
    return TvSeasonWatchProviders200ResponseResultsBSToJSONTyped(json, false);
}

export function TvSeasonWatchProviders200ResponseResultsBSToJSONTyped(value?: TvSeasonWatchProviders200ResponseResultsBS | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
        'flatrate': value['flatrate'] == null ? undefined : ((value['flatrate'] as Array<any>).map(MovieWatchProviders200ResponseResultsBBFlatrateInnerToJSON)),
    };
}

