/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TvSeriesWatchProviders200ResponseResultsHKFlatrateInner } from './TvSeriesWatchProviders200ResponseResultsHKFlatrateInner';
import {
    TvSeriesWatchProviders200ResponseResultsHKFlatrateInnerFromJSON,
    TvSeriesWatchProviders200ResponseResultsHKFlatrateInnerFromJSONTyped,
    TvSeriesWatchProviders200ResponseResultsHKFlatrateInnerToJSON,
    TvSeriesWatchProviders200ResponseResultsHKFlatrateInnerToJSONTyped,
} from './TvSeriesWatchProviders200ResponseResultsHKFlatrateInner';

/**
 * 
 * @export
 * @interface TvSeasonWatchProviders200ResponseResultsTW
 */
export interface TvSeasonWatchProviders200ResponseResultsTW {
    /**
     * 
     * @type {string}
     * @memberof TvSeasonWatchProviders200ResponseResultsTW
     */
    link?: string;
    /**
     * 
     * @type {Array<TvSeriesWatchProviders200ResponseResultsHKFlatrateInner>}
     * @memberof TvSeasonWatchProviders200ResponseResultsTW
     */
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsHKFlatrateInner>;
}

/**
 * Check if a given object implements the TvSeasonWatchProviders200ResponseResultsTW interface.
 */
export function instanceOfTvSeasonWatchProviders200ResponseResultsTW(value: object): value is TvSeasonWatchProviders200ResponseResultsTW {
    return true;
}

export function TvSeasonWatchProviders200ResponseResultsTWFromJSON(json: any): TvSeasonWatchProviders200ResponseResultsTW {
    return TvSeasonWatchProviders200ResponseResultsTWFromJSONTyped(json, false);
}

export function TvSeasonWatchProviders200ResponseResultsTWFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeasonWatchProviders200ResponseResultsTW {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'] == null ? undefined : json['link'],
        'flatrate': json['flatrate'] == null ? undefined : ((json['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsHKFlatrateInnerFromJSON)),
    };
}

export function TvSeasonWatchProviders200ResponseResultsTWToJSON(json: any): TvSeasonWatchProviders200ResponseResultsTW {
    return TvSeasonWatchProviders200ResponseResultsTWToJSONTyped(json, false);
}

export function TvSeasonWatchProviders200ResponseResultsTWToJSONTyped(value?: TvSeasonWatchProviders200ResponseResultsTW | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
        'flatrate': value['flatrate'] == null ? undefined : ((value['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsHKFlatrateInnerToJSON)),
    };
}

