/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TvSeriesChanges200ResponseChangesInnerItemsInner } from './TvSeriesChanges200ResponseChangesInnerItemsInner';
import {
    TvSeriesChanges200ResponseChangesInnerItemsInnerFromJSON,
    TvSeriesChanges200ResponseChangesInnerItemsInnerFromJSONTyped,
    TvSeriesChanges200ResponseChangesInnerItemsInnerToJSON,
    TvSeriesChanges200ResponseChangesInnerItemsInnerToJSONTyped,
} from './TvSeriesChanges200ResponseChangesInnerItemsInner';

/**
 * 
 * @export
 * @interface TvSeriesChanges200ResponseChangesInner
 */
export interface TvSeriesChanges200ResponseChangesInner {
    /**
     * 
     * @type {string}
     * @memberof TvSeriesChanges200ResponseChangesInner
     */
    key?: string;
    /**
     * 
     * @type {Array<TvSeriesChanges200ResponseChangesInnerItemsInner>}
     * @memberof TvSeriesChanges200ResponseChangesInner
     */
    items?: Array<TvSeriesChanges200ResponseChangesInnerItemsInner>;
}

/**
 * Check if a given object implements the TvSeriesChanges200ResponseChangesInner interface.
 */
export function instanceOfTvSeriesChanges200ResponseChangesInner(value: object): value is TvSeriesChanges200ResponseChangesInner {
    return true;
}

export function TvSeriesChanges200ResponseChangesInnerFromJSON(json: any): TvSeriesChanges200ResponseChangesInner {
    return TvSeriesChanges200ResponseChangesInnerFromJSONTyped(json, false);
}

export function TvSeriesChanges200ResponseChangesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeriesChanges200ResponseChangesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'] == null ? undefined : json['key'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(TvSeriesChanges200ResponseChangesInnerItemsInnerFromJSON)),
    };
}

export function TvSeriesChanges200ResponseChangesInnerToJSON(json: any): TvSeriesChanges200ResponseChangesInner {
    return TvSeriesChanges200ResponseChangesInnerToJSONTyped(json, false);
}

export function TvSeriesChanges200ResponseChangesInnerToJSONTyped(value?: TvSeriesChanges200ResponseChangesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(TvSeriesChanges200ResponseChangesInnerItemsInnerToJSON)),
    };
}

