/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TvSeriesDetails200ResponseNetworksInner } from './TvSeriesDetails200ResponseNetworksInner';
import {
    TvSeriesDetails200ResponseNetworksInnerFromJSON,
    TvSeriesDetails200ResponseNetworksInnerFromJSONTyped,
    TvSeriesDetails200ResponseNetworksInnerToJSON,
    TvSeriesDetails200ResponseNetworksInnerToJSONTyped,
} from './TvSeriesDetails200ResponseNetworksInner';

/**
 * 
 * @export
 * @interface TvSeriesEpisodeGroups200ResponseResultsInner
 */
export interface TvSeriesEpisodeGroups200ResponseResultsInner {
    /**
     * 
     * @type {string}
     * @memberof TvSeriesEpisodeGroups200ResponseResultsInner
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof TvSeriesEpisodeGroups200ResponseResultsInner
     */
    episodeCount?: number;
    /**
     * 
     * @type {number}
     * @memberof TvSeriesEpisodeGroups200ResponseResultsInner
     */
    groupCount?: number;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesEpisodeGroups200ResponseResultsInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesEpisodeGroups200ResponseResultsInner
     */
    name?: string;
    /**
     * 
     * @type {TvSeriesDetails200ResponseNetworksInner}
     * @memberof TvSeriesEpisodeGroups200ResponseResultsInner
     */
    network?: TvSeriesDetails200ResponseNetworksInner;
    /**
     * 
     * @type {number}
     * @memberof TvSeriesEpisodeGroups200ResponseResultsInner
     */
    type?: number;
}

/**
 * Check if a given object implements the TvSeriesEpisodeGroups200ResponseResultsInner interface.
 */
export function instanceOfTvSeriesEpisodeGroups200ResponseResultsInner(value: object): value is TvSeriesEpisodeGroups200ResponseResultsInner {
    return true;
}

export function TvSeriesEpisodeGroups200ResponseResultsInnerFromJSON(json: any): TvSeriesEpisodeGroups200ResponseResultsInner {
    return TvSeriesEpisodeGroups200ResponseResultsInnerFromJSONTyped(json, false);
}

export function TvSeriesEpisodeGroups200ResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeriesEpisodeGroups200ResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'episodeCount': json['episode_count'] == null ? undefined : json['episode_count'],
        'groupCount': json['group_count'] == null ? undefined : json['group_count'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'network': json['network'] == null ? undefined : TvSeriesDetails200ResponseNetworksInnerFromJSON(json['network']),
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function TvSeriesEpisodeGroups200ResponseResultsInnerToJSON(json: any): TvSeriesEpisodeGroups200ResponseResultsInner {
    return TvSeriesEpisodeGroups200ResponseResultsInnerToJSONTyped(json, false);
}

export function TvSeriesEpisodeGroups200ResponseResultsInnerToJSONTyped(value?: TvSeriesEpisodeGroups200ResponseResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'episode_count': value['episodeCount'],
        'group_count': value['groupCount'],
        'id': value['id'],
        'name': value['name'],
        'network': TvSeriesDetails200ResponseNetworksInnerToJSON(value['network']),
        'type': value['type'],
    };
}

