/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TvSeriesWatchProviders200ResponseResultsGHFlatrateInner } from './TvSeriesWatchProviders200ResponseResultsGHFlatrateInner';
import {
    TvSeriesWatchProviders200ResponseResultsGHFlatrateInnerFromJSON,
    TvSeriesWatchProviders200ResponseResultsGHFlatrateInnerFromJSONTyped,
    TvSeriesWatchProviders200ResponseResultsGHFlatrateInnerToJSON,
    TvSeriesWatchProviders200ResponseResultsGHFlatrateInnerToJSONTyped,
} from './TvSeriesWatchProviders200ResponseResultsGHFlatrateInner';

/**
 * 
 * @export
 * @interface TvSeriesWatchProviders200ResponseResultsSN
 */
export interface TvSeriesWatchProviders200ResponseResultsSN {
    /**
     * 
     * @type {string}
     * @memberof TvSeriesWatchProviders200ResponseResultsSN
     */
    link?: string;
    /**
     * 
     * @type {Array<TvSeriesWatchProviders200ResponseResultsGHFlatrateInner>}
     * @memberof TvSeriesWatchProviders200ResponseResultsSN
     */
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsGHFlatrateInner>;
}

/**
 * Check if a given object implements the TvSeriesWatchProviders200ResponseResultsSN interface.
 */
export function instanceOfTvSeriesWatchProviders200ResponseResultsSN(value: object): value is TvSeriesWatchProviders200ResponseResultsSN {
    return true;
}

export function TvSeriesWatchProviders200ResponseResultsSNFromJSON(json: any): TvSeriesWatchProviders200ResponseResultsSN {
    return TvSeriesWatchProviders200ResponseResultsSNFromJSONTyped(json, false);
}

export function TvSeriesWatchProviders200ResponseResultsSNFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeriesWatchProviders200ResponseResultsSN {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'] == null ? undefined : json['link'],
        'flatrate': json['flatrate'] == null ? undefined : ((json['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsGHFlatrateInnerFromJSON)),
    };
}

export function TvSeriesWatchProviders200ResponseResultsSNToJSON(json: any): TvSeriesWatchProviders200ResponseResultsSN {
    return TvSeriesWatchProviders200ResponseResultsSNToJSONTyped(json, false);
}

export function TvSeriesWatchProviders200ResponseResultsSNToJSONTyped(value?: TvSeriesWatchProviders200ResponseResultsSN | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
        'flatrate': value['flatrate'] == null ? undefined : ((value['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsGHFlatrateInnerToJSON)),
    };
}

