/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MovieWatchProviders200ResponseResultsBERentInner } from './MovieWatchProviders200ResponseResultsBERentInner';
import {
    MovieWatchProviders200ResponseResultsBERentInnerFromJSON,
    MovieWatchProviders200ResponseResultsBERentInnerFromJSONTyped,
    MovieWatchProviders200ResponseResultsBERentInnerToJSON,
    MovieWatchProviders200ResponseResultsBERentInnerToJSONTyped,
} from './MovieWatchProviders200ResponseResultsBERentInner';
import type { TvSeriesWatchProviders200ResponseResultsCAFlatrateInner } from './TvSeriesWatchProviders200ResponseResultsCAFlatrateInner';
import {
    TvSeriesWatchProviders200ResponseResultsCAFlatrateInnerFromJSON,
    TvSeriesWatchProviders200ResponseResultsCAFlatrateInnerFromJSONTyped,
    TvSeriesWatchProviders200ResponseResultsCAFlatrateInnerToJSON,
    TvSeriesWatchProviders200ResponseResultsCAFlatrateInnerToJSONTyped,
} from './TvSeriesWatchProviders200ResponseResultsCAFlatrateInner';

/**
 * 
 * @export
 * @interface TvSeriesWatchProviders200ResponseResultsCA
 */
export interface TvSeriesWatchProviders200ResponseResultsCA {
    /**
     * 
     * @type {string}
     * @memberof TvSeriesWatchProviders200ResponseResultsCA
     */
    link?: string;
    /**
     * 
     * @type {Array<MovieWatchProviders200ResponseResultsBERentInner>}
     * @memberof TvSeriesWatchProviders200ResponseResultsCA
     */
    buy?: Array<MovieWatchProviders200ResponseResultsBERentInner>;
    /**
     * 
     * @type {Array<TvSeriesWatchProviders200ResponseResultsCAFlatrateInner>}
     * @memberof TvSeriesWatchProviders200ResponseResultsCA
     */
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsCAFlatrateInner>;
}

/**
 * Check if a given object implements the TvSeriesWatchProviders200ResponseResultsCA interface.
 */
export function instanceOfTvSeriesWatchProviders200ResponseResultsCA(value: object): value is TvSeriesWatchProviders200ResponseResultsCA {
    return true;
}

export function TvSeriesWatchProviders200ResponseResultsCAFromJSON(json: any): TvSeriesWatchProviders200ResponseResultsCA {
    return TvSeriesWatchProviders200ResponseResultsCAFromJSONTyped(json, false);
}

export function TvSeriesWatchProviders200ResponseResultsCAFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeriesWatchProviders200ResponseResultsCA {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'] == null ? undefined : json['link'],
        'buy': json['buy'] == null ? undefined : ((json['buy'] as Array<any>).map(MovieWatchProviders200ResponseResultsBERentInnerFromJSON)),
        'flatrate': json['flatrate'] == null ? undefined : ((json['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsCAFlatrateInnerFromJSON)),
    };
}

export function TvSeriesWatchProviders200ResponseResultsCAToJSON(json: any): TvSeriesWatchProviders200ResponseResultsCA {
    return TvSeriesWatchProviders200ResponseResultsCAToJSONTyped(json, false);
}

export function TvSeriesWatchProviders200ResponseResultsCAToJSONTyped(value?: TvSeriesWatchProviders200ResponseResultsCA | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
        'buy': value['buy'] == null ? undefined : ((value['buy'] as Array<any>).map(MovieWatchProviders200ResponseResultsBERentInnerToJSON)),
        'flatrate': value['flatrate'] == null ? undefined : ((value['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsCAFlatrateInnerToJSON)),
    };
}

