/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TvSeriesReviews200ResponseResultsInnerAuthorDetails
 */
export interface TvSeriesReviews200ResponseResultsInnerAuthorDetails {
    /**
     * 
     * @type {string}
     * @memberof TvSeriesReviews200ResponseResultsInnerAuthorDetails
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesReviews200ResponseResultsInnerAuthorDetails
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesReviews200ResponseResultsInnerAuthorDetails
     */
    avatarPath?: string;
    /**
     * 
     * @type {number}
     * @memberof TvSeriesReviews200ResponseResultsInnerAuthorDetails
     */
    rating?: number;
}

/**
 * Check if a given object implements the TvSeriesReviews200ResponseResultsInnerAuthorDetails interface.
 */
export function instanceOfTvSeriesReviews200ResponseResultsInnerAuthorDetails(value: object): value is TvSeriesReviews200ResponseResultsInnerAuthorDetails {
    return true;
}

export function TvSeriesReviews200ResponseResultsInnerAuthorDetailsFromJSON(json: any): TvSeriesReviews200ResponseResultsInnerAuthorDetails {
    return TvSeriesReviews200ResponseResultsInnerAuthorDetailsFromJSONTyped(json, false);
}

export function TvSeriesReviews200ResponseResultsInnerAuthorDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeriesReviews200ResponseResultsInnerAuthorDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'username': json['username'] == null ? undefined : json['username'],
        'avatarPath': json['avatar_path'] == null ? undefined : json['avatar_path'],
        'rating': json['rating'] == null ? undefined : json['rating'],
    };
}

export function TvSeriesReviews200ResponseResultsInnerAuthorDetailsToJSON(json: any): TvSeriesReviews200ResponseResultsInnerAuthorDetails {
    return TvSeriesReviews200ResponseResultsInnerAuthorDetailsToJSONTyped(json, false);
}

export function TvSeriesReviews200ResponseResultsInnerAuthorDetailsToJSONTyped(value?: TvSeriesReviews200ResponseResultsInnerAuthorDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'username': value['username'],
        'avatar_path': value['avatarPath'],
        'rating': value['rating'],
    };
}

