/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TvSeriesWatchProviders200ResponseResultsMUFlatrateInner } from './TvSeriesWatchProviders200ResponseResultsMUFlatrateInner';
import {
    TvSeriesWatchProviders200ResponseResultsMUFlatrateInnerFromJSON,
    TvSeriesWatchProviders200ResponseResultsMUFlatrateInnerFromJSONTyped,
    TvSeriesWatchProviders200ResponseResultsMUFlatrateInnerToJSON,
    TvSeriesWatchProviders200ResponseResultsMUFlatrateInnerToJSONTyped,
} from './TvSeriesWatchProviders200ResponseResultsMUFlatrateInner';

/**
 * 
 * @export
 * @interface TvSeasonWatchProviders200ResponseResultsMU
 */
export interface TvSeasonWatchProviders200ResponseResultsMU {
    /**
     * 
     * @type {string}
     * @memberof TvSeasonWatchProviders200ResponseResultsMU
     */
    link?: string;
    /**
     * 
     * @type {Array<TvSeriesWatchProviders200ResponseResultsMUFlatrateInner>}
     * @memberof TvSeasonWatchProviders200ResponseResultsMU
     */
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsMUFlatrateInner>;
}

/**
 * Check if a given object implements the TvSeasonWatchProviders200ResponseResultsMU interface.
 */
export function instanceOfTvSeasonWatchProviders200ResponseResultsMU(value: object): value is TvSeasonWatchProviders200ResponseResultsMU {
    return true;
}

export function TvSeasonWatchProviders200ResponseResultsMUFromJSON(json: any): TvSeasonWatchProviders200ResponseResultsMU {
    return TvSeasonWatchProviders200ResponseResultsMUFromJSONTyped(json, false);
}

export function TvSeasonWatchProviders200ResponseResultsMUFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeasonWatchProviders200ResponseResultsMU {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'] == null ? undefined : json['link'],
        'flatrate': json['flatrate'] == null ? undefined : ((json['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsMUFlatrateInnerFromJSON)),
    };
}

export function TvSeasonWatchProviders200ResponseResultsMUToJSON(json: any): TvSeasonWatchProviders200ResponseResultsMU {
    return TvSeasonWatchProviders200ResponseResultsMUToJSONTyped(json, false);
}

export function TvSeasonWatchProviders200ResponseResultsMUToJSONTyped(value?: TvSeasonWatchProviders200ResponseResultsMU | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
        'flatrate': value['flatrate'] == null ? undefined : ((value['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsMUFlatrateInnerToJSON)),
    };
}

