/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TvSeriesWatchProviders200ResponseResultsSCFlatrateInner } from './TvSeriesWatchProviders200ResponseResultsSCFlatrateInner';
import {
    TvSeriesWatchProviders200ResponseResultsSCFlatrateInnerFromJSON,
    TvSeriesWatchProviders200ResponseResultsSCFlatrateInnerFromJSONTyped,
    TvSeriesWatchProviders200ResponseResultsSCFlatrateInnerToJSON,
    TvSeriesWatchProviders200ResponseResultsSCFlatrateInnerToJSONTyped,
} from './TvSeriesWatchProviders200ResponseResultsSCFlatrateInner';

/**
 * 
 * @export
 * @interface TvSeasonWatchProviders200ResponseResultsSC
 */
export interface TvSeasonWatchProviders200ResponseResultsSC {
    /**
     * 
     * @type {string}
     * @memberof TvSeasonWatchProviders200ResponseResultsSC
     */
    link?: string;
    /**
     * 
     * @type {Array<TvSeriesWatchProviders200ResponseResultsSCFlatrateInner>}
     * @memberof TvSeasonWatchProviders200ResponseResultsSC
     */
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsSCFlatrateInner>;
}

/**
 * Check if a given object implements the TvSeasonWatchProviders200ResponseResultsSC interface.
 */
export function instanceOfTvSeasonWatchProviders200ResponseResultsSC(value: object): value is TvSeasonWatchProviders200ResponseResultsSC {
    return true;
}

export function TvSeasonWatchProviders200ResponseResultsSCFromJSON(json: any): TvSeasonWatchProviders200ResponseResultsSC {
    return TvSeasonWatchProviders200ResponseResultsSCFromJSONTyped(json, false);
}

export function TvSeasonWatchProviders200ResponseResultsSCFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeasonWatchProviders200ResponseResultsSC {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'] == null ? undefined : json['link'],
        'flatrate': json['flatrate'] == null ? undefined : ((json['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsSCFlatrateInnerFromJSON)),
    };
}

export function TvSeasonWatchProviders200ResponseResultsSCToJSON(json: any): TvSeasonWatchProviders200ResponseResultsSC {
    return TvSeasonWatchProviders200ResponseResultsSCToJSONTyped(json, false);
}

export function TvSeasonWatchProviders200ResponseResultsSCToJSONTyped(value?: TvSeasonWatchProviders200ResponseResultsSC | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
        'flatrate': value['flatrate'] == null ? undefined : ((value['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsSCFlatrateInnerToJSON)),
    };
}

