/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TvSeriesWatchProviders200ResponseResultsRUFlatrateInner } from './TvSeriesWatchProviders200ResponseResultsRUFlatrateInner';
import {
    TvSeriesWatchProviders200ResponseResultsRUFlatrateInnerFromJSON,
    TvSeriesWatchProviders200ResponseResultsRUFlatrateInnerFromJSONTyped,
    TvSeriesWatchProviders200ResponseResultsRUFlatrateInnerToJSON,
    TvSeriesWatchProviders200ResponseResultsRUFlatrateInnerToJSONTyped,
} from './TvSeriesWatchProviders200ResponseResultsRUFlatrateInner';
import type { TvSeriesWatchProviders200ResponseResultsRUAdsInner } from './TvSeriesWatchProviders200ResponseResultsRUAdsInner';
import {
    TvSeriesWatchProviders200ResponseResultsRUAdsInnerFromJSON,
    TvSeriesWatchProviders200ResponseResultsRUAdsInnerFromJSONTyped,
    TvSeriesWatchProviders200ResponseResultsRUAdsInnerToJSON,
    TvSeriesWatchProviders200ResponseResultsRUAdsInnerToJSONTyped,
} from './TvSeriesWatchProviders200ResponseResultsRUAdsInner';

/**
 * 
 * @export
 * @interface TvSeriesWatchProviders200ResponseResultsRU
 */
export interface TvSeriesWatchProviders200ResponseResultsRU {
    /**
     * 
     * @type {string}
     * @memberof TvSeriesWatchProviders200ResponseResultsRU
     */
    link?: string;
    /**
     * 
     * @type {Array<TvSeriesWatchProviders200ResponseResultsRUFlatrateInner>}
     * @memberof TvSeriesWatchProviders200ResponseResultsRU
     */
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsRUFlatrateInner>;
    /**
     * 
     * @type {Array<TvSeriesWatchProviders200ResponseResultsRUAdsInner>}
     * @memberof TvSeriesWatchProviders200ResponseResultsRU
     */
    ads?: Array<TvSeriesWatchProviders200ResponseResultsRUAdsInner>;
}

/**
 * Check if a given object implements the TvSeriesWatchProviders200ResponseResultsRU interface.
 */
export function instanceOfTvSeriesWatchProviders200ResponseResultsRU(value: object): value is TvSeriesWatchProviders200ResponseResultsRU {
    return true;
}

export function TvSeriesWatchProviders200ResponseResultsRUFromJSON(json: any): TvSeriesWatchProviders200ResponseResultsRU {
    return TvSeriesWatchProviders200ResponseResultsRUFromJSONTyped(json, false);
}

export function TvSeriesWatchProviders200ResponseResultsRUFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeriesWatchProviders200ResponseResultsRU {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'] == null ? undefined : json['link'],
        'flatrate': json['flatrate'] == null ? undefined : ((json['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsRUFlatrateInnerFromJSON)),
        'ads': json['ads'] == null ? undefined : ((json['ads'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsRUAdsInnerFromJSON)),
    };
}

export function TvSeriesWatchProviders200ResponseResultsRUToJSON(json: any): TvSeriesWatchProviders200ResponseResultsRU {
    return TvSeriesWatchProviders200ResponseResultsRUToJSONTyped(json, false);
}

export function TvSeriesWatchProviders200ResponseResultsRUToJSONTyped(value?: TvSeriesWatchProviders200ResponseResultsRU | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
        'flatrate': value['flatrate'] == null ? undefined : ((value['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsRUFlatrateInnerToJSON)),
        'ads': value['ads'] == null ? undefined : ((value['ads'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsRUAdsInnerToJSON)),
    };
}

