/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TvSeriesWatchProviders200ResponseResultsBEFlatrateInner } from './TvSeriesWatchProviders200ResponseResultsBEFlatrateInner';
import {
    TvSeriesWatchProviders200ResponseResultsBEFlatrateInnerFromJSON,
    TvSeriesWatchProviders200ResponseResultsBEFlatrateInnerFromJSONTyped,
    TvSeriesWatchProviders200ResponseResultsBEFlatrateInnerToJSON,
    TvSeriesWatchProviders200ResponseResultsBEFlatrateInnerToJSONTyped,
} from './TvSeriesWatchProviders200ResponseResultsBEFlatrateInner';

/**
 * 
 * @export
 * @interface TvSeriesWatchProviders200ResponseResultsBE
 */
export interface TvSeriesWatchProviders200ResponseResultsBE {
    /**
     * 
     * @type {string}
     * @memberof TvSeriesWatchProviders200ResponseResultsBE
     */
    link?: string;
    /**
     * 
     * @type {Array<TvSeriesWatchProviders200ResponseResultsBEFlatrateInner>}
     * @memberof TvSeriesWatchProviders200ResponseResultsBE
     */
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsBEFlatrateInner>;
}

/**
 * Check if a given object implements the TvSeriesWatchProviders200ResponseResultsBE interface.
 */
export function instanceOfTvSeriesWatchProviders200ResponseResultsBE(value: object): value is TvSeriesWatchProviders200ResponseResultsBE {
    return true;
}

export function TvSeriesWatchProviders200ResponseResultsBEFromJSON(json: any): TvSeriesWatchProviders200ResponseResultsBE {
    return TvSeriesWatchProviders200ResponseResultsBEFromJSONTyped(json, false);
}

export function TvSeriesWatchProviders200ResponseResultsBEFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeriesWatchProviders200ResponseResultsBE {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'] == null ? undefined : json['link'],
        'flatrate': json['flatrate'] == null ? undefined : ((json['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsBEFlatrateInnerFromJSON)),
    };
}

export function TvSeriesWatchProviders200ResponseResultsBEToJSON(json: any): TvSeriesWatchProviders200ResponseResultsBE {
    return TvSeriesWatchProviders200ResponseResultsBEToJSONTyped(json, false);
}

export function TvSeriesWatchProviders200ResponseResultsBEToJSONTyped(value?: TvSeriesWatchProviders200ResponseResultsBE | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
        'flatrate': value['flatrate'] == null ? undefined : ((value['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsBEFlatrateInnerToJSON)),
    };
}

