/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TvSeriesWatchProviders200ResponseResultsILFlatrateInner } from './TvSeriesWatchProviders200ResponseResultsILFlatrateInner';
import {
    TvSeriesWatchProviders200ResponseResultsILFlatrateInnerFromJSON,
    TvSeriesWatchProviders200ResponseResultsILFlatrateInnerFromJSONTyped,
    TvSeriesWatchProviders200ResponseResultsILFlatrateInnerToJSON,
    TvSeriesWatchProviders200ResponseResultsILFlatrateInnerToJSONTyped,
} from './TvSeriesWatchProviders200ResponseResultsILFlatrateInner';

/**
 * 
 * @export
 * @interface TvSeriesWatchProviders200ResponseResultsIL
 */
export interface TvSeriesWatchProviders200ResponseResultsIL {
    /**
     * 
     * @type {string}
     * @memberof TvSeriesWatchProviders200ResponseResultsIL
     */
    link?: string;
    /**
     * 
     * @type {Array<TvSeriesWatchProviders200ResponseResultsILFlatrateInner>}
     * @memberof TvSeriesWatchProviders200ResponseResultsIL
     */
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsILFlatrateInner>;
}

/**
 * Check if a given object implements the TvSeriesWatchProviders200ResponseResultsIL interface.
 */
export function instanceOfTvSeriesWatchProviders200ResponseResultsIL(value: object): value is TvSeriesWatchProviders200ResponseResultsIL {
    return true;
}

export function TvSeriesWatchProviders200ResponseResultsILFromJSON(json: any): TvSeriesWatchProviders200ResponseResultsIL {
    return TvSeriesWatchProviders200ResponseResultsILFromJSONTyped(json, false);
}

export function TvSeriesWatchProviders200ResponseResultsILFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeriesWatchProviders200ResponseResultsIL {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'] == null ? undefined : json['link'],
        'flatrate': json['flatrate'] == null ? undefined : ((json['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsILFlatrateInnerFromJSON)),
    };
}

export function TvSeriesWatchProviders200ResponseResultsILToJSON(json: any): TvSeriesWatchProviders200ResponseResultsIL {
    return TvSeriesWatchProviders200ResponseResultsILToJSONTyped(json, false);
}

export function TvSeriesWatchProviders200ResponseResultsILToJSONTyped(value?: TvSeriesWatchProviders200ResponseResultsIL | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
        'flatrate': value['flatrate'] == null ? undefined : ((value['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsILFlatrateInnerToJSON)),
    };
}

