/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TvSeriesWatchProviders200ResponseResultsGHFlatrateInner } from './TvSeriesWatchProviders200ResponseResultsGHFlatrateInner';
import {
    TvSeriesWatchProviders200ResponseResultsGHFlatrateInnerFromJSON,
    TvSeriesWatchProviders200ResponseResultsGHFlatrateInnerFromJSONTyped,
    TvSeriesWatchProviders200ResponseResultsGHFlatrateInnerToJSON,
    TvSeriesWatchProviders200ResponseResultsGHFlatrateInnerToJSONTyped,
} from './TvSeriesWatchProviders200ResponseResultsGHFlatrateInner';

/**
 * 
 * @export
 * @interface TvSeasonWatchProviders200ResponseResultsGH
 */
export interface TvSeasonWatchProviders200ResponseResultsGH {
    /**
     * 
     * @type {string}
     * @memberof TvSeasonWatchProviders200ResponseResultsGH
     */
    link?: string;
    /**
     * 
     * @type {Array<TvSeriesWatchProviders200ResponseResultsGHFlatrateInner>}
     * @memberof TvSeasonWatchProviders200ResponseResultsGH
     */
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsGHFlatrateInner>;
}

/**
 * Check if a given object implements the TvSeasonWatchProviders200ResponseResultsGH interface.
 */
export function instanceOfTvSeasonWatchProviders200ResponseResultsGH(value: object): value is TvSeasonWatchProviders200ResponseResultsGH {
    return true;
}

export function TvSeasonWatchProviders200ResponseResultsGHFromJSON(json: any): TvSeasonWatchProviders200ResponseResultsGH {
    return TvSeasonWatchProviders200ResponseResultsGHFromJSONTyped(json, false);
}

export function TvSeasonWatchProviders200ResponseResultsGHFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeasonWatchProviders200ResponseResultsGH {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'] == null ? undefined : json['link'],
        'flatrate': json['flatrate'] == null ? undefined : ((json['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsGHFlatrateInnerFromJSON)),
    };
}

export function TvSeasonWatchProviders200ResponseResultsGHToJSON(json: any): TvSeasonWatchProviders200ResponseResultsGH {
    return TvSeasonWatchProviders200ResponseResultsGHToJSONTyped(json, false);
}

export function TvSeasonWatchProviders200ResponseResultsGHToJSONTyped(value?: TvSeasonWatchProviders200ResponseResultsGH | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
        'flatrate': value['flatrate'] == null ? undefined : ((value['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsGHFlatrateInnerToJSON)),
    };
}

