/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TvSeriesAggregateCredits200ResponseCastInnerRolesInner } from './TvSeriesAggregateCredits200ResponseCastInnerRolesInner';
import {
    TvSeriesAggregateCredits200ResponseCastInnerRolesInnerFromJSON,
    TvSeriesAggregateCredits200ResponseCastInnerRolesInnerFromJSONTyped,
    TvSeriesAggregateCredits200ResponseCastInnerRolesInnerToJSON,
    TvSeriesAggregateCredits200ResponseCastInnerRolesInnerToJSONTyped,
} from './TvSeriesAggregateCredits200ResponseCastInnerRolesInner';

/**
 * 
 * @export
 * @interface TvSeriesAggregateCredits200ResponseCastInner
 */
export interface TvSeriesAggregateCredits200ResponseCastInner {
    /**
     * 
     * @type {boolean}
     * @memberof TvSeriesAggregateCredits200ResponseCastInner
     */
    adult?: boolean;
    /**
     * 
     * @type {number}
     * @memberof TvSeriesAggregateCredits200ResponseCastInner
     */
    gender?: number;
    /**
     * 
     * @type {number}
     * @memberof TvSeriesAggregateCredits200ResponseCastInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesAggregateCredits200ResponseCastInner
     */
    knownForDepartment?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesAggregateCredits200ResponseCastInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesAggregateCredits200ResponseCastInner
     */
    originalName?: string;
    /**
     * 
     * @type {number}
     * @memberof TvSeriesAggregateCredits200ResponseCastInner
     */
    popularity?: number;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesAggregateCredits200ResponseCastInner
     */
    profilePath?: string;
    /**
     * 
     * @type {Array<TvSeriesAggregateCredits200ResponseCastInnerRolesInner>}
     * @memberof TvSeriesAggregateCredits200ResponseCastInner
     */
    roles?: Array<TvSeriesAggregateCredits200ResponseCastInnerRolesInner>;
    /**
     * 
     * @type {number}
     * @memberof TvSeriesAggregateCredits200ResponseCastInner
     */
    totalEpisodeCount?: number;
    /**
     * 
     * @type {number}
     * @memberof TvSeriesAggregateCredits200ResponseCastInner
     */
    order?: number;
}

/**
 * Check if a given object implements the TvSeriesAggregateCredits200ResponseCastInner interface.
 */
export function instanceOfTvSeriesAggregateCredits200ResponseCastInner(value: object): value is TvSeriesAggregateCredits200ResponseCastInner {
    return true;
}

export function TvSeriesAggregateCredits200ResponseCastInnerFromJSON(json: any): TvSeriesAggregateCredits200ResponseCastInner {
    return TvSeriesAggregateCredits200ResponseCastInnerFromJSONTyped(json, false);
}

export function TvSeriesAggregateCredits200ResponseCastInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeriesAggregateCredits200ResponseCastInner {
    if (json == null) {
        return json;
    }
    return {
        
        'adult': json['adult'] == null ? undefined : json['adult'],
        'gender': json['gender'] == null ? undefined : json['gender'],
        'id': json['id'] == null ? undefined : json['id'],
        'knownForDepartment': json['known_for_department'] == null ? undefined : json['known_for_department'],
        'name': json['name'] == null ? undefined : json['name'],
        'originalName': json['original_name'] == null ? undefined : json['original_name'],
        'popularity': json['popularity'] == null ? undefined : json['popularity'],
        'profilePath': json['profile_path'] == null ? undefined : json['profile_path'],
        'roles': json['roles'] == null ? undefined : ((json['roles'] as Array<any>).map(TvSeriesAggregateCredits200ResponseCastInnerRolesInnerFromJSON)),
        'totalEpisodeCount': json['total_episode_count'] == null ? undefined : json['total_episode_count'],
        'order': json['order'] == null ? undefined : json['order'],
    };
}

export function TvSeriesAggregateCredits200ResponseCastInnerToJSON(json: any): TvSeriesAggregateCredits200ResponseCastInner {
    return TvSeriesAggregateCredits200ResponseCastInnerToJSONTyped(json, false);
}

export function TvSeriesAggregateCredits200ResponseCastInnerToJSONTyped(value?: TvSeriesAggregateCredits200ResponseCastInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'adult': value['adult'],
        'gender': value['gender'],
        'id': value['id'],
        'known_for_department': value['knownForDepartment'],
        'name': value['name'],
        'original_name': value['originalName'],
        'popularity': value['popularity'],
        'profile_path': value['profilePath'],
        'roles': value['roles'] == null ? undefined : ((value['roles'] as Array<any>).map(TvSeriesAggregateCredits200ResponseCastInnerRolesInnerToJSON)),
        'total_episode_count': value['totalEpisodeCount'],
        'order': value['order'],
    };
}

