/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TvSeriesWatchProviders200ResponseResultsFIBuyInner } from './TvSeriesWatchProviders200ResponseResultsFIBuyInner';
import {
    TvSeriesWatchProviders200ResponseResultsFIBuyInnerFromJSON,
    TvSeriesWatchProviders200ResponseResultsFIBuyInnerFromJSONTyped,
    TvSeriesWatchProviders200ResponseResultsFIBuyInnerToJSON,
    TvSeriesWatchProviders200ResponseResultsFIBuyInnerToJSONTyped,
} from './TvSeriesWatchProviders200ResponseResultsFIBuyInner';
import type { TvSeriesWatchProviders200ResponseResultsCRFlatrateInner } from './TvSeriesWatchProviders200ResponseResultsCRFlatrateInner';
import {
    TvSeriesWatchProviders200ResponseResultsCRFlatrateInnerFromJSON,
    TvSeriesWatchProviders200ResponseResultsCRFlatrateInnerFromJSONTyped,
    TvSeriesWatchProviders200ResponseResultsCRFlatrateInnerToJSON,
    TvSeriesWatchProviders200ResponseResultsCRFlatrateInnerToJSONTyped,
} from './TvSeriesWatchProviders200ResponseResultsCRFlatrateInner';

/**
 * 
 * @export
 * @interface TvSeriesWatchProviders200ResponseResultsFI
 */
export interface TvSeriesWatchProviders200ResponseResultsFI {
    /**
     * 
     * @type {string}
     * @memberof TvSeriesWatchProviders200ResponseResultsFI
     */
    link?: string;
    /**
     * 
     * @type {Array<TvSeriesWatchProviders200ResponseResultsFIBuyInner>}
     * @memberof TvSeriesWatchProviders200ResponseResultsFI
     */
    buy?: Array<TvSeriesWatchProviders200ResponseResultsFIBuyInner>;
    /**
     * 
     * @type {Array<TvSeriesWatchProviders200ResponseResultsCRFlatrateInner>}
     * @memberof TvSeriesWatchProviders200ResponseResultsFI
     */
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsCRFlatrateInner>;
}

/**
 * Check if a given object implements the TvSeriesWatchProviders200ResponseResultsFI interface.
 */
export function instanceOfTvSeriesWatchProviders200ResponseResultsFI(value: object): value is TvSeriesWatchProviders200ResponseResultsFI {
    return true;
}

export function TvSeriesWatchProviders200ResponseResultsFIFromJSON(json: any): TvSeriesWatchProviders200ResponseResultsFI {
    return TvSeriesWatchProviders200ResponseResultsFIFromJSONTyped(json, false);
}

export function TvSeriesWatchProviders200ResponseResultsFIFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeriesWatchProviders200ResponseResultsFI {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'] == null ? undefined : json['link'],
        'buy': json['buy'] == null ? undefined : ((json['buy'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsFIBuyInnerFromJSON)),
        'flatrate': json['flatrate'] == null ? undefined : ((json['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsCRFlatrateInnerFromJSON)),
    };
}

export function TvSeriesWatchProviders200ResponseResultsFIToJSON(json: any): TvSeriesWatchProviders200ResponseResultsFI {
    return TvSeriesWatchProviders200ResponseResultsFIToJSONTyped(json, false);
}

export function TvSeriesWatchProviders200ResponseResultsFIToJSONTyped(value?: TvSeriesWatchProviders200ResponseResultsFI | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
        'buy': value['buy'] == null ? undefined : ((value['buy'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsFIBuyInnerToJSON)),
        'flatrate': value['flatrate'] == null ? undefined : ((value['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsCRFlatrateInnerToJSON)),
    };
}

