/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MovieWatchProviders200ResponseResultsMKFlatrateInner } from './MovieWatchProviders200ResponseResultsMKFlatrateInner';
import {
    MovieWatchProviders200ResponseResultsMKFlatrateInnerFromJSON,
    MovieWatchProviders200ResponseResultsMKFlatrateInnerFromJSONTyped,
    MovieWatchProviders200ResponseResultsMKFlatrateInnerToJSON,
    MovieWatchProviders200ResponseResultsMKFlatrateInnerToJSONTyped,
} from './MovieWatchProviders200ResponseResultsMKFlatrateInner';

/**
 * 
 * @export
 * @interface TvSeasonWatchProviders200ResponseResultsMK
 */
export interface TvSeasonWatchProviders200ResponseResultsMK {
    /**
     * 
     * @type {string}
     * @memberof TvSeasonWatchProviders200ResponseResultsMK
     */
    link?: string;
    /**
     * 
     * @type {Array<MovieWatchProviders200ResponseResultsMKFlatrateInner>}
     * @memberof TvSeasonWatchProviders200ResponseResultsMK
     */
    flatrate?: Array<MovieWatchProviders200ResponseResultsMKFlatrateInner>;
}

/**
 * Check if a given object implements the TvSeasonWatchProviders200ResponseResultsMK interface.
 */
export function instanceOfTvSeasonWatchProviders200ResponseResultsMK(value: object): value is TvSeasonWatchProviders200ResponseResultsMK {
    return true;
}

export function TvSeasonWatchProviders200ResponseResultsMKFromJSON(json: any): TvSeasonWatchProviders200ResponseResultsMK {
    return TvSeasonWatchProviders200ResponseResultsMKFromJSONTyped(json, false);
}

export function TvSeasonWatchProviders200ResponseResultsMKFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeasonWatchProviders200ResponseResultsMK {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'] == null ? undefined : json['link'],
        'flatrate': json['flatrate'] == null ? undefined : ((json['flatrate'] as Array<any>).map(MovieWatchProviders200ResponseResultsMKFlatrateInnerFromJSON)),
    };
}

export function TvSeasonWatchProviders200ResponseResultsMKToJSON(json: any): TvSeasonWatchProviders200ResponseResultsMK {
    return TvSeasonWatchProviders200ResponseResultsMKToJSONTyped(json, false);
}

export function TvSeasonWatchProviders200ResponseResultsMKToJSONTyped(value?: TvSeasonWatchProviders200ResponseResultsMK | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
        'flatrate': value['flatrate'] == null ? undefined : ((value['flatrate'] as Array<any>).map(MovieWatchProviders200ResponseResultsMKFlatrateInnerToJSON)),
    };
}

