/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TvSeriesWatchProviders200ResponseResultsCRFlatrateInner } from './TvSeriesWatchProviders200ResponseResultsCRFlatrateInner';
import {
    TvSeriesWatchProviders200ResponseResultsCRFlatrateInnerFromJSON,
    TvSeriesWatchProviders200ResponseResultsCRFlatrateInnerFromJSONTyped,
    TvSeriesWatchProviders200ResponseResultsCRFlatrateInnerToJSON,
    TvSeriesWatchProviders200ResponseResultsCRFlatrateInnerToJSONTyped,
} from './TvSeriesWatchProviders200ResponseResultsCRFlatrateInner';

/**
 * 
 * @export
 * @interface TvSeasonWatchProviders200ResponseResultsCR
 */
export interface TvSeasonWatchProviders200ResponseResultsCR {
    /**
     * 
     * @type {string}
     * @memberof TvSeasonWatchProviders200ResponseResultsCR
     */
    link?: string;
    /**
     * 
     * @type {Array<TvSeriesWatchProviders200ResponseResultsCRFlatrateInner>}
     * @memberof TvSeasonWatchProviders200ResponseResultsCR
     */
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsCRFlatrateInner>;
}

/**
 * Check if a given object implements the TvSeasonWatchProviders200ResponseResultsCR interface.
 */
export function instanceOfTvSeasonWatchProviders200ResponseResultsCR(value: object): value is TvSeasonWatchProviders200ResponseResultsCR {
    return true;
}

export function TvSeasonWatchProviders200ResponseResultsCRFromJSON(json: any): TvSeasonWatchProviders200ResponseResultsCR {
    return TvSeasonWatchProviders200ResponseResultsCRFromJSONTyped(json, false);
}

export function TvSeasonWatchProviders200ResponseResultsCRFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeasonWatchProviders200ResponseResultsCR {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'] == null ? undefined : json['link'],
        'flatrate': json['flatrate'] == null ? undefined : ((json['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsCRFlatrateInnerFromJSON)),
    };
}

export function TvSeasonWatchProviders200ResponseResultsCRToJSON(json: any): TvSeasonWatchProviders200ResponseResultsCR {
    return TvSeasonWatchProviders200ResponseResultsCRToJSONTyped(json, false);
}

export function TvSeasonWatchProviders200ResponseResultsCRToJSONTyped(value?: TvSeasonWatchProviders200ResponseResultsCR | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
        'flatrate': value['flatrate'] == null ? undefined : ((value['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsCRFlatrateInnerToJSON)),
    };
}

