/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TvSeriesWatchProviders200ResponseResultsJPBuyInner } from './TvSeriesWatchProviders200ResponseResultsJPBuyInner';
import {
    TvSeriesWatchProviders200ResponseResultsJPBuyInnerFromJSON,
    TvSeriesWatchProviders200ResponseResultsJPBuyInnerFromJSONTyped,
    TvSeriesWatchProviders200ResponseResultsJPBuyInnerToJSON,
    TvSeriesWatchProviders200ResponseResultsJPBuyInnerToJSONTyped,
} from './TvSeriesWatchProviders200ResponseResultsJPBuyInner';
import type { TvSeriesWatchProviders200ResponseResultsJPFlatrateInner } from './TvSeriesWatchProviders200ResponseResultsJPFlatrateInner';
import {
    TvSeriesWatchProviders200ResponseResultsJPFlatrateInnerFromJSON,
    TvSeriesWatchProviders200ResponseResultsJPFlatrateInnerFromJSONTyped,
    TvSeriesWatchProviders200ResponseResultsJPFlatrateInnerToJSON,
    TvSeriesWatchProviders200ResponseResultsJPFlatrateInnerToJSONTyped,
} from './TvSeriesWatchProviders200ResponseResultsJPFlatrateInner';

/**
 * 
 * @export
 * @interface TvSeasonWatchProviders200ResponseResultsJP
 */
export interface TvSeasonWatchProviders200ResponseResultsJP {
    /**
     * 
     * @type {string}
     * @memberof TvSeasonWatchProviders200ResponseResultsJP
     */
    link?: string;
    /**
     * 
     * @type {Array<TvSeriesWatchProviders200ResponseResultsJPBuyInner>}
     * @memberof TvSeasonWatchProviders200ResponseResultsJP
     */
    buy?: Array<TvSeriesWatchProviders200ResponseResultsJPBuyInner>;
    /**
     * 
     * @type {Array<TvSeriesWatchProviders200ResponseResultsJPFlatrateInner>}
     * @memberof TvSeasonWatchProviders200ResponseResultsJP
     */
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsJPFlatrateInner>;
    /**
     * 
     * @type {Array<TvSeriesWatchProviders200ResponseResultsJPBuyInner>}
     * @memberof TvSeasonWatchProviders200ResponseResultsJP
     */
    rent?: Array<TvSeriesWatchProviders200ResponseResultsJPBuyInner>;
}

/**
 * Check if a given object implements the TvSeasonWatchProviders200ResponseResultsJP interface.
 */
export function instanceOfTvSeasonWatchProviders200ResponseResultsJP(value: object): value is TvSeasonWatchProviders200ResponseResultsJP {
    return true;
}

export function TvSeasonWatchProviders200ResponseResultsJPFromJSON(json: any): TvSeasonWatchProviders200ResponseResultsJP {
    return TvSeasonWatchProviders200ResponseResultsJPFromJSONTyped(json, false);
}

export function TvSeasonWatchProviders200ResponseResultsJPFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeasonWatchProviders200ResponseResultsJP {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'] == null ? undefined : json['link'],
        'buy': json['buy'] == null ? undefined : ((json['buy'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsJPBuyInnerFromJSON)),
        'flatrate': json['flatrate'] == null ? undefined : ((json['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsJPFlatrateInnerFromJSON)),
        'rent': json['rent'] == null ? undefined : ((json['rent'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsJPBuyInnerFromJSON)),
    };
}

export function TvSeasonWatchProviders200ResponseResultsJPToJSON(json: any): TvSeasonWatchProviders200ResponseResultsJP {
    return TvSeasonWatchProviders200ResponseResultsJPToJSONTyped(json, false);
}

export function TvSeasonWatchProviders200ResponseResultsJPToJSONTyped(value?: TvSeasonWatchProviders200ResponseResultsJP | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
        'buy': value['buy'] == null ? undefined : ((value['buy'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsJPBuyInnerToJSON)),
        'flatrate': value['flatrate'] == null ? undefined : ((value['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsJPFlatrateInnerToJSON)),
        'rent': value['rent'] == null ? undefined : ((value['rent'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsJPBuyInnerToJSON)),
    };
}

