/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MovieWatchProviders200ResponseResultsMKFlatrateInner } from './MovieWatchProviders200ResponseResultsMKFlatrateInner';
import {
    MovieWatchProviders200ResponseResultsMKFlatrateInnerFromJSON,
    MovieWatchProviders200ResponseResultsMKFlatrateInnerFromJSONTyped,
    MovieWatchProviders200ResponseResultsMKFlatrateInnerToJSON,
    MovieWatchProviders200ResponseResultsMKFlatrateInnerToJSONTyped,
} from './MovieWatchProviders200ResponseResultsMKFlatrateInner';

/**
 * 
 * @export
 * @interface TvSeriesWatchProviders200ResponseResultsSI
 */
export interface TvSeriesWatchProviders200ResponseResultsSI {
    /**
     * 
     * @type {string}
     * @memberof TvSeriesWatchProviders200ResponseResultsSI
     */
    link?: string;
    /**
     * 
     * @type {Array<MovieWatchProviders200ResponseResultsMKFlatrateInner>}
     * @memberof TvSeriesWatchProviders200ResponseResultsSI
     */
    flatrate?: Array<MovieWatchProviders200ResponseResultsMKFlatrateInner>;
}

/**
 * Check if a given object implements the TvSeriesWatchProviders200ResponseResultsSI interface.
 */
export function instanceOfTvSeriesWatchProviders200ResponseResultsSI(value: object): value is TvSeriesWatchProviders200ResponseResultsSI {
    return true;
}

export function TvSeriesWatchProviders200ResponseResultsSIFromJSON(json: any): TvSeriesWatchProviders200ResponseResultsSI {
    return TvSeriesWatchProviders200ResponseResultsSIFromJSONTyped(json, false);
}

export function TvSeriesWatchProviders200ResponseResultsSIFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeriesWatchProviders200ResponseResultsSI {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'] == null ? undefined : json['link'],
        'flatrate': json['flatrate'] == null ? undefined : ((json['flatrate'] as Array<any>).map(MovieWatchProviders200ResponseResultsMKFlatrateInnerFromJSON)),
    };
}

export function TvSeriesWatchProviders200ResponseResultsSIToJSON(json: any): TvSeriesWatchProviders200ResponseResultsSI {
    return TvSeriesWatchProviders200ResponseResultsSIToJSONTyped(json, false);
}

export function TvSeriesWatchProviders200ResponseResultsSIToJSONTyped(value?: TvSeriesWatchProviders200ResponseResultsSI | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
        'flatrate': value['flatrate'] == null ? undefined : ((value['flatrate'] as Array<any>).map(MovieWatchProviders200ResponseResultsMKFlatrateInnerToJSON)),
    };
}

