/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TvSeriesWatchProviders200ResponseResultsHKFlatrateInner } from './TvSeriesWatchProviders200ResponseResultsHKFlatrateInner';
import {
    TvSeriesWatchProviders200ResponseResultsHKFlatrateInnerFromJSON,
    TvSeriesWatchProviders200ResponseResultsHKFlatrateInnerFromJSONTyped,
    TvSeriesWatchProviders200ResponseResultsHKFlatrateInnerToJSON,
    TvSeriesWatchProviders200ResponseResultsHKFlatrateInnerToJSONTyped,
} from './TvSeriesWatchProviders200ResponseResultsHKFlatrateInner';

/**
 * 
 * @export
 * @interface TvSeriesWatchProviders200ResponseResultsHK
 */
export interface TvSeriesWatchProviders200ResponseResultsHK {
    /**
     * 
     * @type {string}
     * @memberof TvSeriesWatchProviders200ResponseResultsHK
     */
    link?: string;
    /**
     * 
     * @type {Array<TvSeriesWatchProviders200ResponseResultsHKFlatrateInner>}
     * @memberof TvSeriesWatchProviders200ResponseResultsHK
     */
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsHKFlatrateInner>;
}

/**
 * Check if a given object implements the TvSeriesWatchProviders200ResponseResultsHK interface.
 */
export function instanceOfTvSeriesWatchProviders200ResponseResultsHK(value: object): value is TvSeriesWatchProviders200ResponseResultsHK {
    return true;
}

export function TvSeriesWatchProviders200ResponseResultsHKFromJSON(json: any): TvSeriesWatchProviders200ResponseResultsHK {
    return TvSeriesWatchProviders200ResponseResultsHKFromJSONTyped(json, false);
}

export function TvSeriesWatchProviders200ResponseResultsHKFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeriesWatchProviders200ResponseResultsHK {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'] == null ? undefined : json['link'],
        'flatrate': json['flatrate'] == null ? undefined : ((json['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsHKFlatrateInnerFromJSON)),
    };
}

export function TvSeriesWatchProviders200ResponseResultsHKToJSON(json: any): TvSeriesWatchProviders200ResponseResultsHK {
    return TvSeriesWatchProviders200ResponseResultsHKToJSONTyped(json, false);
}

export function TvSeriesWatchProviders200ResponseResultsHKToJSONTyped(value?: TvSeriesWatchProviders200ResponseResultsHK | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
        'flatrate': value['flatrate'] == null ? undefined : ((value['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsHKFlatrateInnerToJSON)),
    };
}

