/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TvSeriesDetails200ResponseProductionCountriesInner
 */
export interface TvSeriesDetails200ResponseProductionCountriesInner {
    /**
     * 
     * @type {string}
     * @memberof TvSeriesDetails200ResponseProductionCountriesInner
     */
    iso31661?: string;
    /**
     * 
     * @type {string}
     * @memberof TvSeriesDetails200ResponseProductionCountriesInner
     */
    name?: string;
}

/**
 * Check if a given object implements the TvSeriesDetails200ResponseProductionCountriesInner interface.
 */
export function instanceOfTvSeriesDetails200ResponseProductionCountriesInner(value: object): value is TvSeriesDetails200ResponseProductionCountriesInner {
    return true;
}

export function TvSeriesDetails200ResponseProductionCountriesInnerFromJSON(json: any): TvSeriesDetails200ResponseProductionCountriesInner {
    return TvSeriesDetails200ResponseProductionCountriesInnerFromJSONTyped(json, false);
}

export function TvSeriesDetails200ResponseProductionCountriesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeriesDetails200ResponseProductionCountriesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'iso31661': json['iso_3166_1'] == null ? undefined : json['iso_3166_1'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function TvSeriesDetails200ResponseProductionCountriesInnerToJSON(json: any): TvSeriesDetails200ResponseProductionCountriesInner {
    return TvSeriesDetails200ResponseProductionCountriesInnerToJSONTyped(json, false);
}

export function TvSeriesDetails200ResponseProductionCountriesInnerToJSONTyped(value?: TvSeriesDetails200ResponseProductionCountriesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'iso_3166_1': value['iso31661'],
        'name': value['name'],
    };
}

