/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TvSeasonChangesById200ResponseChangesInnerItemsInnerValue
 */
export interface TvSeasonChangesById200ResponseChangesInnerItemsInnerValue {
    /**
     * 
     * @type {number}
     * @memberof TvSeasonChangesById200ResponseChangesInnerItemsInnerValue
     */
    episodeId?: number;
    /**
     * 
     * @type {number}
     * @memberof TvSeasonChangesById200ResponseChangesInnerItemsInnerValue
     */
    episodeNumber?: number;
}

/**
 * Check if a given object implements the TvSeasonChangesById200ResponseChangesInnerItemsInnerValue interface.
 */
export function instanceOfTvSeasonChangesById200ResponseChangesInnerItemsInnerValue(value: object): value is TvSeasonChangesById200ResponseChangesInnerItemsInnerValue {
    return true;
}

export function TvSeasonChangesById200ResponseChangesInnerItemsInnerValueFromJSON(json: any): TvSeasonChangesById200ResponseChangesInnerItemsInnerValue {
    return TvSeasonChangesById200ResponseChangesInnerItemsInnerValueFromJSONTyped(json, false);
}

export function TvSeasonChangesById200ResponseChangesInnerItemsInnerValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeasonChangesById200ResponseChangesInnerItemsInnerValue {
    if (json == null) {
        return json;
    }
    return {
        
        'episodeId': json['episode_id'] == null ? undefined : json['episode_id'],
        'episodeNumber': json['episode_number'] == null ? undefined : json['episode_number'],
    };
}

export function TvSeasonChangesById200ResponseChangesInnerItemsInnerValueToJSON(json: any): TvSeasonChangesById200ResponseChangesInnerItemsInnerValue {
    return TvSeasonChangesById200ResponseChangesInnerItemsInnerValueToJSONTyped(json, false);
}

export function TvSeasonChangesById200ResponseChangesInnerItemsInnerValueToJSONTyped(value?: TvSeasonChangesById200ResponseChangesInnerItemsInnerValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'episode_id': value['episodeId'],
        'episode_number': value['episodeNumber'],
    };
}

