/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TvSeriesWatchProviders200ResponseResultsCZFlatrateInner } from './TvSeriesWatchProviders200ResponseResultsCZFlatrateInner';
import {
    TvSeriesWatchProviders200ResponseResultsCZFlatrateInnerFromJSON,
    TvSeriesWatchProviders200ResponseResultsCZFlatrateInnerFromJSONTyped,
    TvSeriesWatchProviders200ResponseResultsCZFlatrateInnerToJSON,
    TvSeriesWatchProviders200ResponseResultsCZFlatrateInnerToJSONTyped,
} from './TvSeriesWatchProviders200ResponseResultsCZFlatrateInner';

/**
 * 
 * @export
 * @interface TvSeriesWatchProviders200ResponseResultsCZ
 */
export interface TvSeriesWatchProviders200ResponseResultsCZ {
    /**
     * 
     * @type {string}
     * @memberof TvSeriesWatchProviders200ResponseResultsCZ
     */
    link?: string;
    /**
     * 
     * @type {Array<TvSeriesWatchProviders200ResponseResultsCZFlatrateInner>}
     * @memberof TvSeriesWatchProviders200ResponseResultsCZ
     */
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsCZFlatrateInner>;
}

/**
 * Check if a given object implements the TvSeriesWatchProviders200ResponseResultsCZ interface.
 */
export function instanceOfTvSeriesWatchProviders200ResponseResultsCZ(value: object): value is TvSeriesWatchProviders200ResponseResultsCZ {
    return true;
}

export function TvSeriesWatchProviders200ResponseResultsCZFromJSON(json: any): TvSeriesWatchProviders200ResponseResultsCZ {
    return TvSeriesWatchProviders200ResponseResultsCZFromJSONTyped(json, false);
}

export function TvSeriesWatchProviders200ResponseResultsCZFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeriesWatchProviders200ResponseResultsCZ {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'] == null ? undefined : json['link'],
        'flatrate': json['flatrate'] == null ? undefined : ((json['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsCZFlatrateInnerFromJSON)),
    };
}

export function TvSeriesWatchProviders200ResponseResultsCZToJSON(json: any): TvSeriesWatchProviders200ResponseResultsCZ {
    return TvSeriesWatchProviders200ResponseResultsCZToJSONTyped(json, false);
}

export function TvSeriesWatchProviders200ResponseResultsCZToJSONTyped(value?: TvSeriesWatchProviders200ResponseResultsCZ | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
        'flatrate': value['flatrate'] == null ? undefined : ((value['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsCZFlatrateInnerToJSON)),
    };
}

