/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TvSeriesWatchProviders200ResponseResultsSAFlatrateInner } from './TvSeriesWatchProviders200ResponseResultsSAFlatrateInner';
import {
    TvSeriesWatchProviders200ResponseResultsSAFlatrateInnerFromJSON,
    TvSeriesWatchProviders200ResponseResultsSAFlatrateInnerFromJSONTyped,
    TvSeriesWatchProviders200ResponseResultsSAFlatrateInnerToJSON,
    TvSeriesWatchProviders200ResponseResultsSAFlatrateInnerToJSONTyped,
} from './TvSeriesWatchProviders200ResponseResultsSAFlatrateInner';

/**
 * 
 * @export
 * @interface TvSeasonWatchProviders200ResponseResultsSA
 */
export interface TvSeasonWatchProviders200ResponseResultsSA {
    /**
     * 
     * @type {string}
     * @memberof TvSeasonWatchProviders200ResponseResultsSA
     */
    link?: string;
    /**
     * 
     * @type {Array<TvSeriesWatchProviders200ResponseResultsSAFlatrateInner>}
     * @memberof TvSeasonWatchProviders200ResponseResultsSA
     */
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsSAFlatrateInner>;
}

/**
 * Check if a given object implements the TvSeasonWatchProviders200ResponseResultsSA interface.
 */
export function instanceOfTvSeasonWatchProviders200ResponseResultsSA(value: object): value is TvSeasonWatchProviders200ResponseResultsSA {
    return true;
}

export function TvSeasonWatchProviders200ResponseResultsSAFromJSON(json: any): TvSeasonWatchProviders200ResponseResultsSA {
    return TvSeasonWatchProviders200ResponseResultsSAFromJSONTyped(json, false);
}

export function TvSeasonWatchProviders200ResponseResultsSAFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeasonWatchProviders200ResponseResultsSA {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'] == null ? undefined : json['link'],
        'flatrate': json['flatrate'] == null ? undefined : ((json['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsSAFlatrateInnerFromJSON)),
    };
}

export function TvSeasonWatchProviders200ResponseResultsSAToJSON(json: any): TvSeasonWatchProviders200ResponseResultsSA {
    return TvSeasonWatchProviders200ResponseResultsSAToJSONTyped(json, false);
}

export function TvSeasonWatchProviders200ResponseResultsSAToJSONTyped(value?: TvSeasonWatchProviders200ResponseResultsSA | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
        'flatrate': value['flatrate'] == null ? undefined : ((value['flatrate'] as Array<any>).map(TvSeriesWatchProviders200ResponseResultsSAFlatrateInnerToJSON)),
    };
}

