/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TvSeasonVideos200ResponseResultsInner } from './TvSeasonVideos200ResponseResultsInner';
import {
    TvSeasonVideos200ResponseResultsInnerFromJSON,
    TvSeasonVideos200ResponseResultsInnerFromJSONTyped,
    TvSeasonVideos200ResponseResultsInnerToJSON,
    TvSeasonVideos200ResponseResultsInnerToJSONTyped,
} from './TvSeasonVideos200ResponseResultsInner';

/**
 * 
 * @export
 * @interface TvSeasonVideos200Response
 */
export interface TvSeasonVideos200Response {
    /**
     * 
     * @type {number}
     * @memberof TvSeasonVideos200Response
     */
    id?: number;
    /**
     * 
     * @type {Array<TvSeasonVideos200ResponseResultsInner>}
     * @memberof TvSeasonVideos200Response
     */
    results?: Array<TvSeasonVideos200ResponseResultsInner>;
}

/**
 * Check if a given object implements the TvSeasonVideos200Response interface.
 */
export function instanceOfTvSeasonVideos200Response(value: object): value is TvSeasonVideos200Response {
    return true;
}

export function TvSeasonVideos200ResponseFromJSON(json: any): TvSeasonVideos200Response {
    return TvSeasonVideos200ResponseFromJSONTyped(json, false);
}

export function TvSeasonVideos200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeasonVideos200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(TvSeasonVideos200ResponseResultsInnerFromJSON)),
    };
}

export function TvSeasonVideos200ResponseToJSON(json: any): TvSeasonVideos200Response {
    return TvSeasonVideos200ResponseToJSONTyped(json, false);
}

export function TvSeasonVideos200ResponseToJSONTyped(value?: TvSeasonVideos200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(TvSeasonVideos200ResponseResultsInnerToJSON)),
    };
}

