/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WatchProvidersMovieList200ResponseResultsInner } from './WatchProvidersMovieList200ResponseResultsInner';
import {
    WatchProvidersMovieList200ResponseResultsInnerFromJSON,
    WatchProvidersMovieList200ResponseResultsInnerFromJSONTyped,
    WatchProvidersMovieList200ResponseResultsInnerToJSON,
    WatchProvidersMovieList200ResponseResultsInnerToJSONTyped,
} from './WatchProvidersMovieList200ResponseResultsInner';

/**
 * 
 * @export
 * @interface WatchProvidersMovieList200Response
 */
export interface WatchProvidersMovieList200Response {
    /**
     * 
     * @type {Array<WatchProvidersMovieList200ResponseResultsInner>}
     * @memberof WatchProvidersMovieList200Response
     */
    results?: Array<WatchProvidersMovieList200ResponseResultsInner>;
}

/**
 * Check if a given object implements the WatchProvidersMovieList200Response interface.
 */
export function instanceOfWatchProvidersMovieList200Response(value: object): value is WatchProvidersMovieList200Response {
    return true;
}

export function WatchProvidersMovieList200ResponseFromJSON(json: any): WatchProvidersMovieList200Response {
    return WatchProvidersMovieList200ResponseFromJSONTyped(json, false);
}

export function WatchProvidersMovieList200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WatchProvidersMovieList200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(WatchProvidersMovieList200ResponseResultsInnerFromJSON)),
    };
}

export function WatchProvidersMovieList200ResponseToJSON(json: any): WatchProvidersMovieList200Response {
    return WatchProvidersMovieList200ResponseToJSONTyped(json, false);
}

export function WatchProvidersMovieList200ResponseToJSONTyped(value?: WatchProvidersMovieList200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(WatchProvidersMovieList200ResponseResultsInnerToJSON)),
    };
}

