/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WatchProvidersAvailableRegions200ResponseResultsInner } from './WatchProvidersAvailableRegions200ResponseResultsInner';
import {
    WatchProvidersAvailableRegions200ResponseResultsInnerFromJSON,
    WatchProvidersAvailableRegions200ResponseResultsInnerFromJSONTyped,
    WatchProvidersAvailableRegions200ResponseResultsInnerToJSON,
    WatchProvidersAvailableRegions200ResponseResultsInnerToJSONTyped,
} from './WatchProvidersAvailableRegions200ResponseResultsInner';

/**
 * 
 * @export
 * @interface WatchProvidersAvailableRegions200Response
 */
export interface WatchProvidersAvailableRegions200Response {
    /**
     * 
     * @type {Array<WatchProvidersAvailableRegions200ResponseResultsInner>}
     * @memberof WatchProvidersAvailableRegions200Response
     */
    results?: Array<WatchProvidersAvailableRegions200ResponseResultsInner>;
}

/**
 * Check if a given object implements the WatchProvidersAvailableRegions200Response interface.
 */
export function instanceOfWatchProvidersAvailableRegions200Response(value: object): value is WatchProvidersAvailableRegions200Response {
    return true;
}

export function WatchProvidersAvailableRegions200ResponseFromJSON(json: any): WatchProvidersAvailableRegions200Response {
    return WatchProvidersAvailableRegions200ResponseFromJSONTyped(json, false);
}

export function WatchProvidersAvailableRegions200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WatchProvidersAvailableRegions200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(WatchProvidersAvailableRegions200ResponseResultsInnerFromJSON)),
    };
}

export function WatchProvidersAvailableRegions200ResponseToJSON(json: any): WatchProvidersAvailableRegions200Response {
    return WatchProvidersAvailableRegions200ResponseToJSONTyped(json, false);
}

export function WatchProvidersAvailableRegions200ResponseToJSONTyped(value?: WatchProvidersAvailableRegions200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(WatchProvidersAvailableRegions200ResponseResultsInnerToJSON)),
    };
}

